__term_sd_task_pre_model_1 =====核心模型===== OFF
__term_sd_task_pre_model_2 bert-base-uncased ON
__term_sd_task_pre_model_3 bert-base-uncased ON
__term_sd_task_pre_model_4 bert-base-uncased ON
__term_sd_task_pre_model_5 bert-base-uncased ON
__term_sd_task_pre_model_6 CLIP-ViT-bigG-14-laion2B-39B-b160k ON
__term_sd_task_pre_model_7 CLIP-ViT-bigG-14-laion2B-39B-b160k ON
__term_sd_task_pre_model_8 CLIP-ViT-bigG-14-laion2B-39B-b160k ON
__term_sd_task_pre_model_9 CLIP-ViT-bigG-14-laion2B-39B-b160k ON
__term_sd_task_pre_model_10 CLIP-ViT-bigG-14-laion2B-39B-b160k ON
__term_sd_task_pre_model_11 clip-vit-large-patch14 ON
__term_sd_task_pre_model_12 clip-vit-large-patch14 ON
__term_sd_task_pre_model_13 clip-vit-large-patch14 ON
__term_sd_task_pre_model_14 clip-vit-large-patch14 ON
__term_sd_task_pre_model_15 clip-vit-large-patch14 ON
__term_sd_task_pre_model_16 clip-vit-large-patch14 ON
__term_sd_task_pre_model_17 stable-diffusion-2-clip ON
__term_sd_task_pre_model_18 stable-diffusion-2-clip ON
__term_sd_task_pre_model_19 stable-diffusion-2-clip ON
__term_sd_task_pre_model_20 stable-diffusion-2-clip ON
__term_sd_task_pre_model_21 stable-diffusion-2-clip ON
__term_sd_task_pre_model_22 stable-diffusion-2-clip ON
__term_sd_task_pre_model_23 stable-diffusion-safety-checker ON
__term_sd_task_pre_model_24 stable-diffusion-safety-checker ON
__term_sd_task_pre_model_25 stable-diffusion-safety-checker ON
__term_sd_task_pre_model_26 lama ON
__term_sd_task_pre_model_27 =====放大模型===== OFF
__term_sd_task_pre_model_28 ESRGAN_SRx4_DF2KOST_official-ff704c30 ON
__term_sd_task_pre_model_29 RealESRGAN_x2plus ON
__term_sd_task_pre_model_30 RealESRGAN_x4plus ON
__term_sd_task_pre_model_31 RealESRGAN_x4plus_anime_6B ON
__term_sd_task_pre_model_32 =====配置文件===== OFF
__term_sd_task_pre_model_33 INITIAL_MODELS ON
__term_sd_task_pre_model_34 models.yaml ON
__term_sd_task_pre_model_35 models.yaml.example ON
__term_sd_task_pre_model_36 sd_xl_base.yaml ON
__term_sd_task_pre_model_37 sd_xl_refiner.yaml ON
__term_sd_task_pre_model_38 v1-finetune.yaml ON
__term_sd_task_pre_model_39 v1-finetune_style.yaml ON
__term_sd_task_pre_model_40 v1-inference-v.yaml ON
__term_sd_task_pre_model_41 v1-inference.yaml ON
__term_sd_task_pre_model_42 v1-inpainting-inference.yaml ON
__term_sd_task_pre_model_43 v1-m1-finetune.yaml ON
__term_sd_task_pre_model_44 v2-inference-v.yaml ON
__term_sd_task_pre_model_45 v2-inference.yaml ON
__term_sd_task_pre_model_46 v2-inpainting-inference-v.yaml ON
__term_sd_task_pre_model_47 v2-inpainting-inference.yaml ON
__term_sd_task_pre_model_48 =====基础模型===== OFF
__term_sd_task_pre_model_49 =====SD1.5大模型===== OFF
__term_sd_task_pre_model_50 sd1.5-official OFF
__term_sd_task_pre_model_51 sd1.5-official OFF
__term_sd_task_pre_model_52 sd1.5-official OFF
__term_sd_task_pre_model_53 sd1.5-official OFF
__term_sd_task_pre_model_54 sd1.5-official OFF
__term_sd_task_pre_model_55 sd1.5-official OFF
__term_sd_task_pre_model_56 sd1.5-official OFF
__term_sd_task_pre_model_57 sd1.5-official OFF
__term_sd_task_pre_model_58 sd1.5-official OFF
__term_sd_task_pre_model_59 sd1.5-official OFF
__term_sd_task_pre_model_60 sd1.5-official OFF
__term_sd_task_pre_model_61 sd1.5-official OFF
__term_sd_task_pre_model_62 sd1.5-official OFF
__term_sd_task_pre_model_63 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_64 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_65 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_66 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_67 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_68 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_69 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_70 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_71 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_72 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_73 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_74 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_75 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_76 openjourney OFF
__term_sd_task_pre_model_77 openjourney OFF
__term_sd_task_pre_model_78 openjourney OFF
__term_sd_task_pre_model_79 openjourney OFF
__term_sd_task_pre_model_80 openjourney OFF
__term_sd_task_pre_model_81 openjourney OFF
__term_sd_task_pre_model_82 openjourney OFF
__term_sd_task_pre_model_83 openjourney OFF
__term_sd_task_pre_model_84 openjourney OFF
__term_sd_task_pre_model_85 openjourney OFF
__term_sd_task_pre_model_86 openjourney OFF
__term_sd_task_pre_model_87 openjourney OFF
__term_sd_task_pre_model_88 openjourney OFF
__term_sd_task_pre_model_89 =====SD2.1大模型===== OFF
__term_sd_task_pre_model_90 sd2.1-official OFF
__term_sd_task_pre_model_91 sd2.1-official OFF
__term_sd_task_pre_model_92 sd2.1-official OFF
__term_sd_task_pre_model_93 sd2.1-official OFF
__term_sd_task_pre_model_94 sd2.1-official OFF
__term_sd_task_pre_model_95 sd2.1-official OFF
__term_sd_task_pre_model_96 sd2.1-official OFF
__term_sd_task_pre_model_97 sd2.1-official OFF
__term_sd_task_pre_model_98 sd2.1-official OFF
__term_sd_task_pre_model_99 sd2.1-official OFF
__term_sd_task_pre_model_100 sd2.1-official OFF
__term_sd_task_pre_model_101 sd2.1-official OFF
__term_sd_task_pre_model_102 sd2.1-official OFF
__term_sd_task_pre_model_103 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_104 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_105 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_106 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_107 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_108 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_109 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_110 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_111 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_112 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_113 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_114 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_115 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_116 =====SDXL大模型===== OFF
__term_sd_task_pre_model_117 sdxl OFF
__term_sd_task_pre_model_118 sdxl OFF
__term_sd_task_pre_model_119 sdxl OFF
__term_sd_task_pre_model_120 sdxl OFF
__term_sd_task_pre_model_121 sdxl OFF
__term_sd_task_pre_model_122 sdxl OFF
__term_sd_task_pre_model_123 sdxl OFF
__term_sd_task_pre_model_124 sdxl OFF
__term_sd_task_pre_model_125 sdxl OFF
__term_sd_task_pre_model_126 sdxl OFF
__term_sd_task_pre_model_127 sdxl OFF
__term_sd_task_pre_model_128 sdxl OFF
__term_sd_task_pre_model_129 sdxl OFF
__term_sd_task_pre_model_130 sdxl OFF
__term_sd_task_pre_model_131 sdxl OFF
__term_sd_task_pre_model_132 sdxl OFF
__term_sd_task_pre_model_133 sdxl OFF
__term_sd_task_pre_model_134 sdxl OFF
__term_sd_task_pre_model_135 sdxl-refind OFF
__term_sd_task_pre_model_136 sdxl-refind OFF
__term_sd_task_pre_model_137 sdxl-refind OFF
__term_sd_task_pre_model_138 sdxl-refind OFF
__term_sd_task_pre_model_139 sdxl-refind OFF
__term_sd_task_pre_model_140 sdxl-refind OFF
__term_sd_task_pre_model_141 sdxl-refind OFF
__term_sd_task_pre_model_142 sdxl-refind OFF
__term_sd_task_pre_model_143 sdxl-refind OFF
__term_sd_task_pre_model_144 sdxl-refind OFF
__term_sd_task_pre_model_145 sdxl-refind OFF
__term_sd_task_pre_model_146 sdxl-refind OFF
__term_sd_task_pre_model_147 =====VAE模型===== OFF
__term_sd_task_pre_model_148 sd-vae-ft-mse ON
__term_sd_task_pre_model_149 sd-vae-ft-mse ON
__term_sd_task_pre_model_150 sdxl-vae OFF
__term_sd_task_pre_model_151 sdxl-vae OFF
__term_sd_task_pre_model_152 =====Embedding模型===== OFF
__term_sd_task_pre_model_153 EasyNegative OFF
__term_sd_task_pre_model_154 ahx-beta-453407d OFF
__term_sd_task_pre_model_155 =====控制模型===== OFF
__term_sd_task_pre_model_156 =====ControlNet(SD1.5)模型===== OFF
__term_sd_task_pre_model_157 canny OFF
__term_sd_task_pre_model_158 canny OFF
__term_sd_task_pre_model_159 depth OFF
__term_sd_task_pre_model_160 depth OFF
__term_sd_task_pre_model_161 inpaint OFF
__term_sd_task_pre_model_162 inpaint OFF
__term_sd_task_pre_model_163 ip2p OFF
__term_sd_task_pre_model_164 ip2p OFF
__term_sd_task_pre_model_165 lineart OFF
__term_sd_task_pre_model_166 lineart OFF
__term_sd_task_pre_model_167 lineart-anime OFF
__term_sd_task_pre_model_168 lineart-anime OFF
__term_sd_task_pre_model_169 mlsd OFF
__term_sd_task_pre_model_170 mlsd OFF
__term_sd_task_pre_model_171 normal-bae OFF
__term_sd_task_pre_model_172 normal-bae OFF
__term_sd_task_pre_model_173 openpose OFF
__term_sd_task_pre_model_174 openpose OFF
__term_sd_task_pre_model_175 qrcode OFF
__term_sd_task_pre_model_176 qrcode OFF
__term_sd_task_pre_model_177 scribble OFF
__term_sd_task_pre_model_178 scribble OFF
__term_sd_task_pre_model_179 seg OFF
__term_sd_task_pre_model_180 seg OFF
__term_sd_task_pre_model_181 shuffle OFF
__term_sd_task_pre_model_182 shuffle OFF
__term_sd_task_pre_model_183 softedge OFF
__term_sd_task_pre_model_184 softedge OFF
__term_sd_task_pre_model_185 tile OFF
__term_sd_task_pre_model_186 tile OFF
__term_sd_task_pre_model_187 =====T2I-Adapter(SD1.5)模型===== OFF
__term_sd_task_pre_model_188 canny OFF
__term_sd_task_pre_model_189 canny OFF
__term_sd_task_pre_model_190 depth OFF
__term_sd_task_pre_model_191 depth OFF
__term_sd_task_pre_model_192 sketch OFF
__term_sd_task_pre_model_193 sketch OFF
__term_sd_task_pre_model_194 zoedepth OFF
__term_sd_task_pre_model_195 zoedepth OFF
__term_sd_task_pre_model_196 =====T2I-Adapter(SDXL)模型===== OFF
__term_sd_task_pre_model_197 canny OFF
__term_sd_task_pre_model_198 canny OFF
__term_sd_task_pre_model_199 lineart OFF
__term_sd_task_pre_model_200 lineart OFF
__term_sd_task_pre_model_201 sketch OFF
__term_sd_task_pre_model_202 sketch OFF
__term_sd_task_pre_model_203 zoedepth OFF
__term_sd_task_pre_model_204 zoedepth OFF
__term_sd_task_pre_model_205 =====IP-Adapter(SD1.5)模型===== OFF
__term_sd_task_pre_model_206 clip_vision OFF
__term_sd_task_pre_model_207 clip_vision OFF
__term_sd_task_pre_model_208 plus-face OFF
__term_sd_task_pre_model_209 plus-face OFF
__term_sd_task_pre_model_210 plus OFF
__term_sd_task_pre_model_211 plus OFF
__term_sd_task_pre_model_212 normal OFF
__term_sd_task_pre_model_213 normal OFF
__term_sd_task_pre_model_214 =====IP-Adapter(SDXL)模型===== OFF
__term_sd_task_pre_model_215 clip_vision OFF
__term_sd_task_pre_model_216 clip_vision OFF
__term_sd_task_pre_model_217 normal OFF
__term_sd_task_pre_model_218 normal OFF
