__term_sd_task_pre_model_1 bert-base-uncased ON
__term_sd_task_pre_model_2 bert-base-uncased ON
__term_sd_task_pre_model_3 bert-base-uncased ON
__term_sd_task_pre_model_4 bert-base-uncased ON
__term_sd_task_pre_model_5 CLIP-ViT-bigG-14-laion2B-39B-b160k ON
__term_sd_task_pre_model_6 CLIP-ViT-bigG-14-laion2B-39B-b160k ON
__term_sd_task_pre_model_7 CLIP-ViT-bigG-14-laion2B-39B-b160k ON
__term_sd_task_pre_model_8 CLIP-ViT-bigG-14-laion2B-39B-b160k ON
__term_sd_task_pre_model_9 CLIP-ViT-bigG-14-laion2B-39B-b160k ON
__term_sd_task_pre_model_10 clip-vit-large-patch14 ON
__term_sd_task_pre_model_11 clip-vit-large-patch14 ON
__term_sd_task_pre_model_12 clip-vit-large-patch14 ON
__term_sd_task_pre_model_13 clip-vit-large-patch14 ON
__term_sd_task_pre_model_14 clip-vit-large-patch14 ON
__term_sd_task_pre_model_15 clip-vit-large-patch14 ON
__term_sd_task_pre_model_16 sd-vae-ft-mse ON
__term_sd_task_pre_model_17 sd-vae-ft-mse ON
__term_sd_task_pre_model_18 stable-diffusion-2-clip ON
__term_sd_task_pre_model_19 stable-diffusion-2-clip ON
__term_sd_task_pre_model_20 stable-diffusion-2-clip ON
__term_sd_task_pre_model_21 stable-diffusion-2-clip ON
__term_sd_task_pre_model_22 stable-diffusion-2-clip ON
__term_sd_task_pre_model_23 stable-diffusion-2-clip ON
__term_sd_task_pre_model_24 stable-diffusion-safety-checker ON
__term_sd_task_pre_model_25 stable-diffusion-safety-checker ON
__term_sd_task_pre_model_26 stable-diffusion-safety-checker ON
__term_sd_task_pre_model_27 lama ON
__term_sd_task_pre_model_28 ESRGAN_SRx4_DF2KOST_official-ff704c30 ON
__term_sd_task_pre_model_29 RealESRGAN_x2plus ON
__term_sd_task_pre_model_30 RealESRGAN_x4plus ON
__term_sd_task_pre_model_31 RealESRGAN_x4plus_anime_6B ON
__term_sd_task_pre_model_32 INITIAL_MODELS ON
__term_sd_task_pre_model_33 models.yaml ON
__term_sd_task_pre_model_34 models.yaml.example ON
__term_sd_task_pre_model_35 sd_xl_base.yaml ON
__term_sd_task_pre_model_36 sd_xl_refiner.yaml ON
__term_sd_task_pre_model_37 v1-finetune.yaml ON
__term_sd_task_pre_model_38 v1-finetune_style.yaml ON
__term_sd_task_pre_model_39 v1-inference-v.yaml ON
__term_sd_task_pre_model_40 v1-inference.yaml ON
__term_sd_task_pre_model_41 v1-inpainting-inference.yaml ON
__term_sd_task_pre_model_42 v1-m1-finetune.yaml ON
__term_sd_task_pre_model_43 v2-inference-v.yaml ON
__term_sd_task_pre_model_44 v2-inference.yaml ON
__term_sd_task_pre_model_45 v2-inpainting-inference-v.yaml ON
__term_sd_task_pre_model_46 v2-inpainting-inference.yaml ON
