__term_sd_task_pre_model_1 (提示：) OFF
__term_sd_task_pre_model_2 (建议使用InvokeAI自带的模型管理下载和添加模型) OFF
__term_sd_task_pre_model_3 (不推荐使用Term-SD下载InvokeAI的模型) OFF
__term_sd_task_pre_model_4 =====核心模型===== OFF
__term_sd_task_pre_model_5 bert-base-uncased OFF
__term_sd_task_pre_model_6 bert-base-uncased OFF
__term_sd_task_pre_model_7 bert-base-uncased OFF
__term_sd_task_pre_model_8 bert-base-uncased OFF
__term_sd_task_pre_model_9 CLIP-ViT-bigG-14-laion2B-39B-b160k OFF
__term_sd_task_pre_model_10 CLIP-ViT-bigG-14-laion2B-39B-b160k OFF
__term_sd_task_pre_model_11 CLIP-ViT-bigG-14-laion2B-39B-b160k OFF
__term_sd_task_pre_model_12 CLIP-ViT-bigG-14-laion2B-39B-b160k OFF
__term_sd_task_pre_model_13 CLIP-ViT-bigG-14-laion2B-39B-b160k OFF
__term_sd_task_pre_model_14 clip-vit-large-patch14 OFF
__term_sd_task_pre_model_15 clip-vit-large-patch14 OFF
__term_sd_task_pre_model_16 clip-vit-large-patch14(492.3m) OFF
__term_sd_task_pre_model_17 clip-vit-large-patch14 OFF
__term_sd_task_pre_model_18 clip-vit-large-patch14 OFF
__term_sd_task_pre_model_19 clip-vit-large-patch14 OFF
__term_sd_task_pre_model_20 stable-diffusion-2-clip OFF
__term_sd_task_pre_model_21 stable-diffusion-2-clip(1.36g) OFF
__term_sd_task_pre_model_22 stable-diffusion-2-clip OFF
__term_sd_task_pre_model_23 stable-diffusion-2-clip OFF
__term_sd_task_pre_model_24 stable-diffusion-2-clip OFF
__term_sd_task_pre_model_25 stable-diffusion-2-clip OFF
__term_sd_task_pre_model_26 stable-diffusion-safety-checker OFF
__term_sd_task_pre_model_27 stable-diffusion-safety-checker(1.22g) OFF
__term_sd_task_pre_model_28 stable-diffusion-safety-checker OFF
__term_sd_task_pre_model_29 lama(205.6m) OFF
__term_sd_task_pre_model_30 =====放大模型===== OFF
__term_sd_task_pre_model_31 ESRGAN_SRx4_DF2KOST_official-ff704c30(66.9m) OFF
__term_sd_task_pre_model_32 RealESRGAN_x2plus(67m) OFF
__term_sd_task_pre_model_33 RealESRGAN_x4plus(67m) OFF
__term_sd_task_pre_model_34 RealESRGAN_x4plus_anime_6B(17.9m) OFF
__term_sd_task_pre_model_35 =====配置文件===== OFF
__term_sd_task_pre_model_36 INITIAL_MODELS OFF
__term_sd_task_pre_model_37 models.yaml OFF
__term_sd_task_pre_model_38 models.yaml.example OFF
__term_sd_task_pre_model_39 sd_xl_base.yaml OFF
__term_sd_task_pre_model_40 sd_xl_refiner.yaml OFF
__term_sd_task_pre_model_41 v1-finetune.yaml OFF
__term_sd_task_pre_model_42 v1-finetune_style.yaml OFF
__term_sd_task_pre_model_43 v1-inference-v.yaml OFF
__term_sd_task_pre_model_44 v1-inference.yaml OFF
__term_sd_task_pre_model_45 v1-inpainting-inference.yaml OFF
__term_sd_task_pre_model_46 v1-m1-finetune.yaml OFF
__term_sd_task_pre_model_47 v2-inference-v.yaml OFF
__term_sd_task_pre_model_48 v2-inference.yaml OFF
__term_sd_task_pre_model_49 v2-inpainting-inference-v.yaml OFF
__term_sd_task_pre_model_50 v2-inpainting-inference.yaml OFF
__term_sd_task_pre_model_51 =====基础模型===== OFF
__term_sd_task_pre_model_52 =====SD1.5大模型===== OFF
__term_sd_task_pre_model_53 sd1.5-official OFF
__term_sd_task_pre_model_54 sd1.5-official OFF
__term_sd_task_pre_model_55 sd1.5-official OFF
__term_sd_task_pre_model_56 sd1.5-official OFF
__term_sd_task_pre_model_57 sd1.5-official(246.1m) OFF
__term_sd_task_pre_model_58 sd1.5-official OFF
__term_sd_task_pre_model_59 sd1.5-official OFF
__term_sd_task_pre_model_60 sd1.5-official OFF
__term_sd_task_pre_model_61 sd1.5-official OFF
__term_sd_task_pre_model_62 sd1.5-official OFF
__term_sd_task_pre_model_63 sd1.5-official(1.72g) OFF
__term_sd_task_pre_model_64 sd1.5-official OFF
__term_sd_task_pre_model_65 sd1.5-official(167.3m) OFF
__term_sd_task_pre_model_66 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_67 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_68 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_69 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_70 sd1.5-inpaint-official(246.1m) OFF
__term_sd_task_pre_model_71 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_72 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_73 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_74 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_75 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_76 sd1.5-inpaint-official(1.72g) OFF
__term_sd_task_pre_model_77 sd1.5-inpaint-official OFF
__term_sd_task_pre_model_78 sd1.5-inpaint-official(167.3m) OFF
__term_sd_task_pre_model_79 openjourney OFF
__term_sd_task_pre_model_80 openjourney OFF
__term_sd_task_pre_model_81 openjourney OFF
__term_sd_task_pre_model_82 openjourney OFF
__term_sd_task_pre_model_83 openjourney(246.1m) OFF
__term_sd_task_pre_model_84 openjourney OFF
__term_sd_task_pre_model_85 openjourney OFF
__term_sd_task_pre_model_86 openjourney OFF
__term_sd_task_pre_model_87 openjourney OFF
__term_sd_task_pre_model_88 openjourney OFF
__term_sd_task_pre_model_89 openjourney(1.72g) OFF
__term_sd_task_pre_model_90 openjourney OFF
__term_sd_task_pre_model_91 openjourney(246.1m) OFF
__term_sd_task_pre_model_92 =====SD2.1大模型===== OFF
__term_sd_task_pre_model_93 sd2.1-official OFF
__term_sd_task_pre_model_94 sd2.1-official OFF
__term_sd_task_pre_model_95 sd2.1-official OFF
__term_sd_task_pre_model_96 sd2.1-official OFF
__term_sd_task_pre_model_97 sd2.1-official(680.8m) OFF
__term_sd_task_pre_model_98 sd2.1-official OFF
__term_sd_task_pre_model_99 sd2.1-official OFF
__term_sd_task_pre_model_100 sd2.1-official OFF
__term_sd_task_pre_model_101 sd2.1-official OFF
__term_sd_task_pre_model_102 sd2.1-official OFF
__term_sd_task_pre_model_103 sd2.1-official(1.73g) OFF
__term_sd_task_pre_model_104 sd2.1-official OFF
__term_sd_task_pre_model_105 sd2.1-official(167.3m) OFF
__term_sd_task_pre_model_106 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_107 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_108 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_109 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_110 sd2.1-inpaint-official(680.8m) OFF
__term_sd_task_pre_model_111 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_112 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_113 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_114 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_115 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_116 sd2.1-inpaint-official(1.73g) OFF
__term_sd_task_pre_model_117 sd2.1-inpaint-official OFF
__term_sd_task_pre_model_118 sd2.1-inpaint-official(167.3m) OFF
__term_sd_task_pre_model_119 =====SDXL大模型===== OFF
__term_sd_task_pre_model_120 sdxl OFF
__term_sd_task_pre_model_121 sdxl OFF
__term_sd_task_pre_model_122 sdxl OFF
__term_sd_task_pre_model_123 sdxl(246.1m) OFF
__term_sd_task_pre_model_124 sdxl OFF
__term_sd_task_pre_model_125 sdxl(1.39g) OFF
__term_sd_task_pre_model_126 sdxl OFF
__term_sd_task_pre_model_127 sdxl OFF
__term_sd_task_pre_model_128 sdxl OFF
__term_sd_task_pre_model_129 sdxl OFF
__term_sd_task_pre_model_130 sdxl OFF
__term_sd_task_pre_model_131 sdxl OFF
__term_sd_task_pre_model_132 sdxl OFF
__term_sd_task_pre_model_133 sdxl OFF
__term_sd_task_pre_model_134 sdxl OFF
__term_sd_task_pre_model_135 sdxl(5.14g) OFF
__term_sd_task_pre_model_136 sdxl OFF
__term_sd_task_pre_model_137 sdxl(167.3m) OFF
__term_sd_task_pre_model_138 sdxl-refind OFF
__term_sd_task_pre_model_139 sdxl-refind OFF
__term_sd_task_pre_model_140 sdxl-refind OFF
__term_sd_task_pre_model_141 sdxl-refind(1.39g) OFF
__term_sd_task_pre_model_142 sdxl-refind OFF
__term_sd_task_pre_model_143 sdxl-refind OFF
__term_sd_task_pre_model_144 sdxl-refind OFF
__term_sd_task_pre_model_145 sdxl-refind OFF
__term_sd_task_pre_model_146 sdxl-refind OFF
__term_sd_task_pre_model_147 sdxl-refind(5.14g) OFF
__term_sd_task_pre_model_148 sdxl-refind OFF
__term_sd_task_pre_model_149 sdxl-refind(167.3m) OFF
__term_sd_task_pre_model_150 =====VAE模型===== OFF
__term_sd_task_pre_model_151 sd-vae-ft-mse OFF
__term_sd_task_pre_model_152 sd-vae-ft-mse(334.6m) OFF
__term_sd_task_pre_model_153 sdxl-vae OFF
__term_sd_task_pre_model_154 sdxl-vae(334.6m) OFF
__term_sd_task_pre_model_155 =====Embedding模型===== OFF
__term_sd_task_pre_model_156 EasyNegative(0.1m) OFF
__term_sd_task_pre_model_157 ahx-beta-453407d(0.1m) OFF
__term_sd_task_pre_model_158 =====控制模型===== OFF
__term_sd_task_pre_model_159 =====ControlNet(SD1.5)模型===== OFF
__term_sd_task_pre_model_160 canny OFF
__term_sd_task_pre_model_161 canny(1.45g) OFF
__term_sd_task_pre_model_162 depth OFF
__term_sd_task_pre_model_163 depth(1.45g) OFF
__term_sd_task_pre_model_164 inpaint OFF
__term_sd_task_pre_model_165 inpaint(1.45g) OFF
__term_sd_task_pre_model_166 ip2p OFF
__term_sd_task_pre_model_167 ip2p(1.45g) OFF
__term_sd_task_pre_model_168 lineart OFF
__term_sd_task_pre_model_169 lineart(1.45g) OFF
__term_sd_task_pre_model_170 lineart-anime OFF
__term_sd_task_pre_model_171 lineart-anime(1.45g) OFF
__term_sd_task_pre_model_172 mlsd OFF
__term_sd_task_pre_model_173 mlsd(1.45g) OFF
__term_sd_task_pre_model_174 normal-bae OFF
__term_sd_task_pre_model_175 normal-bae(1.45g) OFF
__term_sd_task_pre_model_176 openpose OFF
__term_sd_task_pre_model_177 openpose(1.45g) OFF
__term_sd_task_pre_model_178 qrcode OFF
__term_sd_task_pre_model_179 qrcode(1.45g) OFF
__term_sd_task_pre_model_180 scribble OFF
__term_sd_task_pre_model_181 scribble(1.45g) OFF
__term_sd_task_pre_model_182 seg OFF
__term_sd_task_pre_model_183 seg(1.45g) OFF
__term_sd_task_pre_model_184 shuffle OFF
__term_sd_task_pre_model_185 shuffle(1.45g) OFF
__term_sd_task_pre_model_186 softedge OFF
__term_sd_task_pre_model_187 softedge(1.45g) OFF
__term_sd_task_pre_model_188 tile OFF
__term_sd_task_pre_model_189 tile(1.45g) OFF
__term_sd_task_pre_model_190 =====T2I-Adapter(SD1.5)模型===== OFF
__term_sd_task_pre_model_191 canny OFF
__term_sd_task_pre_model_192 canny(308m) OFF
__term_sd_task_pre_model_193 depth OFF
__term_sd_task_pre_model_194 depth(308m) OFF
__term_sd_task_pre_model_195 sketch OFF
__term_sd_task_pre_model_196 sketch(308m) OFF
__term_sd_task_pre_model_197 zoedepth OFF
__term_sd_task_pre_model_198 zoedepth(308m) OFF
__term_sd_task_pre_model_199 =====T2I-Adapter(SDXL)模型===== OFF
__term_sd_task_pre_model_200 canny OFF
__term_sd_task_pre_model_201 canny(316m) OFF
__term_sd_task_pre_model_202 lineart OFF
__term_sd_task_pre_model_203 lineart(316m) OFF
__term_sd_task_pre_model_204 sketch OFF
__term_sd_task_pre_model_205 sketch(316m) OFF
__term_sd_task_pre_model_206 zoedepth OFF
__term_sd_task_pre_model_207 zoedepth(316m) OFF
__term_sd_task_pre_model_208 =====IP-Adapter(SD1.5)模型===== OFF
__term_sd_task_pre_model_209 clip_vision OFF
__term_sd_task_pre_model_210 clip_vision(2.53g) OFF
__term_sd_task_pre_model_211 plus-face OFF
__term_sd_task_pre_model_212 plus-face(98.1m) OFF
__term_sd_task_pre_model_213 plus OFF
__term_sd_task_pre_model_214 plus(158m) OFF
__term_sd_task_pre_model_215 normal OFF
__term_sd_task_pre_model_216 normal(44.6m) OFF
__term_sd_task_pre_model_217 =====IP-Adapter(SDXL)模型===== OFF
__term_sd_task_pre_model_218 clip_vision OFF
__term_sd_task_pre_model_219 clip_vision(3.69g) OFF
__term_sd_task_pre_model_220 normal OFF
__term_sd_task_pre_model_221 normal(702.6m) OFF
