__term_sd_task_pre_ext_1 git_clone_repository https://github.com/licyk/invoke_tipo "${INVOKEAI_PATH}"/invokeai/nodes ON # 为InvokeAI添加TIPO节点，优化提示词
__term_sd_task_pre_ext_2 git_clone_repository https://github.com/licyk/invoke_wd14_tagger "${INVOKEAI_PATH}"/invokeai/nodes ON # 添加提示词反推节点
__term_sd_task_pre_ext_3 git_clone_repository https://github.com/skunkworxdark/adapters-linked-nodes "${INVOKEAI_PATH}"/invokeai/nodes OFF # 将多个节点（ControlNet、IP-Adapter、T2I-Adapter节点）链接在一起
__term_sd_task_pre_ext_4 git_clone_repository https://github.com/JPPhoto/average-images-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 将多张图像合并取平均值输出
__term_sd_task_pre_ext_5 git_clone_repository https://github.com/VeyDlin/clean-artifact-after-cut-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 去除移除背景后残留的伪影
__term_sd_task_pre_ext_6 git_clone_repository https://github.com/VeyDlin/close-color-mask-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 关闭颜色蒙版
__term_sd_task_pre_ext_7 git_clone_repository https://github.com/VeyDlin/clothing-mask-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 为人物服装生成蒙版
__term_sd_task_pre_ext_8 git_clone_repository https://github.com/VeyDlin/clahe-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 提高图像的对比度
__term_sd_task_pre_ext_9 git_clone_repository https://github.com/dwringer/depth-from-obj-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 从3D文件渲染深度图
__term_sd_task_pre_ext_10 git_clone_repository https://github.com/skunkworxdark/enhance-detail-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 增强图片细节
__term_sd_task_pre_ext_11 git_clone_repository https://github.com/JPPhoto/film-grain-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 生成胶片质感图片
__term_sd_task_pre_ext_12 git_clone_repository https://github.com/mickr777/GPT2RandomPromptMaker "${INVOKEAI_PATH}"/invokeai/nodes OFF # 使用GPT-2生成提示词
__term_sd_task_pre_ext_13 git_clone_repository https://github.com/mildmisery/invokeai-GridToGifNode/blob/main/GridToGif.py "${INVOKEAI_PATH}"/invokeai/nodes OFF # 将多张图片转换为GIF图片
__term_sd_task_pre_ext_14 git_clone_repository https://github.com/blessedcoolant/invoke_meshgraphormer "${INVOKEAI_PATH}"/invokeai/nodes OFF # 为手部生成深度图和蒙版
__term_sd_task_pre_ext_15 git_clone_repository https://github.com/JPPhoto/halftone-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 生成半色调图
__term_sd_task_pre_ext_16 git_clone_repository https://github.com/dwringer/composition-nodes "${INVOKEAI_PATH}"/invokeai/nodes OFF # 蒙版节点包
__term_sd_task_pre_ext_17 git_clone_repository https://github.com/mickr777/imagetoasciiimage "${INVOKEAI_PATH}"/invokeai/nodes OFF # 将输入图像转换为ascii/unicode艺术图像的节点
__term_sd_task_pre_ext_18 git_clone_repository https://github.com/JPPhoto/image-picker-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 从多张图像随机选择一张图像输出
__term_sd_task_pre_ext_19 git_clone_repository https://github.com/VeyDlin/image-resize-plus-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 调整图片大小
__term_sd_task_pre_ext_20 git_clone_repository https://github.com/gogurtenjoyer/latent-upscale "${INVOKEAI_PATH}"/invokeai/nodes OFF # 潜空间放大节点
__term_sd_task_pre_ext_21 git_clone_repository https://github.com/helix4u/load_video_frame "${INVOKEAI_PATH}"/invokeai/nodes OFF # 图片转视频
__term_sd_task_pre_ext_22 git_clone_repository https://github.com/VeyDlin/mask-operations-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 蒙版组合
__term_sd_task_pre_ext_23 git_clone_repository https://github.com/skunkworxdark/metadata-linked-nodes "${INVOKEAI_PATH}"/invokeai/nodes ON # 元数据转换节点
__term_sd_task_pre_ext_24 git_clone_repository https://github.com/skunkworxdark/Prompt-tools-nodes "${INVOKEAI_PATH}"/invokeai/nodes OFF # 提示词工具
__term_sd_task_pre_ext_25 git_clone_repository https://github.com/blessedcoolant/invoke_bria_rmbg "${INVOKEAI_PATH}"/invokeai/nodes ON # 背景移除
__term_sd_task_pre_ext_26 git_clone_repository https://github.com/VeyDlin/remove-background-node "${INVOKEAI_PATH}"/invokeai/nodes OFF # 背景移除
__term_sd_task_pre_ext_27 git_clone_repository https://github.com/skunkworxdark/XYGrid_nodes "${INVOKEAI_PATH}"/invokeai/nodes ON # 添加xyz图工具
