__term_sd_task_sys term_sd_echo "下载模型中"
__term_sd_task_sys term_sd_echo "使用modelscope模型下载源"
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/bert-base-uncased/special_tokens_map.json ./invokeai/models/core/convert/bert-base-uncased
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/bert-base-uncased/tokenizer.json ./invokeai/models/core/convert/bert-base-uncased
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/bert-base-uncased/tokenizer_config.json ./invokeai/models/core/convert/bert-base-uncased
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/bert-base-uncased/vocab.txt ./invokeai/models/core/convert/bert-base-uncased
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k/config.json ./invokeai/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k/merges.txt ./invokeai/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k/special_tokens_map.json ./invokeai/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k/tokenizer_config.json ./invokeai/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k/vocab.json ./invokeai/models/core/convert/CLIP-ViT-bigG-14-laion2B-39B-b160k
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/clip-vit-large-patch14/config.json ./invokeai/models/core/convert/clip-vit-large-patch14
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/clip-vit-large-patch14/merges.txt ./invokeai/models/core/convert/clip-vit-large-patch14
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/clip-vit-large-patch14/model.safetensors ./invokeai/models/core/convert/clip-vit-large-patch14
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/clip-vit-large-patch14/special_tokens_map.json ./invokeai/models/core/convert/clip-vit-large-patch14
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/clip-vit-large-patch14/tokenizer_config.json ./invokeai/models/core/convert/clip-vit-large-patch14
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/clip-vit-large-patch14/vocab.json ./invokeai/models/core/convert/clip-vit-large-patch14
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/sd-vae-ft-mse/config.json ./invokeai/models/core/convert/sd-vae-ft-mse
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/sd-vae-ft-mse/diffusion_pytorch_model.safetensors ./invokeai/models/core/convert/sd-vae-ft-mse
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/stable-diffusion-2-clip/text_encoder/config.json ./invokeai/models/core/convert/stable-diffusion-2-clip/text_encoder
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/stable-diffusion-2-clip/text_encoder/model.safetensors ./invokeai/models/core/convert/stable-diffusion-2-clip/text_encoder
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/stable-diffusion-2-clip/tokenizer/merges.txt ./invokeai/models/core/convert/stable-diffusion-2-clip/tokenizer
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/stable-diffusion-2-clip/tokenizer/special_tokens_map.json ./invokeai/models/core/convert/stable-diffusion-2-clip/tokenizer
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/stable-diffusion-2-clip/tokenizer/tokenizer_config.json ./invokeai/models/core/convert/stable-diffusion-2-clip/tokenizer
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/stable-diffusion-2-clip/tokenizer/vocab.json ./invokeai/models/core/convert/stable-diffusion-2-clip/tokenizer
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/stable-diffusion-safety-checker/config.json ./invokeai/models/core/convert/stable-diffusion-safety-checker
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/stable-diffusion-safety-checker/model.safetensors ./invokeai/models/core/convert/stable-diffusion-safety-checker
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/convert/stable-diffusion-safety-checker/preprocessor_config.json ./invokeai/models/core/convert/stable-diffusion-safety-checker
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/misc/lama/lama.pt ./invokeai/models/core/misc/lama
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/upscaling/realesrgan/ESRGAN_SRx4_DF2KOST_official-ff704c30.pth ./invokeai/models/core/upscaling/realesrgan
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/upscaling/realesrgan/RealESRGAN_x2plus.pth ./invokeai/models/core/upscaling/realesrgan
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/upscaling/realesrgan/RealESRGAN_x4plus.pth ./invokeai/models/core/upscaling/realesrgan
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/models/core/upscaling/realesrgan/RealESRGAN_x4plus_anime_6B.pth ./invokeai/models/core/upscaling/realesrgan
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/INITIAL_MODELS.yaml ./invokeai/configs
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/models.yaml ./invokeai/configs
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/models.yaml.example ./invokeai/configs
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/stable-diffusion/sd_xl_base.yaml ./invokeai/configs/stable-diffusion
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/stable-diffusion/sd_xl_refiner.yaml ./invokeai/configs/stable-diffusion
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/stable-diffusion/v1-finetune.yaml ./invokeai/configs/stable-diffusion
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/stable-diffusion/v1-finetune_style.yaml ./invokeai/configs/stable-diffusion
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/stable-diffusion/v1-inference-v.yaml ./invokeai/configs/stable-diffusion
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/stable-diffusion/v1-inference.yaml ./invokeai/configs/stable-diffusion
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/stable-diffusion/v1-inpainting-inference.yaml ./invokeai/configs/stable-diffusion
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/stable-diffusion/v1-m1-finetune.yaml ./invokeai/configs/stable-diffusion
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/stable-diffusion/v2-inference-v.yaml ./invokeai/configs/stable-diffusion
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/stable-diffusion/v2-inference.yaml ./invokeai/configs/stable-diffusion
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/stable-diffusion/v2-inpainting-inference-v.yaml ./invokeai/configs/stable-diffusion
__term_sd_task_pre_model get_modelscope_model licyks/invokeai-core-model/master/configs/stable-diffusion/v2-inpainting-inference.yaml ./invokeai/configs/stable-diffusion