__term_sd_task_pre_ext_1 sd-webui-controlnet ON
__term_sd_task_pre_ext_2 sd-webui-animatediff ON
__term_sd_task_pre_ext_3 adetailer ON
__term_sd_task_pre_ext_4 sd-webui-IS-NET-pro OFF
__term_sd_task_pre_ext_5 sd-webui-segment-anything OFF
__term_sd_task_pre_ext_6 sd-webui-inpaint-anything OFF
__term_sd_task_pre_ext_7 sd-forge-layerdiffusion OFF
__term_sd_task_pre_ext_8 z-a1111-sd-webui-dtg OFF
__term_sd_task_pre_ext_9 sd-webui-stablesr OFF
__term_sd_task_pre_ext_10 kohya-config-webui OFF
__term_sd_task_pre_ext_11 sd-webui-additional-networks OFF
__term_sd_task_pre_ext_12 a1111-sd-webui-tagcomplete ON
__term_sd_task_pre_ext_13 multidiffusion-upscaler-for-automatic1111 ON
__term_sd_task_pre_ext_14 sd-dynamic-thresholding ON
__term_sd_task_pre_ext_15 sd-webui-cutoff ON
__term_sd_task_pre_ext_16 sd-webui-model-converter ON
__term_sd_task_pre_ext_17 sd-webui-supermerger ON
__term_sd_task_pre_ext_18 stable-diffusion-webui-localization-zh_Hans ON
__term_sd_task_pre_ext_19 sd-webui-wd14-tagger ON
__term_sd_task_pre_ext_20 sd-webui-regional-prompter ON
__term_sd_task_pre_ext_21 sd-webui-infinite-image-browsing ON
__term_sd_task_pre_ext_22 stable-diffusion-webui-anti-burn ON
__term_sd_task_pre_ext_23 loopback_scaler OFF
__term_sd_task_pre_ext_24 latentcoupleregionmapper OFF
__term_sd_task_pre_ext_25 ultimate-upscale-for-automatic1111 ON
__term_sd_task_pre_ext_26 deforum-for-automatic1111-webui OFF
__term_sd_task_pre_ext_27 stable-diffusion-webui-images-browser OFF
__term_sd_task_pre_ext_28 stable-diffusion-webui-huggingface OFF
__term_sd_task_pre_ext_29 sd-civitai-browser OFF
__term_sd_task_pre_ext_30 a1111-stable-diffusion-webui-vram-estimator OFF
__term_sd_task_pre_ext_31 openpose-editor OFF
__term_sd_task_pre_ext_32 sd-webui-depth-lib OFF
__term_sd_task_pre_ext_33 posex OFF
__term_sd_task_pre_ext_34 sd-webui-tunnels OFF
__term_sd_task_pre_ext_35 batchlinks-webui OFF
__term_sd_task_pre_ext_36 stable-diffusion-webui-catppuccin OFF
__term_sd_task_pre_ext_37 a1111-sd-webui-lycoris OFF
__term_sd_task_pre_ext_38 stable-diffusion-webui-rembg ON
__term_sd_task_pre_ext_39 stable-diffusion-webui-two-shot OFF
__term_sd_task_pre_ext_40 sd-webui-lora-block-weight ON
__term_sd_task_pre_ext_41 sd-face-editor OFF
__term_sd_task_pre_ext_42 sd-webui-prompt-all-in-one ON
__term_sd_task_pre_ext_43 sd-webui-comfyui OFF
__term_sd_task_pre_ext_44 sd-webui-photopea-embed OFF
__term_sd_task_pre_ext_45 sd-webui-openpose-editor ON
__term_sd_task_pre_ext_46 sd-webui-llul OFF
__term_sd_task_pre_ext_47 sd-webui-bilingual-localization OFF
__term_sd_task_pre_ext_48 sd-webui-mov2mov OFF
__term_sd_task_pre_ext_49 ebsynth_utility OFF
__term_sd_task_pre_ext_50 sd_dreambooth_extension OFF
__term_sd_task_pre_ext_51 sd-webui-memory-release OFF
__term_sd_task_pre_ext_52 stable-diffusion-webui-dataset-tag-editor OFF
__term_sd_task_pre_ext_53 sd-webui-deoldify OFF
__term_sd_task_pre_ext_54 stable-diffusion-webui-model-toolkit ON
__term_sd_task_pre_ext_55 sd-webui-oldsix-prompt-dynamic OFF
__term_sd_task_pre_ext_56 sd-webui-fastblend OFF
__term_sd_task_pre_ext_57 StyleSelectorXL OFF
__term_sd_task_pre_ext_58 sd-dynamic-prompts OFF
__term_sd_task_pre_ext_59 LightDiffusionFlow ON
__term_sd_task_pre_ext_60 sd-webui-workspace OFF
__term_sd_task_pre_ext_61 openOutpaint-webUI-extension OFF
__term_sd_task_pre_ext_62 sd-webui-samplers-scheduler OFF
__term_sd_task_pre_ext_63 sd-webui-boomer ON
__term_sd_task_pre_ext_64 model-keyword ON
__term_sd_task_pre_ext_65 Stable-Diffusion-WebUI-TensorRT OFF
__term_sd_task_pre_ext_66 sd-webui-lobe-theme OFF
__term_sd_task_pre_ext_67 stable-diffusion-webui-GPU-temperature-protection OFF
__term_sd_task_pre_ext_68 sd-webui-api-payload-display OFF
__term_sd_task_pre_ext_69 sd-webui-aspect-ratio-helper OFF
__term_sd_task_pre_ext_70 sd-webui-cd-tuner OFF
__term_sd_task_pre_ext_71 sd-webui-negpip OFF
__term_sd_task_pre_ext_72 sd-webui-agent-scheduler OFF
__term_sd_task_pre_ext_73 Stable-Diffusion-Webui-Civitai-Helper OFF
__term_sd_task_pre_ext_74 sd-webui-Lora-queue-helper OFF
__term_sd_task_pre_ext_75 PBRemTools OFF
__term_sd_task_pre_ext_76 sd-webui-rich-text OFF
__term_sd_task_pre_ext_77 image-deduplicate-cluster-webui OFF
__term_sd_task_pre_ext_78 stable-diffusion-webui-composable-lora OFF
__term_sd_task_pre_ext_79 sdweb-merge-block-weighted-gui OFF
__term_sd_task_pre_ext_80 sd-civitai-browser-plus OFF
__term_sd_task_pre_ext_81 sd-webui-weight-helper OFF
__term_sd_task_pre_ext_82 sd-danbooru-tags-upsampler OFF
__term_sd_task_pre_ext_83 Stylez OFF
__term_sd_task_pre_ext_84 sd-webui-next-style OFF
__term_sd_task_pre_ext_85 a1111-sd-webui-haku-img ON
__term_sd_task_pre_ext_86 Kohaku-NAI OFF
__term_sd_task_pre_ext_87 sd-webui-cli-interruption OFF
__term_sd_task_pre_ext_88 sdwebui-close-confirmation-dialogue OFF
__term_sd_task_pre_ext_89 sd-webui-hires-fix-tweaks OFF
__term_sd_task_pre_ext_90 sd-webui-custom-autolaunch OFF
__term_sd_task_pre_ext_91 sd-webui-triposr OFF
__term_sd_task_pre_ext_92 sd-webui-qic-console OFF
__term_sd_task_pre_ext_93 sd-webui-qrcode-toolkit OFF
__term_sd_task_pre_ext_94 sd-webui-controlnet-marigold OFF
__term_sd_task_pre_ext_95 Euler-Smea-Dyn-Sampler OFF
__term_sd_task_pre_ext_96 advanced_euler_sampler_extension OFF
__term_sd_task_pre_ext_97 sd-webui-vectorscope-cc OFF
__term_sd_task_pre_ext_98 sd-webui-smea OFF
__term_sd_task_pre_ext_99 sd-webui-neutral-prompt OFF
__term_sd_task_pre_ext_100 sd-webui-tabs-extension OFF
__term_sd_task_pre_ext_101 sd-forge-ic-light OFF
__term_sd_task_pre_ext_102 webui-fooocus-prompt-expansion OFF
__term_sd_task_pre_ext_103 sd-webui-model-patcher OFF
__term_sd_task_pre_ext_104 lora-prompt-tool OFF
__term_sd_task_pre_ext_105 sd-webui-easy-tag-insert OFF
__term_sd_task_pre_ext_106 sd-webui-i2i-ancestral-tree OFF
__term_sd_task_pre_ext_107 sd-forge-couple OFF
__term_sd_task_pre_ext_108 sd-webui-advanced-xyz OFF
__term_sd_task_pre_ext_109 sd-webui-mosaic-outpaint OFF
__term_sd_task_pre_ext_110 sd-webui-image-comparison OFF
__term_sd_task_pre_ext_111 sd-webui-diffusion-cg OFF
__term_sd_task_pre_ext_112 sd-webui-resharpen OFF
__term_sd_task_pre_ext_113 sd-webui-mobile-friendly OFF
__term_sd_task_pre_ext_114 sd-webui-prompt-format OFF
__term_sd_task_pre_ext_115 sd-webui-aaa OFF
__term_sd_task_pre_ext_116 sd-webui-clear-screen OFF
__term_sd_task_pre_ext_117 sd-webui-auto-res OFF
__term_sd_task_pre_ext_118 sd-webui-moar-generate OFF
__term_sd_task_pre_ext_119 metadata_utils OFF
__term_sd_task_pre_ext_120 sd-webui-xyz-addon OFF
__term_sd_task_pre_ext_121 sd-webui-flash-attention-zluda-win OFF
__term_sd_task_pre_ext_122 sd-webui-split-layout OFF
__term_sd_task_pre_ext_123 sd-webui-oldsix-prompt OFF
__term_sd_task_pre_ext_124 sd-webui-incantations OFF
__term_sd_task_pre_ext_125 sd-webui-ipex-enhancement OFF
