__term_sd_task_pre_ext_1 git_clone_repository ${github_mirror} https://github.com/WSH032/kohya-config-webui "$sd_webui_path"/extensions OFF # 一个用于生成kohya-ss训练脚本使用的toml配置文件的WebUI
__term_sd_task_pre_ext_2 git_clone_repository ${github_mirror} https://github.com/kohya-ss/sd-webui-additional-networks "$sd_webui_path"/extensions OFF # 将LoRA等模型添加到stablediffusion以生成图像的扩展
__term_sd_task_pre_ext_3 git_clone_repository ${github_mirror} https://github.com/DominikDoom/a1111-sd-webui-tagcomplete "$sd_webui_path"/extensions ON # 输入Tag时提供booru风格（如Danbooru）的TAG自动补全
__term_sd_task_pre_ext_4 git_clone_repository ${github_mirror} https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111 "$sd_webui_path"/extensions ON # 在有限的显存中进行大型图像绘制，提供图片区域控制
__term_sd_task_pre_ext_5 git_clone_repository ${github_mirror} https://github.com/mcmonkeyprojects/sd-dynamic-thresholding "$sd_webui_path"/extensions ON # 解决使用更高的CFGScale而出现颜色问题
__term_sd_task_pre_ext_6 git_clone_repository ${github_mirror} https://github.com/hnmr293/sd-webui-cutoff "$sd_webui_path"/extensions ON # 解决tag污染
__term_sd_task_pre_ext_7 git_clone_repository ${github_mirror} https://github.com/Akegarasu/sd-webui-model-converter "$sd_webui_path"/extensions ON # 模型转换扩展
__term_sd_task_pre_ext_8 git_clone_repository ${github_mirror} https://github.com/hako-mikan/sd-webui-supermerger "$sd_webui_path"/extensions ON # 模型融合扩展
__term_sd_task_pre_ext_9 git_clone_repository ${github_mirror} https://github.com/hanamizuki-ai/stable-diffusion-webui-localization-zh_Hans "$sd_webui_path"/extensions ON # WEBUI中文扩展
__term_sd_task_pre_ext_10 git_clone_repository ${github_mirror} https://github.com/picobyte/stable-diffusion-webui-wd14-tagger "$sd_webui_path"/extensions ON # 图片tag反推
__term_sd_task_pre_ext_11 git_clone_repository ${github_mirror} https://github.com/hako-mikan/sd-webui-regional-prompter "$sd_webui_path"/extensions ON # 图片区域分割
__term_sd_task_pre_ext_12 git_clone_repository ${github_mirror} https://github.com/zanllp/sd-webui-infinite-image-browsing "$sd_webui_path"/extensions ON # 强大的图像管理器
__term_sd_task_pre_ext_13 git_clone_repository ${github_mirror} https://github.com/klimaleksus/stable-diffusion-webui-anti-burn "$sd_webui_path"/extensions ON # 通过跳过最后几个步骤并将它们之前的一些图像平均在一起来平滑生成的图像，加快点击停止生成图像后WEBUI的响应速度
__term_sd_task_pre_ext_14 git_clone_repository ${github_mirror} https://github.com/Elldreth/loopback_scaler "$sd_webui_path"/extensions OFF # 使用迭代过程增强图像分辨率和质量
__term_sd_task_pre_ext_15 git_clone_repository ${github_mirror} https://github.com/CodeZombie/latentcoupleregionmapper "$sd_webui_path"/extensions OFF # 控制绘制和定义区域
__term_sd_task_pre_ext_16 git_clone_repository ${github_mirror} https://github.com/Coyote-A/ultimate-upscale-for-automatic1111 "$sd_webui_path"/extensions ON # 图片放大工具
__term_sd_task_pre_ext_17 git_clone_repository ${github_mirror} https://github.com/deforum-art/deforum-for-automatic1111-webui "$sd_webui_path"/extensions OFF # 视频生成插件
__term_sd_task_pre_ext_18 git_clone_repository ${github_mirror} https://github.com/AlUlkesh/stable-diffusion-webui-images-browser "$sd_webui_path"/extensions OFF # 图像管理器
__term_sd_task_pre_ext_19 git_clone_repository ${github_mirror} https://github.com/camenduru/stable-diffusion-webui-huggingface "$sd_webui_path"/extensions OFF # huggingface模型下载扩展
__term_sd_task_pre_ext_20 git_clone_repository ${github_mirror} https://github.com/camenduru/sd-civitai-browser "$sd_webui_path"/extensions OFF # civitai模型下载扩展
__term_sd_task_pre_ext_21 git_clone_repository ${github_mirror} https://github.com/space-nuko/a1111-stable-diffusion-webui-vram-estimator "$sd_webui_path"/extensions OFF # 显存占用评估
__term_sd_task_pre_ext_22 git_clone_repository ${github_mirror} https://github.com/fkunn1326/openpose-editor "$sd_webui_path"/extensions OFF # openpose姿势编辑
__term_sd_task_pre_ext_23 git_clone_repository ${github_mirror} https://github.com/jexom/sd-webui-depth-lib "$sd_webui_path"/extensions OFF # 深度图库，用于Automatic1111/stable-diffusion-webui的controlnet扩展
__term_sd_task_pre_ext_24 git_clone_repository ${github_mirror} https://github.com/hnmr293/posex "$sd_webui_path"/extensions OFF # openpose姿势编辑
__term_sd_task_pre_ext_25 git_clone_repository ${github_mirror} https://github.com/camenduru/sd-webui-tunnels "$sd_webui_path"/extensions OFF # WEBUI端口映射扩展
__term_sd_task_pre_ext_26 git_clone_repository ${github_mirror} https://github.com/etherealxx/batchlinks-webui "$sd_webui_path"/extensions OFF # 批处理链接下载器
__term_sd_task_pre_ext_27 git_clone_repository ${github_mirror} https://github.com/camenduru/stable-diffusion-webui-catppuccin "$sd_webui_path"/extensions OFF # WEBUI主题
__term_sd_task_pre_ext_28 git_clone_repository ${github_mirror} https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris "$sd_webui_path"/extensions OFF # 添加lycoris模型支持
__term_sd_task_pre_ext_29 git_clone_repository ${github_mirror} https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg "$sd_webui_path"/extensions ON # 人物背景去除
__term_sd_task_pre_ext_30 git_clone_repository ${github_mirror} https://github.com/ashen-sensored/stable-diffusion-webui-two-shot "$sd_webui_path"/extensions OFF # 图片区域分割和控制
__term_sd_task_pre_ext_31 git_clone_repository ${github_mirror} https://github.com/hako-mikan/sd-webui-lora-block-weight "$sd_webui_path"/extensions ON # lora分层扩展
__term_sd_task_pre_ext_32 git_clone_repository ${github_mirror} https://github.com/ototadana/sd-face-editor "$sd_webui_path"/extensions OFF # 面部编辑器
__term_sd_task_pre_ext_33 git_clone_repository ${github_mirror} https://github.com/continue-revolution/sd-webui-segment-anything "$sd_webui_path"/extensions OFF # 图片语义分割
__term_sd_task_pre_ext_34 git_clone_repository ${github_mirror} https://github.com/Mikubill/sd-webui-controlnet "$sd_webui_path"/extensions ON # 图片生成控制
__term_sd_task_pre_ext_35 git_clone_repository ${github_mirror} https://github.com/Physton/sd-webui-prompt-all-in-one "$sd_webui_path"/extensions ON # tag翻译和管理插件
__term_sd_task_pre_ext_36 git_clone_repository ${github_mirror} https://github.com/ModelSurge/sd-webui-comfyui "$sd_webui_path"/extensions OFF # 在WEBUI添加ComfyUI界面
__term_sd_task_pre_ext_37 git_clone_repository ${github_mirror} https://github.com/continue-revolution/sd-webui-animatediff "$sd_webui_path"/extensions OFF # 视频生成扩展
__term_sd_task_pre_ext_38 git_clone_repository ${github_mirror} https://github.com/yankooliveira/sd-webui-photopea-embed "$sd_webui_path"/extensions OFF # 在WEBUI界面添加ps功能
__term_sd_task_pre_ext_39 git_clone_repository ${github_mirror} https://github.com/huchenlei/sd-webui-openpose-editor "$sd_webui_path"/extensions ON # ControlNet的pose编辑器
__term_sd_task_pre_ext_40 git_clone_repository ${github_mirror} https://github.com/hnmr293/sd-webui-llul "$sd_webui_path"/extensions OFF # 给图片的选定区域增加细节
__term_sd_task_pre_ext_41 git_clone_repository ${github_mirror} https://github.com/journey-ad/sd-webui-bilingual-localization "$sd_webui_path"/extensions OFF # WEBUI双语对照翻译插件
__term_sd_task_pre_ext_42 git_clone_repository ${github_mirror} https://github.com/Bing-su/adetailer "$sd_webui_path"/extensions ON # 图片细节修复扩展
__term_sd_task_pre_ext_43 git_clone_repository ${github_mirror} https://github.com/Scholar01/sd-webui-mov2mov "$sd_webui_path"/extensions OFF # 视频逐帧处理插件
__term_sd_task_pre_ext_44 git_clone_repository ${github_mirror} https://github.com/ClockZinc/sd-webui-IS-NET-pro "$sd_webui_path"/extensions OFF # 人物抠图
__term_sd_task_pre_ext_45 git_clone_repository ${github_mirror} https://github.com/s9roll7/ebsynth_utility "$sd_webui_path"/extensions OFF # 视频处理扩展
__term_sd_task_pre_ext_46 git_clone_repository ${github_mirror} https://github.com/d8ahazard/sd_dreambooth_extension "$sd_webui_path"/extensions OFF # dreambooth模型训练
__term_sd_task_pre_ext_47 git_clone_repository ${github_mirror} https://github.com/Haoming02/sd-webui-memory-release "$sd_webui_path"/extensions OFF # 显存释放扩展
__term_sd_task_pre_ext_48 git_clone_repository ${github_mirror} https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor "$sd_webui_path"/extensions OFF # 训练集打标和处理扩展
__term_sd_task_pre_ext_49 git_clone_repository ${github_mirror} https://github.com/pkuliyi2015/sd-webui-stablesr "$sd_webui_path"/extensions OFF # 图片放大
__term_sd_task_pre_ext_50 git_clone_repository ${github_mirror} https://github.com/SpenserCai/sd-webui-deoldify "$sd_webui_path"/extensions OFF # 黑白图片上色
__term_sd_task_pre_ext_51 git_clone_repository ${github_mirror} https://github.com/arenasys/stable-diffusion-webui-model-toolkit "$sd_webui_path"/extensions ON # 大模型数据查看
__term_sd_task_pre_ext_52 git_clone_repository ${github_mirror} https://github.com/Bobo-1125/sd-webui-oldsix-prompt-dynamic "$sd_webui_path"/extensions OFF # 动态提示词
__term_sd_task_pre_ext_53 git_clone_repository ${github_mirror} https://github.com/Artiprocher/sd-webui-fastblend "$sd_webui_path"/extensions OFF # ai视频平滑
__term_sd_task_pre_ext_54 git_clone_repository ${github_mirror} https://github.com/ahgsql/StyleSelectorXL "$sd_webui_path"/extensions OFF # SDXL模型画风选择
__term_sd_task_pre_ext_55 git_clone_repository ${github_mirror} https://github.com/adieyal/sd-dynamic-prompts "$sd_webui_path"/extensions OFF # 动态提示词
__term_sd_task_pre_ext_56 git_clone_repository ${github_mirror} https://github.com/Tencent/LightDiffusionFlow "$sd_webui_path"/extensions ON # 保存工作流
__term_sd_task_pre_ext_57 git_clone_repository ${github_mirror} https://github.com/Scholar01/sd-webui-workspace "$sd_webui_path"/extensions OFF # 保存webui生图的参数
__term_sd_task_pre_ext_58 git_clone_repository --submod ${github_mirror} https://github.com/zero01101/openOutpaint-webUI-extension "$sd_webui_path"/extensions OFF # 提供类似InvokeAI的统一画布的功能
__term_sd_task_pre_ext_59 git_clone_repository ${github_mirror} https://github.com/Carzit/sd-webui-samplers-scheduler "$sd_webui_path"/extensions OFF # 采样器调度器，可以在不同的生成步骤中应用不同的采样器
__term_sd_task_pre_ext_60 git_clone_repository ${github_mirror} https://github.com/Haoming02/sd-webui-boomer "$sd_webui_path"/extensions ON # 恢复新版webui已经移除的按钮
__term_sd_task_pre_ext_61 git_clone_repository ${github_mirror} https://github.com/mix1009/model-keyword "$sd_webui_path"/extensions ON # 用于补全模型对应的提示词，比如使用lora模型的提示词
__term_sd_task_pre_ext_62 git_clone_repository ${github_mirror} https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT "$sd_webui_path"/extensions OFF # nvidia官方加速工具，加速图片生成
__term_sd_task_pre_ext_63 git_clone_repository ${github_mirror} https://github.com/lobehub/sd-webui-lobe-theme "$sd_webui_path"/extensions OFF # webui主题
__term_sd_task_pre_ext_64 git_clone_repository ${github_mirror} https://github.com/w-e-w/stable-diffusion-webui-GPU-temperature-protection "$sd_webui_path"/extensions OFF # 显卡过热保护
__term_sd_task_pre_ext_65 git_clone_repository ${github_mirror} https://github.com/huchenlei/sd-webui-api-payload-display "$sd_webui_path"/extensions OFF # 生图完成后展示api参数
__term_sd_task_pre_ext_66 git_clone_repository ${github_mirror} https://github.com/Uminosachi/sd-webui-inpaint-anything "$sd_webui_path"/extensions OFF # 使用seg生成的蒙版进行图像重绘
__term_sd_task_pre_ext_67 git_clone_repository ${github_mirror} https://github.com/thomasasfk/sd-webui-aspect-ratio-helper "$sd_webui_path"/extensions OFF # 图片尺寸比例固定
__term_sd_task_pre_ext_68 git_clone_repository ${github_mirror} https://github.com/hako-mikan/sd-webui-cd-tuner "$sd_webui_path"/extensions OFF # 修改输出图像中的细节和色调的数量
__term_sd_task_pre_ext_69 git_clone_repository ${github_mirror} https://github.com/hako-mikan/sd-webui-negpip "$sd_webui_path"/extensions OFF # 解决tag的强污染，效果比cutoff更强
__term_sd_task_pre_ext_70 git_clone_repository ${github_mirror} https://github.com/ArtVentureX/sd-webui-agent-scheduler "$sd_webui_path"/extensions OFF # 生图队列管理，可制作一个参数不同的队列来进行批量生图
__term_sd_task_pre_ext_71 git_clone_repository ${github_mirror} https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper "$sd_webui_path"/extensions OFF # civitai模型管理 
__term_sd_task_pre_ext_72 git_clone_repository ${github_mirror} https://github.com/Yinzo/sd-webui-Lora-queue-helper "$sd_webui_path"/extensions OFF # Lora队列助手，用于比较具有相同提示和设置的相同角色的Lora/从同一来源生成不同的角色/或者只需切换和选择Lora，而无需更改选项卡
__term_sd_task_pre_ext_73 git_clone_repository ${github_mirror} https://github.com/mattyamonaca/PBRemTools "$sd_webui_path"/extensions OFF # 图片背景去除，并且可以生成蒙版图像
__term_sd_task_pre_ext_74 git_clone_repository ${github_mirror} https://github.com/songweige/sd-webui-rich-text "$sd_webui_path"/extensions OFF # 使用富文本进行图像生成，并且能够通过提示词来精准的控制图像
__term_sd_task_pre_ext_75 git_clone_repository ${github_mirror} https://github.com/WSH032/image-deduplicate-cluster-webui "$sd_webui_path"/extensions OFF # 图像查重和图片聚类
__term_sd_task_pre_ext_76 git_clone_repository ${github_mirror} https://github.com/opparco/stable-diffusion-webui-composable-lora "$sd_webui_path"/extensions OFF # 将LoRA在提示中的插入位置与“AND”语法相关联
__term_sd_task_pre_ext_77 git_clone_repository ${github_mirror} https://github.com/bbc-mc/sdweb-merge-block-weighted-gui "$sd_webui_path"/extensions OFF # 模型U-NET权重调整与合并
__term_sd_task_pre_ext_78 git_clone_repository ${github_mirror} https://github.com/BlafKing/sd-civitai-browser-plus "$sd_webui_path"/extensions OFF # civitai助手升级版，支持更多功能
