__term_sd_task_pre_ext_1 git_clone_repository https://github.com/Mikubill/sd-webui-controlnet "${SD_WEBUI_PATH}"/extensions ON # 图片生成控制
__term_sd_task_pre_ext_2 git_clone_repository https://github.com/continue-revolution/sd-webui-animatediff "${SD_WEBUI_PATH}"/extensions OFF # 视频生成扩展
__term_sd_task_pre_ext_3 git_clone_repository https://github.com/Bing-su/adetailer "${SD_WEBUI_PATH}"/extensions ON # 图片细节修复扩展
__term_sd_task_pre_ext_4 git_clone_repository https://github.com/ClockZinc/sd-webui-IS-NET-pro "${SD_WEBUI_PATH}"/extensions OFF # 人物抠图
__term_sd_task_pre_ext_5 git_clone_repository https://github.com/continue-revolution/sd-webui-segment-anything "${SD_WEBUI_PATH}"/extensions ON # 图片语义分割
__term_sd_task_pre_ext_6 git_clone_repository https://github.com/Uminosachi/sd-webui-inpaint-anything "${SD_WEBUI_PATH}"/extensions OFF # 使用seg生成的蒙版进行图像重绘
__term_sd_task_pre_ext_7 git_clone_repository https://github.com/lllyasviel/sd-forge-layerdiffuse "${SD_WEBUI_PATH}"/extensions OFF # LayerDiffusion插件，仅支持sd-webui-forge
__term_sd_task_pre_ext_8 git_clone_repository https://github.com/KohakuBlueleaf/z-a1111-sd-webui-dtg "${SD_WEBUI_PATH}"/extensions OFF # 使用Danboou风格对tag进行润色，使出图效果更好，内容更丰富
__term_sd_task_pre_ext_9 git_clone_repository https://github.com/pkuliyi2015/sd-webui-stablesr "${SD_WEBUI_PATH}"/extensions OFF # 图片放大
__term_sd_task_pre_ext_10 git_clone_repository https://github.com/KohakuBlueleaf/z-tipo-extension "${SD_WEBUI_PATH}"/extensions OFF # 使用danbooru-tag和自然语言对提示词进行润色，增强模型的出图效果
__term_sd_task_pre_ext_11 git_clone_repository https://github.com/WSH032/kohya-config-webui "${SD_WEBUI_PATH}"/extensions OFF # 一个用于生成kohya-ss训练脚本使用的toml配置文件的WebUI
__term_sd_task_pre_ext_12 git_clone_repository https://github.com/kohya-ss/sd-webui-additional-networks "${SD_WEBUI_PATH}"/extensions OFF # 将LoRA等模型添加到stablediffusion以生成图像的扩展
__term_sd_task_pre_ext_13 git_clone_repository https://github.com/DominikDoom/a1111-sd-webui-tagcomplete "${SD_WEBUI_PATH}"/extensions ON # 输入Tag时提供booru风格（如Danbooru）的TAG自动补全
__term_sd_task_pre_ext_14 git_clone_repository https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111 "${SD_WEBUI_PATH}"/extensions ON # 在有限的显存中进行大型图像绘制，提供图片区域控制
__term_sd_task_pre_ext_15 git_clone_repository https://github.com/mcmonkeyprojects/sd-dynamic-thresholding "${SD_WEBUI_PATH}"/extensions ON # 解决使用更高的CFGScale而出现颜色问题
__term_sd_task_pre_ext_16 git_clone_repository https://github.com/hnmr293/sd-webui-cutoff "${SD_WEBUI_PATH}"/extensions OFF # 解决tag污染
__term_sd_task_pre_ext_17 git_clone_repository https://github.com/Akegarasu/sd-webui-model-converter "${SD_WEBUI_PATH}"/extensions ON # 模型转换扩展
__term_sd_task_pre_ext_18 git_clone_repository https://github.com/hako-mikan/sd-webui-supermerger "${SD_WEBUI_PATH}"/extensions ON # 模型融合扩展
__term_sd_task_pre_ext_19 git_clone_repository https://github.com/hanamizuki-ai/stable-diffusion-webui-localization-zh_Hans "${SD_WEBUI_PATH}"/extensions ON # WEBUI中文扩展
__term_sd_task_pre_ext_20 git_clone_repository https://github.com/Akegarasu/sd-webui-wd14-tagger "${SD_WEBUI_PATH}"/extensions ON # 图片tag反推
__term_sd_task_pre_ext_21 git_clone_repository https://github.com/hako-mikan/sd-webui-regional-prompter "${SD_WEBUI_PATH}"/extensions ON # 图片区域分割
__term_sd_task_pre_ext_22 git_clone_repository https://github.com/zanllp/sd-webui-infinite-image-browsing "${SD_WEBUI_PATH}"/extensions ON # 强大的图像管理器
__term_sd_task_pre_ext_23 git_clone_repository https://github.com/klimaleksus/stable-diffusion-webui-anti-burn "${SD_WEBUI_PATH}"/extensions OFF # 通过跳过最后几个步骤并将它们之前的一些图像平均在一起来平滑生成的图像，加快点击停止生成图像后WEBUI的响应速度
__term_sd_task_pre_ext_24 git_clone_repository https://github.com/Elldreth/loopback_scaler "${SD_WEBUI_PATH}"/extensions OFF # 使用迭代过程增强图像分辨率和质量
__term_sd_task_pre_ext_25 git_clone_repository https://github.com/CodeZombie/latentcoupleregionmapper "${SD_WEBUI_PATH}"/extensions OFF # 控制绘制和定义区域
__term_sd_task_pre_ext_26 git_clone_repository https://github.com/Coyote-A/ultimate-upscale-for-automatic1111 "${SD_WEBUI_PATH}"/extensions ON # 图片放大工具
__term_sd_task_pre_ext_27 git_clone_repository https://github.com/deforum-art/deforum-for-automatic1111-webui "${SD_WEBUI_PATH}"/extensions OFF # 视频生成插件
__term_sd_task_pre_ext_28 git_clone_repository https://github.com/AlUlkesh/stable-diffusion-webui-images-browser "${SD_WEBUI_PATH}"/extensions OFF # 图像管理器
__term_sd_task_pre_ext_29 git_clone_repository https://github.com/camenduru/stable-diffusion-webui-huggingface "${SD_WEBUI_PATH}"/extensions OFF # huggingface模型下载扩展
__term_sd_task_pre_ext_30 git_clone_repository https://github.com/camenduru/sd-civitai-browser "${SD_WEBUI_PATH}"/extensions OFF # civitai模型下载扩展
__term_sd_task_pre_ext_31 git_clone_repository https://github.com/space-nuko/a1111-stable-diffusion-webui-vram-estimator "${SD_WEBUI_PATH}"/extensions OFF # 显存占用评估
__term_sd_task_pre_ext_32 git_clone_repository https://github.com/fkunn1326/openpose-editor "${SD_WEBUI_PATH}"/extensions OFF # openpose姿势编辑
__term_sd_task_pre_ext_33 git_clone_repository https://github.com/jexom/sd-webui-depth-lib "${SD_WEBUI_PATH}"/extensions OFF # 深度图库，用于Automatic1111/stable-diffusion-webui的controlnet扩展
__term_sd_task_pre_ext_34 git_clone_repository https://github.com/hnmr293/posex "${SD_WEBUI_PATH}"/extensions OFF # openpose姿势编辑
__term_sd_task_pre_ext_35 git_clone_repository https://github.com/camenduru/sd-webui-tunnels "${SD_WEBUI_PATH}"/extensions OFF # WEBUI端口映射扩展
__term_sd_task_pre_ext_36 git_clone_repository https://github.com/etherealxx/batchlinks-webui "${SD_WEBUI_PATH}"/extensions OFF # 批处理链接下载器
__term_sd_task_pre_ext_37 git_clone_repository https://github.com/camenduru/stable-diffusion-webui-catppuccin "${SD_WEBUI_PATH}"/extensions OFF # WEBUI主题
__term_sd_task_pre_ext_38 git_clone_repository https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris "${SD_WEBUI_PATH}"/extensions OFF # 添加lycoris模型支持
__term_sd_task_pre_ext_39 git_clone_repository https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg "${SD_WEBUI_PATH}"/extensions OFF # 人物背景去除
__term_sd_task_pre_ext_40 git_clone_repository https://github.com/ashen-sensored/stable-diffusion-webui-two-shot "${SD_WEBUI_PATH}"/extensions OFF # 图片区域分割和控制
__term_sd_task_pre_ext_41 git_clone_repository https://github.com/hako-mikan/sd-webui-lora-block-weight "${SD_WEBUI_PATH}"/extensions ON # lora分层扩展
__term_sd_task_pre_ext_42 git_clone_repository https://github.com/ototadana/sd-face-editor "${SD_WEBUI_PATH}"/extensions OFF # 面部编辑器
__term_sd_task_pre_ext_43 git_clone_repository https://github.com/Physton/sd-webui-prompt-all-in-one "${SD_WEBUI_PATH}"/extensions ON # tag翻译和管理插件
__term_sd_task_pre_ext_44 git_clone_repository https://github.com/ModelSurge/sd-webui-comfyui "${SD_WEBUI_PATH}"/extensions OFF # 在WEBUI添加ComfyUI界面
__term_sd_task_pre_ext_45 git_clone_repository https://github.com/yankooliveira/sd-webui-photopea-embed "${SD_WEBUI_PATH}"/extensions OFF # 在WEBUI界面添加ps功能
__term_sd_task_pre_ext_46 git_clone_repository https://github.com/huchenlei/sd-webui-openpose-editor "${SD_WEBUI_PATH}"/extensions ON # ControlNet的pose编辑器
__term_sd_task_pre_ext_47 git_clone_repository https://github.com/hnmr293/sd-webui-llul "${SD_WEBUI_PATH}"/extensions OFF # 给图片的选定区域增加细节
__term_sd_task_pre_ext_48 git_clone_repository https://github.com/journey-ad/sd-webui-bilingual-localization "${SD_WEBUI_PATH}"/extensions OFF # WEBUI双语对照翻译插件
__term_sd_task_pre_ext_49 git_clone_repository https://github.com/Scholar01/sd-webui-mov2mov "${SD_WEBUI_PATH}"/extensions OFF # 视频逐帧处理插件
__term_sd_task_pre_ext_50 git_clone_repository https://github.com/s9roll7/ebsynth_utility "${SD_WEBUI_PATH}"/extensions OFF # 视频处理扩展
__term_sd_task_pre_ext_51 git_clone_repository https://github.com/d8ahazard/sd_dreambooth_extension "${SD_WEBUI_PATH}"/extensions OFF # dreambooth模型训练
__term_sd_task_pre_ext_52 git_clone_repository https://github.com/Haoming02/sd-webui-memory-release "${SD_WEBUI_PATH}"/extensions OFF # 显存释放扩展
__term_sd_task_pre_ext_53 git_clone_repository https://github.com/toshiaki1729/stable-diffusion-webui-dataset-tag-editor "${SD_WEBUI_PATH}"/extensions OFF # 训练集打标和处理扩展
__term_sd_task_pre_ext_54 git_clone_repository https://github.com/SpenserCai/sd-webui-deoldify "${SD_WEBUI_PATH}"/extensions OFF # 黑白图片上色
__term_sd_task_pre_ext_55 git_clone_repository https://github.com/arenasys/stable-diffusion-webui-model-toolkit "${SD_WEBUI_PATH}"/extensions ON # 大模型数据查看
__term_sd_task_pre_ext_56 git_clone_repository https://github.com/Bobo-1125/sd-webui-oldsix-prompt-dynamic "${SD_WEBUI_PATH}"/extensions OFF # 动态提示词
__term_sd_task_pre_ext_57 git_clone_repository https://github.com/Artiprocher/sd-webui-fastblend "${SD_WEBUI_PATH}"/extensions OFF # ai视频平滑
__term_sd_task_pre_ext_58 git_clone_repository https://github.com/ahgsql/StyleSelectorXL "${SD_WEBUI_PATH}"/extensions OFF # SDXL模型画风选择
__term_sd_task_pre_ext_59 git_clone_repository https://github.com/adieyal/sd-dynamic-prompts "${SD_WEBUI_PATH}"/extensions OFF # 动态提示词
__term_sd_task_pre_ext_60 git_clone_repository https://github.com/Tencent/LightDiffusionFlow "${SD_WEBUI_PATH}"/extensions OFF # 保存工作流
__term_sd_task_pre_ext_61 git_clone_repository https://github.com/Scholar01/sd-webui-workspace "${SD_WEBUI_PATH}"/extensions OFF # 保存webui生图的参数
__term_sd_task_pre_ext_62 git_clone_repository https://github.com/zero01101/openOutpaint-webUI-extension "${SD_WEBUI_PATH}"/extensions OFF # 提供类似InvokeAI的统一画布的功能
__term_sd_task_pre_ext_63 git_clone_repository https://github.com/Carzit/sd-webui-samplers-scheduler "${SD_WEBUI_PATH}"/extensions OFF # 采样器调度器，可以在不同的生成步骤中应用不同的采样器
__term_sd_task_pre_ext_64 git_clone_repository https://github.com/Haoming02/sd-webui-boomer "${SD_WEBUI_PATH}"/extensions OFF # 恢复新版webui已经移除的按钮
__term_sd_task_pre_ext_65 git_clone_repository https://github.com/mix1009/model-keyword "${SD_WEBUI_PATH}"/extensions OFF # 用于补全模型对应的提示词，比如使用lora模型的提示词
__term_sd_task_pre_ext_66 git_clone_repository https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT "${SD_WEBUI_PATH}"/extensions OFF # nvidia官方加速工具，加速图片生成
__term_sd_task_pre_ext_67 git_clone_repository https://github.com/lobehub/sd-webui-lobe-theme "${SD_WEBUI_PATH}"/extensions OFF # webui主题
__term_sd_task_pre_ext_68 git_clone_repository https://github.com/w-e-w/stable-diffusion-webui-GPU-temperature-protection "${SD_WEBUI_PATH}"/extensions OFF # 显卡过热保护
__term_sd_task_pre_ext_69 git_clone_repository https://github.com/huchenlei/sd-webui-api-payload-display "${SD_WEBUI_PATH}"/extensions OFF # 生图完成后展示api参数
__term_sd_task_pre_ext_70 git_clone_repository https://github.com/thomasasfk/sd-webui-aspect-ratio-helper "${SD_WEBUI_PATH}"/extensions OFF # 图片尺寸比例固定
__term_sd_task_pre_ext_71 git_clone_repository https://github.com/hako-mikan/sd-webui-cd-tuner "${SD_WEBUI_PATH}"/extensions OFF # 修改输出图像中的细节和色调的数量
__term_sd_task_pre_ext_72 git_clone_repository https://github.com/hako-mikan/sd-webui-negpip "${SD_WEBUI_PATH}"/extensions OFF # 解决tag的强污染，效果比cutoff更强
__term_sd_task_pre_ext_73 git_clone_repository https://github.com/ArtVentureX/sd-webui-agent-scheduler "${SD_WEBUI_PATH}"/extensions OFF # 生图队列管理，可制作一个参数不同的队列来进行批量生图
__term_sd_task_pre_ext_74 git_clone_repository https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper "${SD_WEBUI_PATH}"/extensions OFF # civitai模型管理
__term_sd_task_pre_ext_75 git_clone_repository https://github.com/Yinzo/sd-webui-Lora-queue-helper "${SD_WEBUI_PATH}"/extensions OFF # Lora队列助手，用于比较具有相同提示和设置的相同角色的Lora/从同一来源生成不同的角色/或者只需切换和选择Lora，而无需更改选项卡
__term_sd_task_pre_ext_76 git_clone_repository https://github.com/mattyamonaca/PBRemTools "${SD_WEBUI_PATH}"/extensions OFF # 图片背景去除，并且可以生成蒙版图像
__term_sd_task_pre_ext_77 git_clone_repository https://github.com/songweige/sd-webui-rich-text "${SD_WEBUI_PATH}"/extensions OFF # 使用富文本进行图像生成，并且能够通过提示词来精准的控制图像
__term_sd_task_pre_ext_78 git_clone_repository https://github.com/WSH032/image-deduplicate-cluster-webui "${SD_WEBUI_PATH}"/extensions OFF # 图像查重和图片聚类
__term_sd_task_pre_ext_79 git_clone_repository https://github.com/opparco/stable-diffusion-webui-composable-lora "${SD_WEBUI_PATH}"/extensions OFF # 将LoRA在提示中的插入位置与“AND”语法相关联
__term_sd_task_pre_ext_80 git_clone_repository https://github.com/bbc-mc/sdweb-merge-block-weighted-gui "${SD_WEBUI_PATH}"/extensions OFF # 模型U-NET权重调整与合并
__term_sd_task_pre_ext_81 git_clone_repository https://github.com/BlafKing/sd-civitai-browser-plus "${SD_WEBUI_PATH}"/extensions OFF # civitai助手升级版，支持更多功能
__term_sd_task_pre_ext_82 git_clone_repository https://github.com/nihedon/sd-webui-weight-helper "${SD_WEBUI_PATH}"/extensions OFF # 快捷调整lora分层参数
__term_sd_task_pre_ext_83 git_clone_repository https://github.com/p1atdev/sd-danbooru-tags-upsampler "${SD_WEBUI_PATH}"/extensions OFF # 将用于生图的提示词进行润色，使其出图的画面多样化，更自然
__term_sd_task_pre_ext_84 git_clone_repository https://github.com/javsezlol1/Stylez "${SD_WEBUI_PATH}"/extensions OFF # 提示词预设风格选择工具
__term_sd_task_pre_ext_85 git_clone_repository https://github.com/Firetheft/sd-webui-next-style "${SD_WEBUI_PATH}"/extensions OFF # 提示词预设风格选择工具，增加了汉化并添加Fooocus全部风格模板
__term_sd_task_pre_ext_86 git_clone_repository https://github.com/KohakuBlueleaf/a1111-sd-webui-haku-img "${SD_WEBUI_PATH}"/extensions ON # 图像处理工具
__term_sd_task_pre_ext_87 git_clone_repository https://github.com/KohakuBlueleaf/Kohaku-NAI "${SD_WEBUI_PATH}"/extensions OFF # novelai_api调用工具
__term_sd_task_pre_ext_88 git_clone_repository https://github.com/light-and-ray/sd-webui-cli-interruption "${SD_WEBUI_PATH}"/extensions OFF # 当在终端中按下Ctrl+C时，若此时正在生图，则将Ctrl+C的终止程序信号更改为终止生图的信号
__term_sd_task_pre_ext_89 git_clone_repository https://github.com/w-e-w/sdwebui-close-confirmation-dialogue "${SD_WEBUI_PATH}"/extensions OFF # 添加关闭SD-WebUI界面的确认提醒
__term_sd_task_pre_ext_90 git_clone_repository https://github.com/w-e-w/sd-webui-hires-fix-tweaks "${SD_WEBUI_PATH}"/extensions OFF # 添加更多高清修复的选项
__term_sd_task_pre_ext_91 git_clone_repository https://github.com/w-e-w/sd-webui-custom-autolaunch "${SD_WEBUI_PATH}"/extensions OFF # 自定义启动SD-WebUI界面的浏览器
__term_sd_task_pre_ext_92 git_clone_repository https://github.com/AlbedoFire/sd-webui-triposr "${SD_WEBUI_PATH}"/extensions OFF # 添加Triposr支持
__term_sd_task_pre_ext_93 git_clone_repository https://github.com/SenshiSentou/sd-webui-qic-console "${SD_WEBUI_PATH}"/extensions OFF # 在SD-WebUI界面添加Python终端，用于简单的调试
__term_sd_task_pre_ext_94 git_clone_repository https://github.com/antfu/sd-webui-qrcode-toolkit "${SD_WEBUI_PATH}"/extensions OFF # 二维码处理工具
__term_sd_task_pre_ext_95 git_clone_repository https://github.com/huchenlei/sd-webui-controlnet-marigold "${SD_WEBUI_PATH}"/extensions OFF # 为controlnet插件添加marigold深度预处理器
__term_sd_task_pre_ext_96 git_clone_repository https://github.com/Koishi-Star/Euler-Smea-Dyn-Sampler "${SD_WEBUI_PATH}"/extensions OFF # 添加Eular-SMEA-Dy采样算法
__term_sd_task_pre_ext_97 git_clone_repository https://github.com/licyk/advanced_euler_sampler_extension "${SD_WEBUI_PATH}"/extensions OFF # 添加Eular-SMEA-Dy，Eular-SMEA采样算法
__term_sd_task_pre_ext_98 git_clone_repository https://github.com/Haoming02/sd-webui-vectorscope-cc "${SD_WEBUI_PATH}"/extensions OFF # 噪声偏移插件，可用于调整亮度，对比度和颜色
__term_sd_task_pre_ext_99 git_clone_repository https://github.com/AG-w/sd-webui-smea "${SD_WEBUI_PATH}"/extensions OFF # 添加Eular-Smea采样器和TCD采样器
__term_sd_task_pre_ext_100 git_clone_repository https://github.com/ljleb/sd-webui-neutral-prompt "${SD_WEBUI_PATH}"/extensions OFF # 添加AND_PERP、AND_SALT、AND_TOPK提示词用法
__term_sd_task_pre_ext_101 git_clone_repository https://github.com/Haoming02/sd-webui-tabs-extension "${SD_WEBUI_PATH}"/extensions OFF # 优化WebUI选项卡的排版
__term_sd_task_pre_ext_102 git_clone_repository https://github.com/Haoming02/sd-forge-ic-light "${SD_WEBUI_PATH}"/extensions OFF # 添加ic-light支持
__term_sd_task_pre_ext_103 git_clone_repository https://github.com/power88/webui-fooocus-prompt-expansion "${SD_WEBUI_PATH}"/extensions OFF # 添加fooocus的提示词扩写支持
__term_sd_task_pre_ext_104 git_clone_repository https://github.com/huchenlei/sd-webui-model-patcher "${SD_WEBUI_PATH}"/extensions OFF # ComfyUI样式的LDM修补插件
__term_sd_task_pre_ext_105 git_clone_repository https://github.com/a2569875/lora-prompt-tool "${SD_WEBUI_PATH}"/extensions OFF # 快捷管理lora模型的触发词
__term_sd_task_pre_ext_106 git_clone_repository https://github.com/Haoming02/sd-webui-easy-tag-insert "${SD_WEBUI_PATH}"/extensions OFF # 提示词快捷插入
__term_sd_task_pre_ext_107 git_clone_repository https://github.com/Haoming02/sd-webui-i2i-ancestral-tree "${SD_WEBUI_PATH}"/extensions OFF # 图生图的可视化图片关系
__term_sd_task_pre_ext_108 git_clone_repository https://github.com/Haoming02/sd-forge-couple "${SD_WEBUI_PATH}"/extensions OFF # 添加分区绘制的功能，仅支持forge
__term_sd_task_pre_ext_109 git_clone_repository https://github.com/Haoming02/sd-webui-advanced-xyz "${SD_WEBUI_PATH}"/extensions OFF # 改进xyz图表的功能
__term_sd_task_pre_ext_110 git_clone_repository https://github.com/Haoming02/sd-webui-mosaic-outpaint "${SD_WEBUI_PATH}"/extensions ON # 快捷扩图工具
__term_sd_task_pre_ext_111 git_clone_repository https://github.com/Haoming02/sd-webui-image-comparison "${SD_WEBUI_PATH}"/extensions OFF # 图片对比工具
__term_sd_task_pre_ext_112 git_clone_repository https://github.com/Haoming02/sd-webui-diffusion-cg "${SD_WEBUI_PATH}"/extensions OFF # 在潜空间张量范围执行颜色分级，改善出图的效果
__term_sd_task_pre_ext_113 git_clone_repository https://github.com/Haoming02/sd-webui-resharpen "${SD_WEBUI_PATH}"/extensions OFF # 图片锐化工具，改善出图效果
__term_sd_task_pre_ext_114 git_clone_repository https://github.com/Haoming02/sd-webui-mobile-friendly "${SD_WEBUI_PATH}"/extensions OFF # 使界面排版在手机上更合理
__term_sd_task_pre_ext_115 git_clone_repository https://github.com/Haoming02/sd-webui-prompt-format "${SD_WEBUI_PATH}"/extensions OFF # 提示词格式化工具
__term_sd_task_pre_ext_116 git_clone_repository https://github.com/Haoming02/sd-webui-aaa "${SD_WEBUI_PATH}"/extensions OFF # 为主体生成用于修复的蒙版，使背景与主体融合更融洽
__term_sd_task_pre_ext_117 git_clone_repository https://github.com/Haoming02/sd-webui-clear-screen "${SD_WEBUI_PATH}"/extensions OFF # 清理控制台输出
__term_sd_task_pre_ext_118 git_clone_repository https://github.com/Haoming02/sd-webui-auto-res "${SD_WEBUI_PATH}"/extensions OFF # 通过预设自动设置不同模型的分辨率
__term_sd_task_pre_ext_119 git_clone_repository https://github.com/Haoming02/sd-webui-moar-generate "${SD_WEBUI_PATH}"/extensions OFF # 添加了另一个生成按钮，用于当有太多活动扩展但不想每次都一直向上滚动时
__term_sd_task_pre_ext_120 git_clone_repository https://github.com/Tzigo/metadata_utils "${SD_WEBUI_PATH}"/extensions OFF # 为sd-webui-supermerger融合的模型添加元数据
__term_sd_task_pre_ext_121 git_clone_repository https://github.com/w-e-w/sd-webui-xyz-addon "${SD_WEBUI_PATH}"/extensions OFF # 为xyz脚本添加更多功能
__term_sd_task_pre_ext_122 git_clone_repository https://github.com/Repeerc/sd-webui-flash-attention-zluda-win "${SD_WEBUI_PATH}"/extensions OFF # 为zluda添加flash-attension优化
__term_sd_task_pre_ext_123 git_clone_repository https://github.com/thisjam/sd-webui-split-layout "${SD_WEBUI_PATH}"/extensions OFF # 调整界面布局
__term_sd_task_pre_ext_124 git_clone_repository https://github.com/thisjam/sd-webui-oldsix-prompt "${SD_WEBUI_PATH}"/extensions OFF # 提示词辅助工具
__term_sd_task_pre_ext_125 git_clone_repository https://github.com/Nuullll/sd-webui-ipex-enhancement "${SD_WEBUI_PATH}"/extensions OFF # 优化IPEX后端的运行体验
__term_sd_task_pre_ext_126 git_clone_repository https://github.com/MackinationsAi/sd-webui-udav2 "${SD_WEBUI_PATH}"/extensions OFF # 添加DepthAnythingV2支持
__term_sd_task_pre_ext_127 git_clone_repository https://github.com/light-and-ray/sd-webui-cn-sam-preprocessor "${SD_WEBUI_PATH}"/extensions OFF # 为ControlNet插件添加SegmentAnything预处理器
__term_sd_task_pre_ext_128 git_clone_repository https://github.com/bluelovers/sd-webui-pnginfo-beautify "${SD_WEBUI_PATH}"/extensions OFF # 将图片下方的生图信息进行美化排版
__term_sd_task_pre_ext_129 git_clone_repository https://github.com/Haoming02/sd-webui-resource-monitor "${SD_WEBUI_PATH}"/extensions ON # 性能监测
__term_sd_task_pre_ext_130 git_clone_repository https://github.com/NON906/chara-searcher "${SD_WEBUI_PATH}"/extensions OFF # 角色图片搜索
__term_sd_task_pre_ext_131 git_clone_repository https://github.com/MakkiShizu/sd-webui-to_top_button "${SD_WEBUI_PATH}"/extensions OFF # 添加一个回滚至顶部按钮
__term_sd_task_pre_ext_132 git_clone_repository https://github.com/AndreyRGW/sd-webui-aurasr "${SD_WEBUI_PATH}"/extensions OFF # 添加AuraSR放大算法支持
__term_sd_task_pre_ext_133 git_clone_repository https://github.com/quanghuyn94/a1111-intelli-prompt "${SD_WEBUI_PATH}"/extensions OFF # 提示词辅助插件
__term_sd_task_pre_ext_134 git_clone_repository https://github.com/xlinx/sd-webui-decadetw-auto-prompt-llm "${SD_WEBUI_PATH}"/extensions OFF # 使用LLM辅助编写提示词
__term_sd_task_pre_ext_135 git_clone_repository https://github.com/Haoming02/sd-forge-temperature-settings "${SD_WEBUI_PATH}"/extensions OFF # 图片色温调节，仅支持Forge
__term_sd_task_pre_ext_136 git_clone_repository https://github.com/Haoming02/forge-space-SUPIR "${SD_WEBUI_PATH}"/extensions OFF # 为sd-webui-forge添加SUPIR支持
__term_sd_task_pre_ext_137 git_clone_repository https://github.com/Haoming02/forge-space-ollama "${SD_WEBUI_PATH}"/extensions OFF # 为sd-webui-forge添加ollama支持
__term_sd_task_pre_ext_138 git_clone_repository https://github.com/SenshiSentou/sd-webui-cardmaster "${SD_WEBUI_PATH}"/extensions OFF # 优化模型选项卡
__term_sd_task_pre_ext_139 git_clone_repository https://github.com/CurtisDS/extra-network-side-panel-for-a1111 "${SD_WEBUI_PATH}"/extensions OFF # 恢复旧版扩展模型按钮
__term_sd_task_pre_ext_140 git_clone_repository https://github.com/jessearodriguez/sd-forge-regional-prompter "${SD_WEBUI_PATH}"/extensions OFF # 为sd-webui-forge添加分区提示词支持
__term_sd_task_pre_ext_141 git_clone_repository https://github.com/LEv145/--sd-webui-ar-plus "${SD_WEBUI_PATH}"/extensions OFF # 宽高比选择工具
__term_sd_task_pre_ext_142 git_clone_repository https://github.com/DenOfEquity/forge2_cleaner "${SD_WEBUI_PATH}"/extensions OFF # 为sd-webui-forge添加图像内容擦除功能
__term_sd_task_pre_ext_143 git_clone_repository https://github.com/novitalabs/sd-webui-cleaner "${SD_WEBUI_PATH}"/extensions OFF # 添加图像内容擦除功能
__term_sd_task_pre_ext_144 git_clone_repository https://github.com/DenOfEquity/HyperTile "${SD_WEBUI_PATH}"/extensions OFF # 为sd-webui-forge添加HyperTile支持
__term_sd_task_pre_ext_145 git_clone_repository https://github.com/DenOfEquity/forgeFlux_dualPrompt "${SD_WEBUI_PATH}"/extensions OFF # 为sd-webui-forge添加多提示词功能
__term_sd_task_pre_ext_146 git_clone_repository https://github.com/Juqowel/GPU_For_T5 "${SD_WEBUI_PATH}"/extensions OFF # 为sd-webui-forge添加移动t5模型功能，可将t5模型权重移至指定gpu上
__term_sd_task_pre_ext_147 git_clone_repository https://github.com/Filexor/sd-webui-top-k-emphasis "${SD_WEBUI_PATH}"/extensions OFF # 为sd-webui-forge添加Top_K_Emphasis提示词语法
__term_sd_task_pre_ext_148 git_clone_repository https://github.com/wkpark/uddetailer "${SD_WEBUI_PATH}"/extensions OFF # 面部修复工具
__term_sd_task_pre_ext_149 git_clone_repository https://github.com/Zyin055/Config-Presets "${SD_WEBUI_PATH}"/extensions OFF # 生图参数预设保存工具
__term_sd_task_pre_ext_150 git_clone_repository https://github.com/brick2face/seamless-tile-inpainting "${SD_WEBUI_PATH}"/extensions OFF # 平滑平铺工具
__term_sd_task_pre_ext_151 git_clone_repository https://github.com/anapnoe/sd-webui-ux "${SD_WEBUI_PATH}"/extensions OFF # 更改sd-webui的界面
__term_sd_task_pre_ext_152 git_clone_repository https://github.com/light-and-ray/sd-webui-replacer "${SD_WEBUI_PATH}"/extensions OFF # 图片内容替换工具
__term_sd_task_pre_ext_153 git_clone_repository https://github.com/sdbds/stable-diffusion-webui-wildcards "${SD_WEBUI_PATH}"/extensions OFF # 添加提示词通配符支持
__term_sd_task_pre_ext_154 git_clone_repository https://github.com/ljleb/sd-webui-freeu "${SD_WEBUI_PATH}"/extensions OFF # 添加FreeU支持
__term_sd_task_pre_ext_155 git_clone_repository https://github.com/v0xie/sd-webui-incantations "${SD_WEBUI_PATH}"/extensions OFF # 添加PerturbedAttentionGuidance支持
__term_sd_task_pre_ext_156 git_clone_repository https://github.com/w-e-w/sd-webui-kohya-hiresfix "${SD_WEBUI_PATH}"/extensions OFF # 修复在直出高分辨率图片时画面异常的问题
__term_sd_task_pre_ext_157 git_clone_repository https://github.com/wkpark/sd-webui-model-mixer "${SD_WEBUI_PATH}"/extensions OFF # 模型融合工具
__term_sd_task_pre_ext_158 git_clone_repository https://github.com/Repeerc/sd-webui-flash-attention2-rdna3-rocm "${SD_WEBUI_PATH}"/extensions OFF # 为Windows下的ZLUDA添加FlashAttension支持
__term_sd_task_pre_ext_159 git_clone_repository https://github.com/licyk/sd-webui-tcd-sampler "${SD_WEBUI_PATH}"/extensions OFF # 为SDWebUI添加tcd采样算法
__term_sd_task_pre_ext_160 git_clone_repository https://github.com/dimitribarbot/sd-webui-birefnet "${SD_WEBUI_PATH}"/extensions OFF # 添加BiRefNet支持，用于移除背景
__term_sd_task_pre_ext_161 git_clone_repository https://github.com/muerrilla/stable-diffusion-NPW "${SD_WEBUI_PATH}"/extensions OFF # 为反向提示词添加整体权重设置
__term_sd_task_pre_ext_162 git_clone_repository https://github.com/licyk/sd_forge_hypertile_svd_z123 "${SD_WEBUI_PATH}"/extensions OFF # 为sd-webui和sd-webui-forge添加hypertile，svd，stable-z123支持
__term_sd_task_pre_ext_163 git_clone_repository https://github.com/viyiviyi/stable-diffusion-webui-zoomimage "${SD_WEBUI_PATH}"/extensions OFF # 为图片查看窗口添加鼠标缩放拖动功能
__term_sd_task_pre_ext_164 git_clone_repository https://github.com/gutris1/sd-simple-dimension-preset "${SD_WEBUI_PATH}"/extensions OFF # 图片分辨率预设
__term_sd_task_pre_ext_165 git_clone_repository https://github.com/gutris1/sd-hub "${SD_WEBUI_PATH}"/extensions OFF # 批量下载管理文件
__term_sd_task_pre_ext_166 git_clone_repository https://github.com/Avaray/lora-keywords-finder "${SD_WEBUI_PATH}"/extensions OFF # 使用civitai-api查询lora模型触发词
__term_sd_task_pre_ext_167 git_clone_repository https://github.com/MINENEMA/sd-webui-quickrecents "${SD_WEBUI_PATH}"/extensions OFF # 查看最近几次图片生成参数并导入
