__term_sd_task_pre_ext_34 term_sd_echo "下载controlnet模型中"
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/cldm_v15.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models cldm_v15.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/cldm_v21.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models cldm_v21.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_canny.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_sd15_canny.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_depth.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_sd15_depth.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_hed.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_sd15_hed.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_mlsd.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_sd15_mlsd.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_normal.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_sd15_normal.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_openpose.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_sd15_openpose.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_scribble.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_sd15_scribble.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_seg.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_sd15_seg.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11e_sd15_ip2p_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11e_sd15_ip2p_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11e_sd15_ip2p_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11e_sd15_ip2p_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11e_sd15_shuffle_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11e_sd15_shuffle_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11e_sd15_shuffle_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11e_sd15_shuffle_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11f1e_sd15_tile_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11f1e_sd15_tile_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11f1e_sd15_tile_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11f1e_sd15_tile_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11f1p_sd15_depth_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11f1p_sd15_depth_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11f1p_sd15_depth_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11f1p_sd15_depth_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_canny_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_canny_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_canny_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_canny_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_inpaint_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_inpaint_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_inpaint_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_inpaint_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_lineart_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_lineart_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_lineart_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_lineart_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_mlsd_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_mlsd_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_mlsd_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_mlsd_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_normalbae_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_normalbae_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_normalbae_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_normalbae_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_openpose_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_openpose_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_openpose_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_openpose_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_scribble_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_scribble_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_scribble_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_scribble_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_seg_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_seg_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_seg_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_seg_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_softedge_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_softedge_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_softedge_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15_softedge_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15s2_lineart_anime_fp16.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15s2_lineart_anime_fp16.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15s2_lineart_anime_fp16.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v11p_sd15s2_lineart_anime_fp16.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v1p_sd15_brightness.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v1p_sd15_brightness.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v1p_sd15_illumination.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v1p_sd15_illumination.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v1p_sd15_qrcode_monster.safetensors "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v1p_sd15_qrcode_monster.safetensors
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v1p_sd15_qrcode_monster.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models control_v1p_sd15_qrcode_monster.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_canny_sd15v2.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_canny_sd15v2.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_canny_sd15v2.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_canny_sd15v2.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_color_sd14v1.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_color_sd14v1.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_color_sd14v1.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_color_sd14v1.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_depth_sd15v2.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_depth_sd15v2.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_depth_sd15v2.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_depth_sd15v2.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_keypose_sd14v1.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_keypose_sd14v1.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_keypose_sd14v1.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_keypose_sd14v1.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_openpose_sd14v1.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_openpose_sd14v1.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_openpose_sd14v1.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_openpose_sd14v1.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_seg_sd14v1.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_seg_sd14v1.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_seg_sd14v1.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_seg_sd14v1.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_sketch_sd15v2.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_sketch_sd15v2.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_sketch_sd15v2.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_sketch_sd15v2.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_style_sd14v1.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_style_sd14v1.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_style_sd14v1.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_style_sd14v1.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_zoedepth_sd15v1.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_zoedepth_sd15v1.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_zoedepth_sd15v1.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models t2iadapter_zoedepth_sd15v1.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/image_adapter_v14.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models image_adapter_v14.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/ip-adapter-plus-face_sd15.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models ip-adapter-plus-face_sd15.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/ip-adapter_sd15.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models ip-adapter_sd15.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/ip-adapter_sd15_light.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models ip-adapter_sd15_light.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/ip-adapter_sd15_plus.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/models ip-adapter_sd15_plus.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/sketch_adapter_v14.yaml "$sd_webui_folder"/extensions/sd-webui-controlnet/models sketch_adapter_v14.yaml
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/clip_vision/clip_g.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/clip_vision clip_g.pth #controlnet预处理器
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/clip_vision/clip_h.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/clip_vision clip_h.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/clip_vision/clip_vitl.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/clip_vision clip_vitl.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/hed/ControlNetHED.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/hed ControlNetHED.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/lama/ControlNetLama.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/lama ControlNetLama.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/leres/latest_net_G.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/leres latest_net_G.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/leres/res101.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/leres res101.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/lineart/sk_model.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/lineart sk_model.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/lineart/sk_model2.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/lineart sk_model2.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/lineart_anime/netG.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/lineart_anime netG.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/manga_line/erika.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/manga_line erika.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/midas/dpt_hybrid-midas-501f0c75.pt "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/midas dpt_hybrid-midas-501f0c75.pt
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/mlsd/mlsd_large_512_fp32.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/mlsd mlsd_large_512_fp32.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/normal_bae/scannet.pt "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/normal_bae scannet.pt
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/oneformer/150_16_swin_l_oneformer_coco_100ep.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/oneformer 150_16_swin_l_oneformer_coco_100ep.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/oneformer/250_16_swin_l_oneformer_ade20k_160k.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/oneformer 250_16_swin_l_oneformer_ade20k_160k.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/openpose/body_pose_model.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/openpose body_pose_model.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/openpose/dw-ll_ucoco_384.onnx "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/openpose dw-ll_ucoco_384.onnx
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/openpose/facenet.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/openpose facenet.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/openpose/hand_pose_model.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/openpose hand_pose_model.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/openpose/yolox_l.onnx "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/openpose yolox_l.onnx
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/pidinet/table5_pidinet.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/pidinet table5_pidinet.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/uniformer/upernet_global_small.pth "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/uniformer upernet_global_small.pth
__term_sd_task_pre_ext_34 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/zoedepth/ZoeD_M12_N.pt "$sd_webui_folder"/extensions/sd-webui-controlnet/annotator/downloads/zoedepth ZoeD_M12_N.pt

__term_sd_task_pre_ext_37 term_sd_echo "下载animatediff模型"
__term_sd_task_pre_ext_37 aria2_download https://huggingface.co/guoyww/animatediff/resolve/main/mm_sd_v15_v2.ckpt "$sd_webui_folder"/extensions/sd-webui-animatediff/model mm_sd_v15_v2.ckpt

__term_sd_task_pre_ext_42 term_sd_echo "下载adetailer模型"
__term_sd_task_pre_ext_42 aria2_download https://huggingface.co/Bingsu/adetailer/resolve/main/deepfashion2_yolov8s-seg.pt "$sd_webui_folder"/models/adetailer deepfashion2_yolov8s-seg.pt # adetailer模型
__term_sd_task_pre_ext_42 aria2_download https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8m.pt "$sd_webui_folder"/models/adetailer face_yolov8m.pt
__term_sd_task_pre_ext_42 aria2_download https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8n.pt "$sd_webui_folder"/models/adetailer face_yolov8n.pt
__term_sd_task_pre_ext_42 aria2_download https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8n_v2.pt "$sd_webui_folder"/models/adetailer face_yolov8n_v2.pt
__term_sd_task_pre_ext_42 aria2_download https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8s.pt "$sd_webui_folder"/models/adetailer face_yolov8s.pt
__term_sd_task_pre_ext_42 aria2_download https://huggingface.co/Bingsu/adetailer/resolve/main/hand_yolov8n.pt "$sd_webui_folder"/models/adetailer hand_yolov8n.pt
__term_sd_task_pre_ext_42 aria2_download https://huggingface.co/Bingsu/adetailer/resolve/main/hand_yolov8s.pt "$sd_webui_folder"/models/adetailer hand_yolov8s.pt
__term_sd_task_pre_ext_42 aria2_download https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8m-seg.pt "$sd_webui_folder"/models/adetailer person_yolov8m-seg.pt
__term_sd_task_pre_ext_42 aria2_download https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8n-seg.pt "$sd_webui_folder"/models/adetailer person_yolov8n-seg.pt
__term_sd_task_pre_ext_42 aria2_download https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8s-seg.pt "$sd_webui_folder"/models/adetailer person_yolov8s-seg.pt

__term_sd_task_pre_ext_44 term_sd_echo "下载IS-NET模型"
__term_sd_task_pre_ext_44 aria2_download https://huggingface.co/ClockZinc/IS-NET_pth/resolve/main/isnet-general-use.pth "$sd_webui_folder"/extensions/sd-webui-IS-NET-pro/saved_models/IS-Net isnet-general-use.pth

__term_sd_task_pre_ext_33 term_sd_echo "下载sd-webui-segment-anything模型"
__term_sd_task_pre_ext_33 aria2_download https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth "$sd_webui_folder"/extensions/sd-webui-segment-anything/models/sam sam_vit_h_4b8939.pth
__term_sd_task_pre_ext_33 aria2_download https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth "$sd_webui_folder"/extensions/sd-webui-segment-anything/models/sam sam_vit_l_0b3195.pth
__term_sd_task_pre_ext_33 aria2_download https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth "$sd_webui_folder"/extensions/sd-webui-segment-anything/models/sam sam_vit_b_01ec64.pth
__term_sd_task_pre_ext_33 aria2_download https://huggingface.co/ShilongLiu/GroundingDINO/resolve/main/groundingdino_swint_ogc.pth  "$sd_webui_folder"/extensions/sd-webui-segment-anything/models/grounding-dino/groundingdino_swint_ogc.pth
__term_sd_task_pre_ext_33 aria2_download https://huggingface.co/ShilongLiu/GroundingDINO/resolve/main/groundingdino_swinb_cogcoor.pth "$sd_webui_folder"/extensions/sd-webui-segment-anything/models/grounding-dino/groundingdino_swinb_cogcoor.pth

__term_sd_task_pre_ext_66 term_sd_echo "下载sd-webui-inpaint-anything模型"
__term_sd_task_pre_ext_66 aria2_download https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth "$sd_webui_folder"/extensions/sd-webui-inpaint-anything/models sam_vit_h_4b8939.pth
__term_sd_task_pre_ext_66 aria2_download https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth "$sd_webui_folder"/extensions/sd-webui-inpaint-anything/models sam_vit_l_0b3195.pth
__term_sd_task_pre_ext_66 aria2_download https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth "$sd_webui_folder"/extensions/sd-webui-inpaint-anything/models sam_vit_b_01ec64.pth
