__term_sd_task_pre_model_1 # =====SD1.5大模型===== OFF
__term_sd_task_pre_model_2 get_modelscope_model licyks/sd-model/master/sd_1.5/v1-5-pruned-emaonly.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # 大模型 v1-5-pruned-emaonly(4.27g) OFF
__term_sd_task_pre_model_3 get_modelscope_model licyks/sd-model/master/sd_1.5/animefull-final-pruned.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # animefull-final-pruned(4.27g) OFF
__term_sd_task_pre_model_4 get_modelscope_model licyks/sd-model/master/sd_1.5/nai1-artist_all_in_one_merge.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # nai1-artist_all_in_one_merge(2.13g) OFF
__term_sd_task_pre_model_5 get_modelscope_model licyks/sd-model/master/sd_1.5/Counterfeit-V3.0_fp16.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # Counterfeit-V3.0(4.24g) OFF
__term_sd_task_pre_model_6 get_modelscope_model licyks/sd-model/master/sd_1.5/cetusMix_Whalefall2.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # cetusMix_Whalefall2(3.85g) OFF
__term_sd_task_pre_model_7 get_modelscope_model licyks/sd-model/master/sd_1.5/cuteyukimixAdorable_neochapter3.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # cuteyukimixAdorable_neochapter3(2.3g) OFF
__term_sd_task_pre_model_8 get_modelscope_model licyks/sd-model/master/sd_1.5/ekmix-pastel-fp16-no-ema.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # ekmix-pastel(2.13g) OFF
__term_sd_task_pre_model_9 get_modelscope_model licyks/sd-model/master/sd_1.5/ex2K_sse2.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # ex2K_sse2(2.38g) OFF
__term_sd_task_pre_model_10 get_modelscope_model licyks/sd-model/master/sd_1.5/kohakuV5_rev2.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # kohakuV5_rev2(2.13g) OFF
__term_sd_task_pre_model_11 get_modelscope_model licyks/sd-model/master/sd_1.5/meinamix_meinaV11.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # meinamix_meinaV11(2.13g) OFF
__term_sd_task_pre_model_12 get_modelscope_model licyks/sd-model/master/sd_1.5/oukaStar_10.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # oukaStar_10(5.43g) OFF
__term_sd_task_pre_model_13 get_modelscope_model licyks/sd-model/master/sd_1.5/pastelMixStylizedAnime_pastelMixPrunedFP16.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # pastelMixStylizedAnime(2.13g) OFF
__term_sd_task_pre_model_14 get_modelscope_model licyks/sd-model/master/sd_1.5/rabbit_v6.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # rabbit_v6(1.97g) OFF
__term_sd_task_pre_model_15 get_modelscope_model licyks/sd-model/master/sd_1.5/sweetSugarSyndrome_rev15.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sweetSugarSyndrome_rev15(2.13g) OFF
__term_sd_task_pre_model_16 get_modelscope_model licyks/sd-model/master/sd_1.5/AnythingV5Ink_ink.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # AnythingV5Ink_ink(2.13g) OFF
__term_sd_task_pre_model_17 get_modelscope_model licyks/sd-model/master/sd_1.5/bartstyledbBlueArchiveArtStyleFineTunedModel_v10.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # bartstyledbBlueArchiveArtStyle(2.13g) OFF
__term_sd_task_pre_model_18 get_modelscope_model licyks/sd-model/master/sd_1.5/meinapastel_v6Pastel.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # meinapastel_v6(2.13g) OFF
__term_sd_task_pre_model_19 get_modelscope_model licyks/sd-model/master/sd_1.5/qteamixQ_omegaFp16.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # qteamix(2.13g) OFF
__term_sd_task_pre_model_20 get_modelscope_model licyks/sd-model/master/sd_1.5/tmndMix_tmndMixSPRAINBOW.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # tmndMix(2.13g) OFF
__term_sd_task_pre_model_21 # =====SD2.1大模型===== OFF
__term_sd_task_pre_model_22 get_modelscope_model licyks/sd-model/master/sd_2.1/v2-1_768-ema-pruned.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # v2-1_768-ema-pruned(5.21g) OFF
__term_sd_task_pre_model_23 get_modelscope_model licyks/sd-model/master/sd_2.1/wd-1-4-anime_e2.ckpt "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # wd-1-4-anime_e2(5.16g) OFF
__term_sd_task_pre_model_24 get_modelscope_model licyks/sd-model/master/sd_2.1/wd-mofu-fp16.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # wd-mofu-fp16(2.58g) OFF
__term_sd_task_pre_model_25 # =====SDXL大模型===== OFF
__term_sd_task_pre_model_26 get_modelscope_model licyks/sd-lora/master/sdxl/sd_xl_offset_example-lora_1.0.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Lora # sd_xl_offset_example-lora_1.0(49.6m) OFF
__term_sd_task_pre_model_27 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sd_xl_base_1.0_0.9vae.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sd_xl_base_1.0_0.9vae(6.94g) OFF
__term_sd_task_pre_model_28 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sd_xl_refiner_1.0_0.9vae.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sd_xl_refiner_1.0_0.9vae(6.94g) OFF
__term_sd_task_pre_model_29 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sd_xl_turbo_1.0_fp16.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sd_xl_turbo_1.0_fp16(6.94g) OFF
__term_sd_task_pre_model_30 get_modelscope_model licyks/sd-model/master/sdxl_1.0/cosxl.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # cosxl(6.94g) OFF
__term_sd_task_pre_model_31 get_modelscope_model licyks/sd-model/master/sdxl_1.0/cosxl_edit.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # cosxl_edit(6.94g) OFF
__term_sd_task_pre_model_32 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animagine-xl-3.0-base.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # animagine-xl-3.0-base(6.94g) OFF
__term_sd_task_pre_model_33 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animagine-xl-3.0.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # animagine-xl-3.0(6.94g) OFF
__term_sd_task_pre_model_34 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animagine-xl-3.1.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # animagine-xl-3.1(6.94g) OFF
__term_sd_task_pre_model_35 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animagine-xl-4.0.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # animagine-xl-4.0(6.94g) OFF
__term_sd_task_pre_model_36 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animagine-xl-4.0-opt.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # animagine-xl-4.0-opt(6.94g) OFF
__term_sd_task_pre_model_37 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animagine-xl-4.0-zero.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # animagine-xl-4.0-zero(6.94g) OFF
__term_sd_task_pre_model_38 get_modelscope_model licyks/sd-model/master/sdxl_1.0/holodayo-xl-2.1.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # holodayo-xl-2.1(6.94g) OFF
__term_sd_task_pre_model_39 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kivotos-xl-2.0.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # kivotos-xl-2.0(6.94g) OFF
__term_sd_task_pre_model_40 get_modelscope_model licyks/sd-model/master/sdxl_1.0/clandestine-xl-1.0.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # clandestine-xl-1.0(6.94g) OFF
__term_sd_task_pre_model_41 get_modelscope_model licyks/sd-model/master/sdxl_1.0/UrangDiffusion-1.1.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # UrangDiffusion-1.1(6.94g) OFF
__term_sd_task_pre_model_42 get_modelscope_model licyks/sd-model/master/sdxl_1.0/RaeDiffusion-XL-v2.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # RaeDiffusion-XL-v2(6.94g) OFF
__term_sd_task_pre_model_43 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sd_xl_anime_V52.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sd_xl_anime_V52(6.94g) OFF
__term_sd_task_pre_model_44 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kohaku-xl-delta-rev1.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # kohaku-xl-delta-rev1(6.94g) OFF
__term_sd_task_pre_model_45 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kohakuXLEpsilon_rev1.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # kohakuXLEpsilon_rev1(6.94g) OFF
__term_sd_task_pre_model_46 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kohaku-xl-epsilon-rev2.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # kohaku-xl-epsilon-rev2(6.94g) OFF
__term_sd_task_pre_model_47 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kohaku-xl-epsilon-rev3.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # kohaku-xl-epsilon-rev3(6.94g) OFF
__term_sd_task_pre_model_48 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kohaku-xl-zeta.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # kohaku-xl-zeta(6.94g) OFF
__term_sd_task_pre_model_49 get_modelscope_model licyks/sd-model/master/sdxl_1.0/starryXLV52_v52.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # starryXLV52_v52(6.94g) OFF
__term_sd_task_pre_model_50 get_modelscope_model licyks/sd-model/master/sdxl_1.0/heartOfAppleXL_v20.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # heartOfAppleXL_v20(6.94g) OFF
__term_sd_task_pre_model_51 get_modelscope_model licyks/sd-model/master/sdxl_1.0/heartOfAppleXL_v30.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # heartOfAppleXL_v30(6.94g) OFF
__term_sd_task_pre_model_52 get_modelscope_model licyks/sd-model/master/sdxl_1.0/baxlBartstylexlBlueArchiveFlatCelluloid_xlv1.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # baxlBartstylexlBlueArchiveFlatCelluloid_xlv1(6.94g) OFF
__term_sd_task_pre_model_53 get_modelscope_model licyks/sd-model/master/sdxl_1.0/baxlBlueArchiveFlatCelluloidStyle_xlv3.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # baxlBlueArchiveFlatCelluloidStyle_xlv3(6.94g) OFF
__term_sd_task_pre_model_54 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sanaexlAnimeV10_v10.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sanaexlAnimeV10_v10(6.94g) OFF
__term_sd_task_pre_model_55 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sanaexlAnimeV10_v11.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sanaexlAnimeV10_v11(6.94g) OFF
__term_sd_task_pre_model_56 get_modelscope_model licyks/sd-model/master/sdxl_1.0/SanaeXL-Anime-v1.2-aesthetic.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # SanaeXL-Anime-v1.2-aesthetic(6.94g) OFF
__term_sd_task_pre_model_57 get_modelscope_model licyks/sd-model/master/sdxl_1.0/SanaeXL-Anime-v1.3-aesthetic.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # SanaeXL-Anime-v1.3-aesthetic(6.94g) OFF
__term_sd_task_pre_model_58 get_modelscope_model licyks/sd-model/master/sdxl_1.0/Illustrious-XL-v0.1.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # Illustrious-XL-v0.1(6.94g) OFF
__term_sd_task_pre_model_59 get_modelscope_model licyks/sd-model/master/sdxl_1.0/Illustrious-XL-v0.1-GUIDED.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # Illustrious-XL-v0.1-GUIDED(6.94g) OFF
__term_sd_task_pre_model_60 get_modelscope_model licyks/sd-model/master/sdxl_1.0/Illustrious-XL-v1.0.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # Illustrious-XL-v1.0(6.94g) ON
__term_sd_task_pre_model_61 get_modelscope_model licyks/sd-model/master/sdxl_1.0/Illustrious-XL-v1.1.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # Illustrious-XL-v1.1(6.94g) OFF
__term_sd_task_pre_model_62 get_modelscope_model licyks/sd-model/master/sdxl_1.0/Illustrious-XL-v2.0-stable.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # Illustrious-XL-v2.0-stable(6.94g) OFF
__term_sd_task_pre_model_63 get_modelscope_model licyks/sd-model/master/sdxl_1.0/Illustrious-XL-v2.0.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # Illustrious-XL-v2.0(6.94g) OFF
__term_sd_task_pre_model_64 get_modelscope_model licyks/sd-model/master/sdxl_1.0/jruTheJourneyRemains_v25XL.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # jruTheJourneyRemains_v25XL(6.94g) OFF
__term_sd_task_pre_model_65 get_modelscope_model licyks/sd-model/master/sdxl_1.0/PVCStyleModelMovable_illustriousxl10.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # PVCStyleModelMovable_illustriousxl10(6.94g) OFF
__term_sd_task_pre_model_66 get_modelscope_model licyks/sd-model/master/sdxl_1.0/miaomiaoHarem_v15a.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # miaomiaoHarem_v15a(6.94g) OFF
__term_sd_task_pre_model_67 get_modelscope_model licyks/sd-model/master/sdxl_1.0/waiNSFWIllustrious_v80.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # waiNSFWIllustrious_v80(6.94g) OFF
__term_sd_task_pre_model_68 get_modelscope_model licyks/sd-model/master/sdxl_1.0/tIllunai3_v4.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # tIllunai3_v4(6.94g) OFF
__term_sd_task_pre_model_69 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_earlyAccessVersion.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_earlyAccessVersion(6.94g) OFF
__term_sd_task_pre_model_70 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_epsilonPred05Version.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_epsilonPred05Version(6.94g) OFF
__term_sd_task_pre_model_71 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_epsilonPred075.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_epsilonPred075(6.94g) OFF
__term_sd_task_pre_model_72 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_epsilonPred077.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_epsilonPred077(6.94g) OFF
__term_sd_task_pre_model_73 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_epsilonPred10Version.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_epsilonPred10Version(6.94g) OFF
__term_sd_task_pre_model_74 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_epsilonPred11Version.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_epsilonPred11Version(6.94g) OFF
__term_sd_task_pre_model_75 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_vPredTestVersion.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_vPredTestVersion(6.94g) OFF
__term_sd_task_pre_model_76 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_vPred05Version.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_vPred05Version(6.94g) OFF
__term_sd_task_pre_model_77 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_vPred06Version.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_vPred06Version(6.94g) OFF
__term_sd_task_pre_model_78 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_vPred065SVersion.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_vPred065SVersion(6.94g) OFF
__term_sd_task_pre_model_79 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_vPred075SVersion.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_vPred075SVersion(6.94g) OFF
__term_sd_task_pre_model_80 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_vPred09RVersion.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_vPred09RVersion(6.94g) OFF
__term_sd_task_pre_model_81 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_vPred10Version.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # noobaiXLNAIXL_vPred10Version(6.94g) OFF
__term_sd_task_pre_model_82 get_modelscope_model licyks/sd-model/master/sdxl_1.0/PVCStyleModelMovable_nbxl12.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # PVCStyleModelMovable_nbxl12(6.94g) OFF
__term_sd_task_pre_model_83 get_modelscope_model licyks/sd-model/master/sdxl_1.0/PVCStyleModelMovable_nbxlVPredV10.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # PVCStyleModelMovable_nbxlVPredV10(6.94g) OFF
__term_sd_task_pre_model_84 get_modelscope_model licyks/sd-model/master/sdxl_1.0/ponyDiffusionV6XL_v6StartWithThisOne.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # ponyDiffusionV6XL_v6(6.94g) OFF
__term_sd_task_pre_model_85 get_modelscope_model licyks/sd-model/master/sdxl_1.0/pdForAnime_v20.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # pdForAnime_v20(7.11g) OFF
__term_sd_task_pre_model_86 get_modelscope_model licyks/sd-model/master/sdxl_1.0/tPonynai3_v51WeightOptimized.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # tPonynai3_v51WeightOptimized(6.94g) OFF
__term_sd_task_pre_model_87 get_modelscope_model licyks/sd-model/master/sdxl_1.0/omegaPonyXLAnime_v20.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # omegaPonyXLAnime_v20(6.94g) OFF
__term_sd_task_pre_model_88 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animeIllustDiffusion_v061.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # animeIllustDiffusion_v061(6.94g) OFF
__term_sd_task_pre_model_89 get_modelscope_model licyks/sd-model/master/sdxl_1.0/artiwaifuDiffusion_v10.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # artiwaifuDiffusion_v10(6.94g) OFF
__term_sd_task_pre_model_90 get_modelscope_model licyks/sd-model/master/sdxl_1.0/artiwaifu-diffusion-v2.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # artiwaifu-diffusion-v2(6.94g) OFF
__term_sd_task_pre_model_91 get_modelscope_model licyks/sd-model/master/sdxl_1.0/AnythingXL_xl.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # AnythingXL_xl(6.94g) OFF
__term_sd_task_pre_model_92 get_modelscope_model licyks/sd-model/master/sdxl_1.0/abyssorangeXLElse_v10.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # abyssorangeXLElse_v10(6.94g) OFF
__term_sd_task_pre_model_93 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animaPencilXL_v200.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # animaPencilXL_v200(6.94g) OFF
__term_sd_task_pre_model_94 get_modelscope_model licyks/sd-model/master/sdxl_1.0/bluePencilXL_v401.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # bluePencilXL_v401(6.94g) OFF
__term_sd_task_pre_model_95 get_modelscope_model licyks/sd-model/master/sdxl_1.0/nekorayxl_v06W3.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # nekorayxl_v06W3(6.94g) OFF
__term_sd_task_pre_model_96 get_modelscope_model licyks/sd-model/master/sdxl_1.0/CounterfeitXL-V1.0.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # CounterfeitXL-V1.0(6.94g) OFF
__term_sd_task_pre_model_97 # =====SD3大模型===== OFF
__term_sd_task_pre_model_98 get_modelscope_model licyks/sd-3-model/master/sd3_medium.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sd3_medium(4.34g) OFF
__term_sd_task_pre_model_99 get_modelscope_model licyks/sd-3-model/master/sd3_medium_incl_clips.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sd3_medium_incl_clips(5.97g) OFF
__term_sd_task_pre_model_100 get_modelscope_model licyks/sd-3-model/master/sd3_medium_incl_clips_t5xxlfp8.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sd3_medium_incl_clips_t5xxlfp8(10.87g) OFF
__term_sd_task_pre_model_101 get_modelscope_model licyks/sd-3-model/master/sd3.5_large.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sd3.5_large(16.5g) OFF
__term_sd_task_pre_model_102 get_modelscope_model licyks/sd-3-model/master/sd3.5_large_fp8_scaled.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sd3.5_large_fp8_scaled(14.9g) OFF
__term_sd_task_pre_model_103 get_modelscope_model licyks/sd-3-model/master/sd3.5_large_turbo.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sd3.5_large_turbo(16.5g) OFF
__term_sd_task_pre_model_104 get_modelscope_model licyks/sd-3-model/master/sd3.5_medium.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sd3.5_medium(5.1g) OFF
__term_sd_task_pre_model_105 get_modelscope_model licyks/sd-3-model/master/sd3.5_medium_incl_clips_t5xxlfp8scaled.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # sd3.5_medium_incl_clips_t5xxlfp8scaled(11.6g) OFF
__term_sd_task_pre_model_106 get_modelscope_model licyks/sd-3-model/master/emi3.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # emi3(16.5g) OFF
__term_sd_task_pre_model_107 # =====SD3文本编码器===== OFF
__term_sd_task_pre_model_108 get_modelscope_model licyks/sd-3-model/master/text_encoders/clip_g.safetensors "${SD_WEBUI_ROOT_PATH}"/models/CLIP # clip_g(1.39g) OFF
__term_sd_task_pre_model_109 get_modelscope_model licyks/sd-3-model/master/text_encoders/clip_l.safetensors "${SD_WEBUI_ROOT_PATH}"/models/CLIP # clip_l(246.1m) OFF
__term_sd_task_pre_model_110 get_modelscope_model licyks/sd-3-model/master/text_encoders/t5xxl_fp16.safetensors "${SD_WEBUI_ROOT_PATH}"/models/CLIP # t5xxl_fp16(9.79g) OFF
__term_sd_task_pre_model_111 get_modelscope_model licyks/sd-3-model/master/text_encoders/t5xxl_fp8_e4m3fn.safetensors "${SD_WEBUI_ROOT_PATH}"/models/CLIP # t5xxl_fp8_e4m3fn(4.89g) OFF
__term_sd_task_pre_model_112 get_modelscope_model licyks/sd-3-model/master/text_encoders/t5xxl_fp8_e4m3fn_scaled.safetensors "${SD_WEBUI_ROOT_PATH}"/models/CLIP # t5xxl_fp8_e4m3fn_scaled(5.16g) OFF
__term_sd_task_pre_model_113 # =====FLUX模型===== OFF
__term_sd_task_pre_model_114 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev(23.8g) OFF
__term_sd_task_pre_model_115 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-fp8.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-fp8(17.2g) OFF
__term_sd_task_pre_model_116 get_modelscope_model licyks/flux-model/master/flux_1/flux_dev_fp8_scaled_diffusion_model.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux_dev_fp8_scaled_diffusion_model(11.9g) OFF
__term_sd_task_pre_model_117 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-bnb-nf4-v2.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-bnb-nf4-v2(12g) OFF
__term_sd_task_pre_model_118 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-bnb-nf4.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-bnb-nf4(11.5g) OFF
__term_sd_task_pre_model_119 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-Q2_K.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-Q2_K-gguf(4.03g) OFF
__term_sd_task_pre_model_120 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-Q3_K_S.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-Q3_K_S-gguf(5.23g) OFF
__term_sd_task_pre_model_121 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-Q4_0.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-Q4_0-gguf(6.79g) OFF
__term_sd_task_pre_model_122 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-Q4_1.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-Q4_1-gguf(7.53g) OFF
__term_sd_task_pre_model_123 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-Q4_K_S.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-Q4_K_S-gguf(6.81g) OFF
__term_sd_task_pre_model_124 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-Q5_0.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-Q5_0-gguf(8.27g) OFF
__term_sd_task_pre_model_125 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-Q5_1.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-Q5_1-gguf(9.01g) OFF
__term_sd_task_pre_model_126 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-Q5_K_S.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-Q5_K_S-gguf(8.29g) OFF
__term_sd_task_pre_model_127 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-Q6_K.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-Q6_K-gguf(9.86g) OFF
__term_sd_task_pre_model_128 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-Q8_0.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-Q8_0-gguf(12.7g) OFF
__term_sd_task_pre_model_129 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-F16.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-F16-gguf(23.8g) OFF
__term_sd_task_pre_model_130 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell(23.8g) OFF
__term_sd_task_pre_model_131 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell-fp8.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell-fp8(17.2g) OFF
__term_sd_task_pre_model_132 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell-Q2_K.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell-Q2_K-gguf(4.01g) OFF
__term_sd_task_pre_model_133 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell-Q3_K_S.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell-Q3_K_S-gguf(5.21g) OFF
__term_sd_task_pre_model_134 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell-Q4_0.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell-Q4_0-gguf(6.77g) OFF
__term_sd_task_pre_model_135 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell-Q4_1.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell-Q4_1-gguf(7.51g) OFF
__term_sd_task_pre_model_136 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell-Q4_K_S.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell-Q4_K_S-gguf(6.78g) OFF
__term_sd_task_pre_model_137 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell-Q5_0.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell-Q5_0-gguf(8.25g) OFF
__term_sd_task_pre_model_138 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell-Q5_1.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell-Q5_1-gguf(8.99g) OFF
__term_sd_task_pre_model_139 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell-Q5_K_S.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell-Q5_K_S-gguf(8.26g) OFF
__term_sd_task_pre_model_140 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell-Q6_K.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell-Q6_K-gguf(9.83g) OFF
__term_sd_task_pre_model_141 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell-Q8_0.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell-Q8_0-gguf(12.7g) OFF
__term_sd_task_pre_model_142 get_modelscope_model licyks/flux-model/master/flux_1/flux1-schnell-F16.gguf "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-schnell-F16-gguf(23.8g) OFF
__term_sd_task_pre_model_143 get_modelscope_model licyks/flux-model/master/flux_1/ashen0209-flux1-dev2pro.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # ashen0209-flux1-dev2pro(23.8g) OFF
__term_sd_task_pre_model_144 get_modelscope_model licyks/flux-model/master/flux_1/jimmycarter-LibreFLUX.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # jimmycarter-LibreFLUX(23.8g) OFF
__term_sd_task_pre_model_145 get_modelscope_model licyks/flux-model/master/flux_1/nyanko7-flux-dev-de-distill.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # nyanko7-flux-dev-de-distill(23.8g) OFF
__term_sd_task_pre_model_146 get_modelscope_model licyks/flux-model/master/flux_1/shuttle-3-diffusion.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # shuttle-3-diffusion(23.8g) OFF
__term_sd_task_pre_model_147 get_modelscope_model licyks/flux-model/master/flux_1/flux1-krea-dev_fp8_scaled.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-krea-dev_fp8_scaled(23.8g) OFF
__term_sd_task_pre_model_148 get_modelscope_model licyks/flux-model/master/flux_1/flux1-krea-dev.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-krea-dev(23.8g) OFF
__term_sd_task_pre_model_149 get_modelscope_model licyks/flux-model/master/flux_1/flux1-dev-kontext_fp8_scaled.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-dev-kontext_fp8_scaled(23.8g) OFF
__term_sd_task_pre_model_150 get_modelscope_model licyks/flux-model/master/flux_1/flux1-kontext-dev.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # flux1-kontext-dev(23.8g) OFF
__term_sd_task_pre_model_151 get_modelscope_model licyks/flux-model/master/flux_1/chroma-unlocked-v50.safetensors "${SD_WEBUI_ROOT_PATH}"/models/Stable-diffusion # chroma-unlocked-v50(23.8g) OFF
__term_sd_task_pre_model_152 # =====FLUX-文本编码器/VAE模型===== OFF
__term_sd_task_pre_model_153 get_modelscope_model licyks/flux-model/master/flux_text_encoders/clip_l.safetensors "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # clip_l(246.1m) OFF
__term_sd_task_pre_model_154 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5xxl_fp16.safetensors "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5xxl_fp16(9.79g) OFF
__term_sd_task_pre_model_155 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5xxl_fp8_e4m3fn.safetensors "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5xxl_fp8_e4m3fn(4.89g) OFF
__term_sd_task_pre_model_156 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5-v1_1-xxl-encoder-Q3_K_L.gguf "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5-v1_1-xxl-encoder-Q3_K_L-gguf(2.46g) OFF
__term_sd_task_pre_model_157 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5-v1_1-xxl-encoder-Q3_K_M.gguf "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5-v1_1-xxl-encoder-Q3_K_M-gguf(2.3g) OFF
__term_sd_task_pre_model_158 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5-v1_1-xxl-encoder-Q3_K_S.gguf "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5-v1_1-xxl-encoder-Q3_K_S-gguf(2.1g) OFF
__term_sd_task_pre_model_159 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5-v1_1-xxl-encoder-Q4_K_M.gguf "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5-v1_1-xxl-encoder-Q4_K_M-gguf(2.9g) OFF
__term_sd_task_pre_model_160 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5-v1_1-xxl-encoder-Q4_K_S.gguf "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5-v1_1-xxl-encoder-Q4_K_S-gguf(2.74g) OFF
__term_sd_task_pre_model_161 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5-v1_1-xxl-encoder-Q5_K_M.gguf "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5-v1_1-xxl-encoder-Q5_K_M-gguf(3.39g) OFF
__term_sd_task_pre_model_162 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5-v1_1-xxl-encoder-Q5_K_S.gguf "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5-v1_1-xxl-encoder-Q5_K_S-gguf(3.29g) OFF
__term_sd_task_pre_model_163 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5-v1_1-xxl-encoder-Q6_K.gguf "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5-v1_1-xxl-encoder-Q6_K-gguf(3.91g) OFF
__term_sd_task_pre_model_164 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5-v1_1-xxl-encoder-Q8_0.gguf "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5-v1_1-xxl-encoder-Q8_0-gguf(5.06g) OFF
__term_sd_task_pre_model_165 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5-v1_1-xxl-encoder-f16.gguf "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5-v1_1-xxl-encoder-f16-gguf(9.53g) OFF
__term_sd_task_pre_model_166 get_modelscope_model licyks/flux-model/master/flux_text_encoders/t5-v1_1-xxl-encoder-f32.gguf "${SD_WEBUI_ROOT_PATH}"/models/text_encoder # t5-v1_1-xxl-encoder-f32-gguf(19.1g) OFF
__term_sd_task_pre_model_167 get_modelscope_model licyks/flux-model/master/flux_vae/ae.safetensors "${SD_WEBUI_ROOT_PATH}"/models/VAE # ae(335m) OFF
__term_sd_task_pre_model_168 # =====VAE模型===== OFF
__term_sd_task_pre_model_169 get_modelscope_model licyks/sd-vae/master/sd_1.5/vae-ft-ema-560000-ema-pruned.safetensors "${SD_WEBUI_ROOT_PATH}"/models/VAE # VAE模型 vae-ft-ema-560000-ema-pruned(334.6m) OFF
__term_sd_task_pre_model_170 get_modelscope_model licyks/sd-vae/master/sd_1.5/vae-ft-mse-840000-ema-pruned.safetensors "${SD_WEBUI_ROOT_PATH}"/models/VAE # vae-ft-mse-840000-ema-pruned(334.6m) ON
__term_sd_task_pre_model_171 get_modelscope_model licyks/sd-vae/master/sdxl_1.0/sdxl_vae.safetensors "${SD_WEBUI_ROOT_PATH}"/models/VAE # sdxl_vae(334.6m) OFF
__term_sd_task_pre_model_172 get_modelscope_model licyks/sd-vae/master/sdxl_1.0/sdxl_fp16_fix_vae.safetensors "${SD_WEBUI_ROOT_PATH}"/models/VAE # sdxl_fp16_fix_vae(334.6m) OFF
__term_sd_task_pre_model_173 # =====VAE-approx模型===== OFF
__term_sd_task_pre_model_174 get_modelscope_model licyks/sd-vae/master/vae-approx/model.pt "${SD_WEBUI_ROOT_PATH}"/models/VAE-approx # VAE-approx模型 model(0.2m) ON
__term_sd_task_pre_model_175 get_modelscope_model licyks/sd-vae/master/vae-approx/vaeapprox-sdxl.pt "${SD_WEBUI_ROOT_PATH}"/models/VAE-approx # vaeapprox-sdxl(0.2m) ON
__term_sd_task_pre_model_176 get_modelscope_model licyks/sd-vae/master/vae-approx/vaeapprox-sd3.pt "${SD_WEBUI_ROOT_PATH}"/models/VAE-approx # vaeapprox-sd3(0.2m) OFF
__term_sd_task_pre_model_177 # =====放大模型===== OFF
__term_sd_task_pre_model_178 get_modelscope_model licyks/sd-upscaler-models/master/Codeformer/codeformer-v0.1.0.pth "${SD_WEBUI_ROOT_PATH}"/models/Codeformer # codeformer-v0.1.0(376.6m) OFF
__term_sd_task_pre_model_179 get_modelscope_model licyks/sd-upscaler-models/master/DAT/DAT_2_x2.pth "${SD_WEBUI_ROOT_PATH}"/models/DAT # DAT_2_x2(139.7m) OFF
__term_sd_task_pre_model_180 get_modelscope_model licyks/sd-upscaler-models/master/DAT/DAT_2_x3.pth "${SD_WEBUI_ROOT_PATH}"/models/DAT # DAT_2_x3(140.4m) OFF
__term_sd_task_pre_model_181 get_modelscope_model licyks/sd-upscaler-models/master/DAT/DAT_2_x4.pth "${SD_WEBUI_ROOT_PATH}"/models/DAT # DAT_2_x4(140.3m) OFF
__term_sd_task_pre_model_182 get_modelscope_model licyks/sd-upscaler-models/master/DAT/DAT_S_x2.pth "${SD_WEBUI_ROOT_PATH}"/models/DAT # DAT_S_x2(87.7m) OFF
__term_sd_task_pre_model_183 get_modelscope_model licyks/sd-upscaler-models/master/DAT/DAT_S_x3.pth "${SD_WEBUI_ROOT_PATH}"/models/DAT # DAT_S_x3(88.4m) OFF
__term_sd_task_pre_model_184 get_modelscope_model licyks/sd-upscaler-models/master/DAT/DAT_S_x4.pth "${SD_WEBUI_ROOT_PATH}"/models/DAT # DAT_S_x4(88.2m) OFF
__term_sd_task_pre_model_185 get_modelscope_model licyks/sd-upscaler-models/master/DAT/DAT_light_x2.pth "${SD_WEBUI_ROOT_PATH}"/models/DAT # DAT_light_x2(45.7m) OFF
__term_sd_task_pre_model_186 get_modelscope_model licyks/sd-upscaler-models/master/DAT/DAT_light_x3.pth "${SD_WEBUI_ROOT_PATH}"/models/DAT # DAT_light_x3(45.7m) OFF
__term_sd_task_pre_model_187 get_modelscope_model licyks/sd-upscaler-models/master/DAT/DAT_light_x4.pth "${SD_WEBUI_ROOT_PATH}"/models/DAT # DAT_light_x4(45.8m) OFF
__term_sd_task_pre_model_188 get_modelscope_model licyks/sd-upscaler-models/master/DAT/DAT_x2.pth "${SD_WEBUI_ROOT_PATH}"/models/DAT # DAT_x2(154.1m) OFF
__term_sd_task_pre_model_189 get_modelscope_model licyks/sd-upscaler-models/master/DAT/DAT_x3.pth "${SD_WEBUI_ROOT_PATH}"/models/DAT # DAT_x3(154.8m) OFF
__term_sd_task_pre_model_190 get_modelscope_model licyks/sd-upscaler-models/master/DAT/DAT_x4.pth "${SD_WEBUI_ROOT_PATH}"/models/DAT # DAT_x4(154.7m) OFF
__term_sd_task_pre_model_191 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/16xPSNR.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 16xPSNR(67.2m) OFF
__term_sd_task_pre_model_192 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/1x-ITF-SkinDiffDetail-Lite-v1.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 1x-ITF-SkinDiffDetail-Lite-v1(20.1m) OFF
__term_sd_task_pre_model_193 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/1x_NMKD-BrightenRedux_200k.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 1x_NMKD-BrightenRedux_200k(66.6m) OFF
__term_sd_task_pre_model_194 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/1x_NMKD-YandereInpaint_375000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 1x_NMKD-YandereInpaint_375000_G(66.6m) OFF
__term_sd_task_pre_model_195 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/1x_NMKDDetoon_97500_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 1x_NMKDDetoon_97500_G(66.6m) OFF
__term_sd_task_pre_model_196 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/1x_NoiseToner-Poisson-Detailed_108000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 1x_NoiseToner-Poisson-Detailed_108000_G(66.6m) OFF
__term_sd_task_pre_model_197 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/1x_NoiseToner-Uniform-Detailed_100000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 1x_NoiseToner-Uniform-Detailed_100000_G(66.6m) OFF
__term_sd_task_pre_model_198 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x-UltraSharp.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x-UltraSharp(66.9m) OFF
__term_sd_task_pre_model_199 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4xPSNR.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4xPSNR(66.9m) OFF
__term_sd_task_pre_model_200 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_CountryRoads_377000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_CountryRoads_377000_G(66.9m) OFF
__term_sd_task_pre_model_201 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_Fatality_Comix_260000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_Fatality_Comix_260000_G(66.9m) OFF
__term_sd_task_pre_model_202 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_NMKD-Siax_200k.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_NMKD-Siax_200k(66.9m) OFF
__term_sd_task_pre_model_203 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_NMKD-Superscale-Artisoftject_210000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_NMKD-Superscale-Artisoftject_210000_G(66.9m) OFF
__term_sd_task_pre_model_204 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_NMKD-Superscale-SP_178000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_NMKD-Superscale-SP_178000_G(66.9m) ON
__term_sd_task_pre_model_205 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_NMKD-UltraYandere-Lite_280k.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_NMKD-UltraYandere-Lite_280k(20.1m) OFF
__term_sd_task_pre_model_206 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_NMKD-UltraYandere_300k.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_NMKD-UltraYandere_300k(66.9m) OFF
__term_sd_task_pre_model_207 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_NMKD-YandereNeoXL_200k.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_NMKD-YandereNeoXL_200k(66.9m) OFF
__term_sd_task_pre_model_208 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_NMKDSuperscale_Artisoft_120000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_NMKDSuperscale_Artisoft_120000_G(67.1m) OFF
__term_sd_task_pre_model_209 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_NickelbackFS_72000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_NickelbackFS_72000_G(67.1m) OFF
__term_sd_task_pre_model_210 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_Nickelback_70000G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_Nickelback_70000G(66.9m) OFF
__term_sd_task_pre_model_211 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_RealisticRescaler_100000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_RealisticRescaler_100000_G(134.1m) OFF
__term_sd_task_pre_model_212 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_Valar_v1.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_Valar_v1(67.5m) OFF
__term_sd_task_pre_model_213 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_fatal_Anime_500000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_fatal_Anime_500000_G(66.9m) OFF
__term_sd_task_pre_model_214 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/4x_foolhardy_Remacri.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_foolhardy_Remacri(67m) OFF
__term_sd_task_pre_model_215 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/8xPSNR.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 8xPSNR(67.1m) OFF
__term_sd_task_pre_model_216 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/8x_NMKD-Superscale_150000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 8x_NMKD-Superscale_150000_G(67.1m) OFF
__term_sd_task_pre_model_217 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/8x_NMKD-Typescale_175k.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 8x_NMKD-Typescale_175k(67.1m) OFF
__term_sd_task_pre_model_218 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/A_ESRGAN_Single.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # A_ESRGAN_Single(134.1m) OFF
__term_sd_task_pre_model_219 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/BSRGAN.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # BSRGAN(67.1m) OFF
__term_sd_task_pre_model_220 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/BSRGANx2.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # BSRGANx2(66.8m) OFF
__term_sd_task_pre_model_221 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/BSRNet.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # BSRNet(67.1m) OFF
__term_sd_task_pre_model_222 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/ESRGAN_4x.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # ESRGAN_4x(66.9m) OFF
__term_sd_task_pre_model_223 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/LADDIER1_282500_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # LADDIER1_282500_G(66.9m) OFF
__term_sd_task_pre_model_224 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/UniversalUpscaler/4x_UniversalUpscalerV2-Neutral_115000_swaG.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_UniversalUpscalerV2-Neutral_115000_swaG(66.9m) OFF
__term_sd_task_pre_model_225 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/UniversalUpscaler/4x_UniversalUpscalerV2-Sharp_101000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_UniversalUpscalerV2-Sharp_101000_G(66.9m) OFF
__term_sd_task_pre_model_226 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/UniversalUpscaler/4x_UniversalUpscalerV2-Sharper_103000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_UniversalUpscalerV2-Sharper_103000_G(66.9m) OFF
__term_sd_task_pre_model_227 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/UniversalUpscaler/Legacy/4x_UniversalUpscaler-Detailed_155000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_UniversalUpscaler-Detailed_155000_G(66.9m) OFF
__term_sd_task_pre_model_228 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/UniversalUpscaler/Legacy/4x_UniversalUpscaler-Soft_190000_G.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # 4x_UniversalUpscaler-Soft_190000_G(66.9m) OFF
__term_sd_task_pre_model_229 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/WaifuGAN_v3_30000.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # WaifuGAN_v3_30000(66.9m) OFF
__term_sd_task_pre_model_230 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/lollypop.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # lollypop(66.9m) OFF
__term_sd_task_pre_model_231 get_modelscope_model licyks/sd-upscaler-models/master/ESRGAN/sudo_rife4_269.662_testV1_scale1.pth "${SD_WEBUI_ROOT_PATH}"/models/ESRGAN # sudo_rife4_269.662_testV1_scale1(33.7m) OFF
__term_sd_task_pre_model_232 get_modelscope_model licyks/sd-upscaler-models/master/GFPGAN/GFPGANv1.3.pth "${SD_WEBUI_ROOT_PATH}"/models/GFPGAN # GFPGANv1.3(348.6m) OFF
__term_sd_task_pre_model_233 get_modelscope_model licyks/sd-upscaler-models/master/GFPGAN/GFPGANv1.4.pth "${SD_WEBUI_ROOT_PATH}"/models/GFPGAN # GFPGANv1.4(348.6m) OFF
__term_sd_task_pre_model_234 get_modelscope_model licyks/sd-upscaler-models/master/GFPGAN/detection_Resnet50_Final.pth "${SD_WEBUI_ROOT_PATH}"/models/GFPGAN # detection_Resnet50_Final(109.5m) OFF
__term_sd_task_pre_model_235 get_modelscope_model licyks/sd-upscaler-models/master/GFPGAN/parsing_bisenet.pth "${SD_WEBUI_ROOT_PATH}"/models/GFPGAN # parsing_bisenet(12.2m) OFF
__term_sd_task_pre_model_236 get_modelscope_model licyks/sd-upscaler-models/master/GFPGAN/parsing_parsenet.pth "${SD_WEBUI_ROOT_PATH}"/models/GFPGAN # parsing_parsenet(85.3m) OFF
__term_sd_task_pre_model_237 get_modelscope_model licyks/sd-upscaler-models/master/RealESRGAN/RealESRGAN_x4plus.pth "${SD_WEBUI_ROOT_PATH}"/models/RealESRGAN # RealESRGAN_x4plus(67m) ON
__term_sd_task_pre_model_238 get_modelscope_model licyks/sd-upscaler-models/master/RealESRGAN/RealESRGAN_x4plus_anime_6B.pth "${SD_WEBUI_ROOT_PATH}"/models/RealESRGAN # RealESRGAN_x4plus_anime_6B(17.9m) ON
__term_sd_task_pre_model_239 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/001_classicalSR_DF2K_s64w8_SwinIR-M_x2.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # 001_classicalSR_DF2K_s64w8_SwinIR-M_x2(67.2m) OFF
__term_sd_task_pre_model_240 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/001_classicalSR_DF2K_s64w8_SwinIR-M_x3.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # 001_classicalSR_DF2K_s64w8_SwinIR-M_x3(68m) OFF
__term_sd_task_pre_model_241 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/001_classicalSR_DF2K_s64w8_SwinIR-M_x4.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # 001_classicalSR_DF2K_s64w8_SwinIR-M_x4(67.8m) OFF
__term_sd_task_pre_model_242 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/001_classicalSR_DF2K_s64w8_SwinIR-M_x8.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # 001_classicalSR_DF2K_s64w8_SwinIR-M_x8(68.4m) OFF
__term_sd_task_pre_model_243 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/001_classicalSR_DIV2K_s48w8_SwinIR-M_x2.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # 001_classicalSR_DIV2K_s48w8_SwinIR-M_x2(59m) OFF
__term_sd_task_pre_model_244 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/001_classicalSR_DIV2K_s48w8_SwinIR-M_x3.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # 001_classicalSR_DIV2K_s48w8_SwinIR-M_x3(59.7m) OFF
__term_sd_task_pre_model_245 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/001_classicalSR_DIV2K_s48w8_SwinIR-M_x4.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # 001_classicalSR_DIV2K_s48w8_SwinIR-M_x4(59.6m) OFF
__term_sd_task_pre_model_246 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/001_classicalSR_DIV2K_s48w8_SwinIR-M_x8.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # 001_classicalSR_DIV2K_s48w8_SwinIR-M_x8(60.2m) OFF
__term_sd_task_pre_model_247 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/Swin2SR_ClassicalSR_X2_64.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # Swin2SR_ClassicalSR_X2_64(68.7m) OFF
__term_sd_task_pre_model_248 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/Swin2SR_ClassicalSR_X4_64.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # Swin2SR_ClassicalSR_X4_64(69.3m) OFF
__term_sd_task_pre_model_249 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/Swin2SR_CompressedSR_X4_48.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # Swin2SR_CompressedSR_X4_48(61.1m) OFF
__term_sd_task_pre_model_250 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/Swin2SR_RealworldSR_X4_64_BSRGAN_PSNR.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # Swin2SR_RealworldSR_X4_64_BSRGAN_PSNR(68.6m) OFF
__term_sd_task_pre_model_251 get_modelscope_model licyks/sd-upscaler-models/master/SwinIR/SwinIR_4x.pth "${SD_WEBUI_ROOT_PATH}"/models/SwinIR # SwinIR_4x(142.4m) OFF
__term_sd_task_pre_model_252 # =====图生图反推Tag模型===== OFF
__term_sd_task_pre_model_253 get_modelscope_model licyks/sd-upscaler-models/master/BLIP/model_base_caption_capfilt_large.pth "${SD_WEBUI_ROOT_PATH}"/models/BLIP # BLIP模型 model_base_caption_capfilt_large(896m) OFF
__term_sd_task_pre_model_254 get_modelscope_model licyks/sd-upscaler-models/master/torch_deepdanbooru/model-resnet_custom_v3.pt "${SD_WEBUI_ROOT_PATH}"/models/torch_deepdanbooru # deepdanbooru模型 model-resnet_custom_v3(644.1m) OFF
__term_sd_task_pre_model_255 # =====Embedding模型===== OFF
__term_sd_task_pre_model_256 get_modelscope_model licyks/sd-embeddings/master/sd_1.5/EasyNegativeV2.safetensors "${SD_WEBUI_ROOT_PATH}"/embeddings # embeddings模型 EasyNegativeV2(0.1m) ON
__term_sd_task_pre_model_257 get_modelscope_model licyks/sd-embeddings/master/sd_1.5/bad-artist-anime.pt "${SD_WEBUI_ROOT_PATH}"/embeddings # bad-artist-anime(0.1m) ON
__term_sd_task_pre_model_258 get_modelscope_model licyks/sd-embeddings/master/sd_1.5/bad-artist.pt "${SD_WEBUI_ROOT_PATH}"/embeddings # bad-artist(0.1m) ON
__term_sd_task_pre_model_259 get_modelscope_model licyks/sd-embeddings/master/sd_1.5/bad-hands-5.pt "${SD_WEBUI_ROOT_PATH}"/embeddings # bad-hands-5(0.1m) ON
__term_sd_task_pre_model_260 get_modelscope_model licyks/sd-embeddings/master/sd_1.5/bad-image-v2-39000.pt "${SD_WEBUI_ROOT_PATH}"/embeddings # bad-image-v2-39000(0.1m) ON
__term_sd_task_pre_model_261 get_modelscope_model licyks/sd-embeddings/master/sd_1.5/bad_prompt_version2.pt "${SD_WEBUI_ROOT_PATH}"/embeddings # bad_prompt_version2(0.1m) ON
__term_sd_task_pre_model_262 get_modelscope_model licyks/sd-embeddings/master/sd_1.5/ng_deepnegative_v1_75t.pt "${SD_WEBUI_ROOT_PATH}"/embeddings # ng_deepnegative_v1_75t(0.1m) ON
__term_sd_task_pre_model_263 get_modelscope_model licyks/sd-embeddings/master/sd_1.5/verybadimagenegative_v1.3.pt "${SD_WEBUI_ROOT_PATH}"/embeddings # verybadimagenegative_v1.3(0.1m) ON
