__term_sd_task_pre_model_1 # =====SDXL大模型===== OFF
__term_sd_task_pre_model_2 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sd_xl_base_1.0_0.9vae.safetensors "${FOOOCUS_PATH}"/models/checkpoints # sd_xl_base_1.0_0.9vae(6.94g) OFF
__term_sd_task_pre_model_3 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sd_xl_refiner_1.0_0.9vae.safetensors "${FOOOCUS_PATH}"/models/checkpoints # sd_xl_refiner_1.0_0.9vae(6.94g) OFF
__term_sd_task_pre_model_4 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sd_xl_turbo_1.0_fp16.safetensors "${FOOOCUS_PATH}"/models/checkpoints # sd_xl_turbo_1.0_fp16(6.94g) OFF
__term_sd_task_pre_model_5 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animagine-xl-3.0-base.safetensors "${FOOOCUS_PATH}"/models/checkpoints # animagine-xl-3.0-base(6.94g) OFF
__term_sd_task_pre_model_6 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animagine-xl-3.0.safetensors "${FOOOCUS_PATH}"/models/checkpoints # animagine-xl-3.0(6.94g) OFF
__term_sd_task_pre_model_7 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animagine-xl-3.1.safetensors "${FOOOCUS_PATH}"/models/checkpoints # animagine-xl-3.1(6.94g) OFF
__term_sd_task_pre_model_8 get_modelscope_model licyks/sd-model/master/sdxl_1.0/holodayo-xl-2.1.safetensors "${FOOOCUS_PATH}"/models/checkpoints # holodayo-xl-2.1(6.94g) OFF
__term_sd_task_pre_model_9 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kivotos-xl-2.0.safetensors "${FOOOCUS_PATH}"/models/checkpoints # kivotos-xl-2.0(6.94g) OFF
__term_sd_task_pre_model_10 get_modelscope_model licyks/sd-model/master/sdxl_1.0/clandestine-xl-1.0.safetensors "${FOOOCUS_PATH}"/models/checkpoints # clandestine-xl-1.0(6.94g) OFF
__term_sd_task_pre_model_11 get_modelscope_model licyks/sd-model/master/sdxl_1.0/UrangDiffusion-1.1.safetensors "${FOOOCUS_PATH}"/models/checkpoints # UrangDiffusion-1.1(6.94g) OFF
__term_sd_task_pre_model_12 get_modelscope_model licyks/sd-model/master/sdxl_1.0/RaeDiffusion-XL-v2.safetensors "${FOOOCUS_PATH}"/models/checkpoints # RaeDiffusion-XL-v2(6.94g) OFF
__term_sd_task_pre_model_13 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sd_xl_anime_V52.safetensors "${FOOOCUS_PATH}"/models/checkpoints # sd_xl_anime_V52(6.94g) OFF
__term_sd_task_pre_model_14 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kohaku-xl-delta-rev1.safetensors "${FOOOCUS_PATH}"/models/checkpoints # kohaku-xl-delta-rev1(6.94g) OFF
__term_sd_task_pre_model_15 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kohakuXLEpsilon_rev1.safetensors "${FOOOCUS_PATH}"/models/checkpoints # kohakuXLEpsilon_rev1(6.94g) OFF
__term_sd_task_pre_model_16 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kohaku-xl-epsilon-rev2.safetensors "${FOOOCUS_PATH}"/models/checkpoints # kohaku-xl-epsilon-rev2(6.94g) OFF
__term_sd_task_pre_model_17 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kohaku-xl-epsilon-rev3.safetensors "${FOOOCUS_PATH}"/models/checkpoints # kohaku-xl-epsilon-rev3(6.94g) OFF
__term_sd_task_pre_model_18 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kohaku-xl-zeta.safetensors "${FOOOCUS_PATH}"/models/checkpoints # kohaku-xl-zeta(6.94g) OFF
__term_sd_task_pre_model_19 get_modelscope_model licyks/sd-model/master/sdxl_1.0/starryXLV52_v52.safetensors "${FOOOCUS_PATH}"/models/checkpoints # starryXLV52_v52(6.94g) OFF
__term_sd_task_pre_model_20 get_modelscope_model licyks/sd-model/master/sdxl_1.0/heartOfAppleXL_v20.safetensors "${FOOOCUS_PATH}"/models/checkpoints # heartOfAppleXL_v20(6.94g) OFF
__term_sd_task_pre_model_21 get_modelscope_model licyks/sd-model/master/sdxl_1.0/heartOfAppleXL_v30.safetensors "${FOOOCUS_PATH}"/models/checkpoints # heartOfAppleXL_v30(6.94g) OFF
__term_sd_task_pre_model_22 get_modelscope_model licyks/sd-model/master/sdxl_1.0/baxlBartstylexlBlueArchiveFlatCelluloid_xlv1.safetensors "${FOOOCUS_PATH}"/models/checkpoints # baxlBartstylexlBlueArchiveFlatCelluloid_xlv1(6.94g) OFF
__term_sd_task_pre_model_23 get_modelscope_model licyks/sd-model/master/sdxl_1.0/baxlBlueArchiveFlatCelluloidStyle_xlv3.safetensors "${FOOOCUS_PATH}"/models/checkpoints # baxlBlueArchiveFlatCelluloidStyle_xlv3(6.94g) OFF
__term_sd_task_pre_model_24 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sanaexlAnimeV10_v10.safetensors "${FOOOCUS_PATH}"/models/checkpoints # sanaexlAnimeV10_v10(6.94g) OFF
__term_sd_task_pre_model_25 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sanaexlAnimeV10_v11.safetensors "${FOOOCUS_PATH}"/models/checkpoints # sanaexlAnimeV10_v11(6.94g) OFF
__term_sd_task_pre_model_26 get_modelscope_model licyks/sd-model/master/sdxl_1.0/SanaeXL-Anime-v1.2-aesthetic.safetensors "${FOOOCUS_PATH}"/models/checkpoints # SanaeXL-Anime-v1.2-aesthetic(6.94g) OFF
__term_sd_task_pre_model_27 get_modelscope_model licyks/sd-model/master/sdxl_1.0/SanaeXL-Anime-v1.3-aesthetic.safetensors "${FOOOCUS_PATH}"/models/checkpoints # SanaeXL-Anime-v1.3-aesthetic(6.94g) OFF
__term_sd_task_pre_model_28 get_modelscope_model licyks/sd-model/master/sdxl_1.0/Illustrious-XL-v0.1.safetensors "${FOOOCUS_PATH}"/models/checkpoints # Illustrious-XL-v0.1(6.94g) ON
__term_sd_task_pre_model_29 get_modelscope_model licyks/sd-model/master/sdxl_1.0/Illustrious-XL-v0.1-GUIDED.safetensors "${FOOOCUS_PATH}"/models/checkpoints # Illustrious-XL-v0.1-GUIDED(6.94g) OFF
__term_sd_task_pre_model_30 get_modelscope_model licyks/sd-model/master/sdxl_1.0/jruTheJourneyRemains_v25XL.safetensors "${FOOOCUS_PATH}"/models/checkpoints # jruTheJourneyRemains_v25XL(6.94g) OFF
__term_sd_task_pre_model_31 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_earlyAccessVersion.safetensors "${FOOOCUS_PATH}"/models/checkpoints # noobaiXLNAIXL_earlyAccessVersion(6.94g) OFF
__term_sd_task_pre_model_32 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_vPredTestVersion.safetensors "${FOOOCUS_PATH}"/models/checkpoints # noobaiXLNAIXL_vPredTestVersion(6.94g) OFF
__term_sd_task_pre_model_33 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_epsilonPred05Version.safetensors "${FOOOCUS_PATH}"/models/checkpoints # noobaiXLNAIXL_epsilonPred05Version(6.94g) OFF
__term_sd_task_pre_model_34 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_epsilonPred075.safetensors "${FOOOCUS_PATH}"/models/checkpoints # noobaiXLNAIXL_epsilonPred075(6.94g) OFF
__term_sd_task_pre_model_35 get_modelscope_model licyks/sd-model/master/sdxl_1.0/noobaiXLNAIXL_epsilonPred077.safetensors "${FOOOCUS_PATH}"/models/checkpoints # noobaiXLNAIXL_epsilonPred077(6.94g) OFF
__term_sd_task_pre_model_36 get_modelscope_model licyks/sd-model/master/sdxl_1.0/ponyDiffusionV6XL_v6StartWithThisOne.safetensors "${FOOOCUS_PATH}"/models/checkpoints # ponyDiffusionV6XL_v6(6.94g) OFF
__term_sd_task_pre_model_37 get_modelscope_model licyks/sd-model/master/sdxl_1.0/pdForAnime_v20.safetensors "${FOOOCUS_PATH}"/models/checkpoints # pdForAnime_v20(7.11g) OFF
__term_sd_task_pre_model_38 get_modelscope_model licyks/sd-model/master/sdxl_1.0/tPonynai3_v51WeightOptimized.safetensors "${FOOOCUS_PATH}"/models/checkpoints # tPonynai3_v51WeightOptimized(6.94g) OFF
__term_sd_task_pre_model_39 get_modelscope_model licyks/sd-model/master/sdxl_1.0/omegaPonyXLAnime_v20.safetensors "${FOOOCUS_PATH}"/models/checkpoints # omegaPonyXLAnime_v20(6.94g) OFF
__term_sd_task_pre_model_40 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animeIllustDiffusion_v061.safetensors "${FOOOCUS_PATH}"/models/checkpoints # animeIllustDiffusion_v061(6.94g) OFF
__term_sd_task_pre_model_41 get_modelscope_model licyks/sd-model/master/sdxl_1.0/artiwaifuDiffusion_v10.safetensors "${FOOOCUS_PATH}"/models/checkpoints # artiwaifuDiffusion_v10(6.94g) OFF
__term_sd_task_pre_model_42 get_modelscope_model licyks/sd-model/master/sdxl_1.0/artiwaifu-diffusion-v2.safetensors "${FOOOCUS_PATH}"/models/checkpoints # artiwaifu-diffusion-v2(6.94g) OFF
__term_sd_task_pre_model_43 get_modelscope_model licyks/sd-model/master/sdxl_1.0/AnythingXL_xl.safetensors "${FOOOCUS_PATH}"/models/checkpoints # AnythingXL_xl(6.94g) OFF
__term_sd_task_pre_model_44 get_modelscope_model licyks/sd-model/master/sdxl_1.0/abyssorangeXLElse_v10.safetensors "${FOOOCUS_PATH}"/models/checkpoints # abyssorangeXLElse_v10(6.94g) OFF
__term_sd_task_pre_model_45 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animaPencilXL_v200.safetensors "${FOOOCUS_PATH}"/models/checkpoints # animaPencilXL_v200(6.94g) OFF
__term_sd_task_pre_model_46 get_modelscope_model licyks/sd-model/master/sdxl_1.0/bluePencilXL_v401.safetensors "${FOOOCUS_PATH}"/models/checkpoints # bluePencilXL_v401(6.94g) OFF
__term_sd_task_pre_model_47 get_modelscope_model licyks/sd-model/master/sdxl_1.0/nekorayxl_v06W3.safetensors "${FOOOCUS_PATH}"/models/checkpoints # nekorayxl_v06W3(6.94g) OFF
__term_sd_task_pre_model_48 get_modelscope_model licyks/sd-model/master/sdxl_1.0/CounterfeitXL-V1.0.safetensors "${FOOOCUS_PATH}"/models/checkpoints # CounterfeitXL-V1.0(6.94g) OFF
__term_sd_task_pre_model_49 # =====其他模型===== OFF
__term_sd_task_pre_model_50 get_modelscope_model licyks/sd-lora/master/sdxl/sd_xl_offset_example-lora_1.0.safetensors "${FOOOCUS_PATH}"/models/loras # sd_xl_offset_example-lora_1.0(49.6m) ON
__term_sd_task_pre_model_51 get_modelscope_model licyks/fooocus-model/master/inpaint/inpaint.fooocus.patch "${FOOOCUS_PATH}"/models/inpaint # inpaint.fooocus(1.32g) OFF
__term_sd_task_pre_model_52 get_modelscope_model licyks/fooocus-model/master/inpaint/inpaint_v26.fooocus.patch "${FOOOCUS_PATH}"/models/inpaint # inpaint_v26.fooocus(1.32g) ON
__term_sd_task_pre_model_53 get_modelscope_model licyks/fooocus-model/master/inpaint/fooocus_inpaint_head.pth "${FOOOCUS_PATH}"/models/inpaint # fooocus_inpaint_head(0.05m) ON
__term_sd_task_pre_model_54 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/pytorch_model.bin "${FOOOCUS_PATH}"/models/prompt_expansion/fooocus_expansion # fooocus_expansion(351.2m) ON
__term_sd_task_pre_model_55 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/config.json "${FOOOCUS_PATH}"/models/prompt_expansion/fooocus_expansion # fooocus_expansion(0.1m) ON
__term_sd_task_pre_model_56 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/merges.txt "${FOOOCUS_PATH}"/models/prompt_expansion/fooocus_expansion # fooocus_expansion(0.1m) ON
__term_sd_task_pre_model_57 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/special_tokens_map.json "${FOOOCUS_PATH}"/models/prompt_expansion/fooocus_expansion # fooocus_expansion(0.1m) ON
__term_sd_task_pre_model_58 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/tokenizer.json "${FOOOCUS_PATH}"/models/prompt_expansion/fooocus_expansion # fooocus_expansion(2.1m) ON
__term_sd_task_pre_model_59 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/tokenizer_config.json "${FOOOCUS_PATH}"/models/prompt_expansion/fooocus_expansion # fooocus_expansion(0.1m) ON
__term_sd_task_pre_model_60 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/vocab.json "${FOOOCUS_PATH}"/models/prompt_expansion/fooocus_expansion # fooocus_expansion(0.1m) ON
__term_sd_task_pre_model_61 get_modelscope_model licyks/fooocus-model/master/upscale_models/fooocus_upscaler_s409985e5.bin "${FOOOCUS_PATH}"/models/upscale_models # fooocus_upscaler_s409985e5(33.6m) ON
__term_sd_task_pre_model_62 get_modelscope_model licyks/fooocus-model/master/vae_approx/vaeapp_sd15.pth "${FOOOCUS_PATH}"/models/vae_approx # vaeapp_sd15(0.2m) ON
__term_sd_task_pre_model_63 get_modelscope_model licyks/fooocus-model/master/vae_approx/xl-to-v1_interposer-v3.1.safetensors "${FOOOCUS_PATH}"/models/vae_approx # xl-to-v1_interposer-v3.1(6.5m) OFF
__term_sd_task_pre_model_64 get_modelscope_model licyks/fooocus-model/master/vae_approx/xl-to-v1_interposer-v4.0.safetensors "${FOOOCUS_PATH}"/models/vae_approx # xl-to-v1_interposer-v4.0(5.6m) ON
__term_sd_task_pre_model_65 get_modelscope_model licyks/fooocus-model/master/vae_approx/xlvaeapp.pth "${FOOOCUS_PATH}"/models/vae_approx # xlvaeapp(0.2m) ON
__term_sd_task_pre_model_66 get_modelscope_model licyks/fooocus-model/master/loras/sdxl_lcm_lora.safetensors "${FOOOCUS_PATH}"/models/loras # sdxl_lcm_lora(393.8m) ON
__term_sd_task_pre_model_67 get_modelscope_model licyks/fooocus-model/master/controlnet/control-lora-canny-rank128.safetensors "${FOOOCUS_PATH}"/models/controlnet # control-lora-canny-rank128(395.7m) ON
__term_sd_task_pre_model_68 get_modelscope_model licyks/fooocus-model/master/controlnet/fooocus_ip_negative.safetensors "${FOOOCUS_PATH}"/models/controlnet # fooocus_ip_negative(0.01m) ON
__term_sd_task_pre_model_69 get_modelscope_model licyks/fooocus-model/master/controlnet/fooocus_xl_cpds_128.safetensors "${FOOOCUS_PATH}"/models/controlnet # fooocus_xl_cpds_128(395.7m) ON
__term_sd_task_pre_model_70 get_modelscope_model licyks/fooocus-model/master/controlnet/ip-adapter-plus_sdxl_vit-h.bin "${FOOOCUS_PATH}"/models/controlnet # ip-adapter-plus_sdxl_vit-h(1.01g) ON
__term_sd_task_pre_model_71 get_modelscope_model licyks/fooocus-model/master/controlnet/detection_Resnet50_Final.pth "${FOOOCUS_PATH}"/models/controlnet # detection_Resnet50_Final(103.5m) ON
__term_sd_task_pre_model_72 get_modelscope_model licyks/fooocus-model/master/controlnet/ip-adapter-plus-face_sdxl_vit-h.bin "${FOOOCUS_PATH}"/models/controlnet # ip-adapter-plus-face_sdxl_vit-h(1.01g) ON
__term_sd_task_pre_model_73 get_modelscope_model licyks/fooocus-model/master/controlnet/parsing_parsenet.pth "${FOOOCUS_PATH}"/models/controlnet # parsing_parsenet(85.3m) ON
