__term_sd_task_pre_model_1 # =====SDXL大模型===== OFF
__term_sd_task_pre_model_2 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sd_xl_base_1.0_0.9vae.safetensors "$fooocus_path"/models/checkpoints # sd_xl_base_1.0_0.9vae ON
__term_sd_task_pre_model_3 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sd_xl_refiner_1.0_0.9vae.safetensors "$fooocus_path"/models/checkpoints # sd_xl_refiner_1.0_0.9vae ON
__term_sd_task_pre_model_4 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animagine-xl-3.0.safetensors "$fooocus_path"/models/checkpoints # animagine-xl-3.0 OFF
__term_sd_task_pre_model_5 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/AnythingXL_xl.safetensors "$fooocus_path"/models/checkpoints # AnythingXL_xl OFF
__term_sd_task_pre_model_6 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/abyssorangeXLElse_v10.safetensors "$fooocus_path"/models/checkpoints # abyssorangeXLElse_v10 OFF
__term_sd_task_pre_model_7 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animaPencilXL_v200.safetensors "$fooocus_path"/models/checkpoints # animaPencilXL_v200 OFF
__term_sd_task_pre_model_8 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animagine-xl-3.1.safetensors "$fooocus_path"/models/checkpoints # animagine-xl-3.1 OFF
__term_sd_task_pre_model_9 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/heartOfAppleXL_v20.safetensors "$fooocus_path"/models/checkpoints # heartOfAppleXL_v20 OFF
__term_sd_task_pre_model_10 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/baxlBartstylexlBlueArchiveFlatCelluloid_xlv1.safetensors "$fooocus_path"/models/checkpoints # baxlBartstylexlBlueArchiveFlatCelluloid_xlv1 OFF
__term_sd_task_pre_model_11 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/kohaku-xl-delta-rev1.safetensors "$fooocus_path"/models/checkpoints # kohaku-xl-delta-rev1 OFF
__term_sd_task_pre_model_12 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/nekorayxl_v06W3.safetensors "$fooocus_path"/models/checkpoints # nekorayxl_v06W3 OFF
__term_sd_task_pre_model_13 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/CounterfeitXL-V1.0.safetensors "$fooocus_path"/models/checkpoints # CounterfeitXL-V1.0 OFF
__term_sd_task_pre_model_14 # =====其他模型===== OFF
__term_sd_task_pre_model_15 aria2_download https://huggingface.co/licyk/sd-lora/resolve/main/sdxl/sd_xl_offset_example-lora_1.0.safetensors "$fooocus_path"/models/loras # sd_xl_offset_example-lora_1.0 ON
__term_sd_task_pre_model_16 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/inpaint/inpaint.fooocus.patch "$fooocus_path"/models/inpaint # inpaint.fooocus ON
__term_sd_task_pre_model_17 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/inpaint/fooocus_inpaint_head.pth "$fooocus_path"/models/inpaint # fooocus_inpaint_head ON
__term_sd_task_pre_model_18 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/pytorch_model.bin "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_19 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/config.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_20 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/merges.txt "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_21 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/special_tokens_map.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_22 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/tokenizer.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_23 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/tokenizer_config.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_24 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/vocab.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_25 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/upscale_models/fooocus_upscaler_s409985e5.bin "$fooocus_path"/models/upscale_models # fooocus_upscaler_s409985e5 ON
__term_sd_task_pre_model_26 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/vae_approx/vaeapp_sd15.pth "$fooocus_path"/models/vae_approx # vaeapp_sd15 ON
__term_sd_task_pre_model_27 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/vae_approx/xl-to-v1_interposer-v3.1.safetensors "$fooocus_path"/models/vae_approx # xl-to-v1_interposer-v3.1 ON
__term_sd_task_pre_model_28 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/vae_approx/xlvaeapp.pth "$fooocus_path"/models/vae_approx # xlvaeapp ON
__term_sd_task_pre_model_29 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/loras/sdxl_lcm_lora.safetensors "$fooocus_path"/models/loras # sdxl_lcm_lora ON
__term_sd_task_pre_model_30 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/control-lora-canny-rank128.safetensors "$fooocus_path"/models/controlnet # control-lora-canny-rank128 ON
__term_sd_task_pre_model_31 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/fooocus_ip_negative.safetensors "$fooocus_path"/models/controlnet # fooocus_ip_negative ON
__term_sd_task_pre_model_32 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/fooocus_xl_cpds_128.safetensors "$fooocus_path"/models/controlnet # fooocus_xl_cpds_128 ON
__term_sd_task_pre_model_33 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/ip-adapter-plus_sdxl_vit-h.bin "$fooocus_path"/models/controlnet # ip-adapter-plus_sdxl_vit-h ON
__term_sd_task_pre_model_34 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/detection_Resnet50_Final.pth "$fooocus_path"/models/controlnet # detection_Resnet50_Final ON
__term_sd_task_pre_model_35 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/ip-adapter-plus-face_sdxl_vit-h.bin "$fooocus_path"/models/controlnet # ip-adapter-plus-face_sdxl_vit-h ON
__term_sd_task_pre_model_36 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/parsing_parsenet.pth "$fooocus_path"/models/controlnet # parsing_parsenet ON
