__term_sd_task_pre_model_1 # =====SDXL大模型===== OFF
__term_sd_task_pre_model_2 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sd_xl_base_1.0_0.9vae.safetensors "$fooocus_path"/models/checkpoints # sd_xl_base_1.0_0.9vae OFF
__term_sd_task_pre_model_3 get_modelscope_model licyks/sd-model/master/sdxl_1.0/sd_xl_refiner_1.0_0.9vae.safetensors "$fooocus_path"/models/checkpoints # sd_xl_refiner_1.0_0.9vae OFF
__term_sd_task_pre_model_4 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animagine-xl-3.0.safetensors "$fooocus_path"/models/checkpoints # animagine-xl-3.0 ON
__term_sd_task_pre_model_5 get_modelscope_model licyks/sd-model/master/sdxl_1.0/AnythingXL_xl.safetensors "$fooocus_path"/models/checkpoints # AnythingXL_xl OFF
__term_sd_task_pre_model_6 get_modelscope_model licyks/sd-model/master/sdxl_1.0/abyssorangeXLElse_v10.safetensors "$fooocus_path"/models/checkpoints # abyssorangeXLElse_v10 OFF
__term_sd_task_pre_model_7 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animaPencilXL_v200.safetensors "$fooocus_path"/models/checkpoints # animaPencilXL_v200 OFF
__term_sd_task_pre_model_8 get_modelscope_model licyks/sd-model/master/sdxl_1.0/animagine-xl-3.1.safetensors "$fooocus_path"/models/checkpoints # animagine-xl-3.1 OFF
__term_sd_task_pre_model_9 get_modelscope_model licyks/sd-model/master/sdxl_1.0/heartOfAppleXL_v20.safetensors "$fooocus_path"/models/checkpoints # heartOfAppleXL_v20 OFF
__term_sd_task_pre_model_10 get_modelscope_model licyks/sd-model/master/sdxl_1.0/baxlBartstylexlBlueArchiveFlatCelluloid_xlv1.safetensors "$fooocus_path"/models/checkpoints # baxlBartstylexlBlueArchiveFlatCelluloid_xlv1 OFF
__term_sd_task_pre_model_11 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kohaku-xl-delta-rev1.safetensors "$fooocus_path"/models/checkpoints # kohaku-xl-delta-rev1 OFF
__term_sd_task_pre_model_12 get_modelscope_model licyks/sd-model/master/sdxl_1.0/kohakuXLEpsilon_rev1.safetensors "$fooocus_path"/models/checkpoints # kohakuXLEpsilon_rev1 OFF
__term_sd_task_pre_model_13 get_modelscope_model licyks/sd-model/master/sdxl_1.0/nekorayxl_v06W3.safetensors "$fooocus_path"/models/checkpoints # nekorayxl_v06W3 OFF
__term_sd_task_pre_model_14 get_modelscope_model licyks/sd-model/master/sdxl_1.0/CounterfeitXL-V1.0.safetensors "$fooocus_path"/models/checkpoints # CounterfeitXL-V1.0 OFF
__term_sd_task_pre_model_15 get_modelscope_model licyks/sd-model/master/sdxl_1.0/ponyDiffusionV6XL_v6StartWithThisOne.safetensors "$fooocus_path"/models/checkpoints # ponyDiffusionV6XL_v6 OFF
__term_sd_task_pre_model_16 get_modelscope_model licyks/sd-model/master/sdxl_1.0/starryXLV52_v52.safetensors "$fooocus_path"/models/checkpoints # starryXLV52_v52 OFF
__term_sd_task_pre_model_17 # =====其他模型===== OFF
__term_sd_task_pre_model_18 get_modelscope_model licyks/fooocus-model/master/loras/sd_xl_offset_example-lora_1.0.safetensors "$fooocus_path"/models/loras # sd_xl_offset_example-lora_1.0 ON
__term_sd_task_pre_model_19 get_modelscope_model licyks/fooocus-model/master/inpaint/inpaint.fooocus.patch "$fooocus_path"/models/inpaint # inpaint.fooocus ON
__term_sd_task_pre_model_20 get_modelscope_model licyks/fooocus-model/master/inpaint/fooocus_inpaint_head.pth "$fooocus_path"/models/inpaint # fooocus_inpaint_head ON
__term_sd_task_pre_model_21 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/pytorch_model.bin "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_22 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/config.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_23 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/merges.txt "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_24 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/special_tokens_map.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_25 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/tokenizer.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_26 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/tokenizer_config.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_27 get_modelscope_model licyks/fooocus-model/master/prompt_expansion/fooocus_expansion/vocab.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_28 get_modelscope_model licyks/fooocus-model/master/upscale_models/fooocus_upscaler_s409985e5.bin "$fooocus_path"/models/upscale_models # fooocus_upscaler_s409985e5 ON
__term_sd_task_pre_model_29 get_modelscope_model licyks/fooocus-model/master/vae_approx/vaeapp_sd15.pth "$fooocus_path"/models/vae_approx # vaeapp_sd15 ON
__term_sd_task_pre_model_30 get_modelscope_model licyks/fooocus-model/master/vae_approx/xl-to-v1_interposer-v3.1.safetensors "$fooocus_path"/models/vae_approx # xl-to-v1_interposer-v3.1 ON
__term_sd_task_pre_model_31 get_modelscope_model licyks/fooocus-model/master/vae_approx/xlvaeapp.pth "$fooocus_path"/models/vae_approx # xlvaeapp ON
__term_sd_task_pre_model_32 get_modelscope_model licyks/fooocus-model/master/loras/sdxl_lcm_lora.safetensors "$fooocus_path"/models/loras # sdxl_lcm_lora ON
__term_sd_task_pre_model_33 get_modelscope_model licyks/fooocus-model/master/controlnet/control-lora-canny-rank128.safetensors "$fooocus_path"/models/controlnet # control-lora-canny-rank128 ON
__term_sd_task_pre_model_34 get_modelscope_model licyks/fooocus-model/master/controlnet/fooocus_ip_negative.safetensors "$fooocus_path"/models/controlnet # fooocus_ip_negative ON
__term_sd_task_pre_model_35 get_modelscope_model licyks/fooocus-model/master/controlnet/fooocus_xl_cpds_128.safetensors "$fooocus_path"/models/controlnet # fooocus_xl_cpds_128 ON
__term_sd_task_pre_model_36 get_modelscope_model licyks/fooocus-model/master/controlnet/ip-adapter-plus_sdxl_vit-h.bin "$fooocus_path"/models/controlnet # ip-adapter-plus_sdxl_vit-h ON
__term_sd_task_pre_model_37 get_modelscope_model licyks/fooocus-model/master/controlnet/detection_Resnet50_Final.pth "$fooocus_path"/models/controlnet # detection_Resnet50_Final ON
__term_sd_task_pre_model_38 get_modelscope_model licyks/fooocus-model/master/controlnet/ip-adapter-plus-face_sdxl_vit-h.bin "$fooocus_path"/models/controlnet # ip-adapter-plus-face_sdxl_vit-h ON
__term_sd_task_pre_model_39 get_modelscope_model licyks/fooocus-model/master/controlnet/parsing_parsenet.pth "$fooocus_path"/models/controlnet # parsing_parsenet ON
