__term_sd_task_pre_model_1 # =====SDXL大模型===== OFF
__term_sd_task_pre_model_2 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sd_xl_base_1.0_0.9vae.safetensors "$fooocus_path"/models/checkpoints # sd_xl_base_1.0_0.9vae OFF
__term_sd_task_pre_model_3 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sd_xl_refiner_1.0_0.9vae.safetensors "$fooocus_path"/models/checkpoints # sd_xl_refiner_1.0_0.9vae OFF
__term_sd_task_pre_model_4 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animagine-xl-3.0.safetensors "$fooocus_path"/models/checkpoints # animagine-xl-3.0 OFF
__term_sd_task_pre_model_5 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/AnythingXL_xl.safetensors "$fooocus_path"/models/checkpoints # AnythingXL_xl OFF
__term_sd_task_pre_model_6 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/abyssorangeXLElse_v10.safetensors "$fooocus_path"/models/checkpoints # abyssorangeXLElse_v10 OFF
__term_sd_task_pre_model_7 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animaPencilXL_v200.safetensors "$fooocus_path"/models/checkpoints # animaPencilXL_v200 OFF
__term_sd_task_pre_model_8 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animagine-xl-3.1.safetensors "$fooocus_path"/models/checkpoints # animagine-xl-3.1 ON
__term_sd_task_pre_model_9 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/heartOfAppleXL_v20.safetensors "$fooocus_path"/models/checkpoints # heartOfAppleXL_v20 OFF
__term_sd_task_pre_model_10 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/baxlBartstylexlBlueArchiveFlatCelluloid_xlv1.safetensors "$fooocus_path"/models/checkpoints # baxlBartstylexlBlueArchiveFlatCelluloid_xlv1 OFF
__term_sd_task_pre_model_11 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/kohaku-xl-delta-rev1.safetensors "$fooocus_path"/models/checkpoints # kohaku-xl-delta-rev1 OFF
__term_sd_task_pre_model_12 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/kohakuXLEpsilon_rev1.safetensors "$fooocus_path"/models/checkpoints # kohakuXLEpsilon_rev1 OFF
__term_sd_task_pre_model_13 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/nekorayxl_v06W3.safetensors "$fooocus_path"/models/checkpoints # nekorayxl_v06W3 OFF
__term_sd_task_pre_model_14 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/CounterfeitXL-V1.0.safetensors "$fooocus_path"/models/checkpoints # CounterfeitXL-V1.0 OFF
__term_sd_task_pre_model_15 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/ponyDiffusionV6XL_v6StartWithThisOne.safetensors "$fooocus_path"/models/checkpoints # ponyDiffusionV6XL_v6 OFF
__term_sd_task_pre_model_16 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/starryXLV52_v52.safetensors "$fooocus_path"/models/checkpoints # starryXLV52_v52 OFF
__term_sd_task_pre_model_17 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/kohaku-xl-epsilon-rev2.safetensors "$fooocus_path"/models/checkpoints # kohaku-xl-epsilon-rev2 OFF
__term_sd_task_pre_model_18 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/heartOfAppleXL_v30.safetensors "$fooocus_path"/models/checkpoints # heartOfAppleXL_v30 OFF
__term_sd_task_pre_model_19 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animeIllustDiffusion_v061.safetensors "$fooocus_path"/models/checkpoints # animeIllustDiffusion_v061 OFF
__term_sd_task_pre_model_20 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/baxlBlueArchiveFlatCelluloidStyle_xlv3.safetensors "$fooocus_path"/models/checkpoints # baxlBlueArchiveFlatCelluloidStyle_xlv3 OFF
__term_sd_task_pre_model_21 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/bluePencilXL_v401.safetensors "$fooocus_path"/models/checkpoints # bluePencilXL_v401 OFF
__term_sd_task_pre_model_22 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sd_xl_refiner_1.0_0.9vae.safetensors "$fooocus_path"/models/checkpoints # sd_xl_refiner_1.0_0.9vae OFF
__term_sd_task_pre_model_23 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sd_xl_turbo_1.0_fp16.safetensors "$fooocus_path"/models/checkpoints # sd_xl_turbo_1.0_fp16 OFF
__term_sd_task_pre_model_24 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/pdForAnime_v20.safetensors "$fooocus_path"/models/checkpoints # pdForAnime_v20 OFF
__term_sd_task_pre_model_25 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/tPonynai3_v51WeightOptimized.safetensors "$fooocus_path"/models/checkpoints # tPonynai3_v51WeightOptimized OFF
__term_sd_task_pre_model_26 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/kohaku-xl-epsilon-rev3.safetensors "$fooocus_path"/models/checkpoints # kohaku-xl-epsilon-rev3 OFF
__term_sd_task_pre_model_27 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/holodayo-xl-2.1.safetensors "$fooocus_path"/models/checkpoints # holodayo-xl-2.1 OFF
__term_sd_task_pre_model_28 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/kivotos-xl-2.0.safetensors "$fooocus_path"/models/checkpoints # kivotos-xl-2.0 OFF
__term_sd_task_pre_model_29 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/omegaPonyXLAnime_v20.safetensors "$fooocus_path"/models/checkpoints # omegaPonyXLAnime_v20 OFF
__term_sd_task_pre_model_30 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sd_xl_anime_V52.safetensors "$fooocus_path"/models/checkpoints # sd_xl_anime_V52 OFF
__term_sd_task_pre_model_31 # =====其他模型===== OFF
__term_sd_task_pre_model_32 aria2_download https://huggingface.co/licyk/sd-lora/resolve/main/sdxl/sd_xl_offset_example-lora_1.0.safetensors "$fooocus_path"/models/loras # sd_xl_offset_example-lora_1.0 ON
__term_sd_task_pre_model_33 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/inpaint/inpaint.fooocus.patch "$fooocus_path"/models/inpaint # inpaint.fooocus ON
__term_sd_task_pre_model_34 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/inpaint/fooocus_inpaint_head.pth "$fooocus_path"/models/inpaint # fooocus_inpaint_head ON
__term_sd_task_pre_model_35 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/pytorch_model.bin "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_36 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/config.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_37 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/merges.txt "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_38 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/special_tokens_map.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_39 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/tokenizer.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_40 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/tokenizer_config.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_41 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/prompt_expansion/fooocus_expansion/vocab.json "$fooocus_path"/models/prompt_expansion/fooocus_expansion # fooocus_expansion ON
__term_sd_task_pre_model_42 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/upscale_models/fooocus_upscaler_s409985e5.bin "$fooocus_path"/models/upscale_models # fooocus_upscaler_s409985e5 ON
__term_sd_task_pre_model_43 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/vae_approx/vaeapp_sd15.pth "$fooocus_path"/models/vae_approx # vaeapp_sd15 ON
__term_sd_task_pre_model_44 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/vae_approx/xl-to-v1_interposer-v3.1.safetensors "$fooocus_path"/models/vae_approx # xl-to-v1_interposer-v3.1 ON
__term_sd_task_pre_model_45 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/vae_approx/xlvaeapp.pth "$fooocus_path"/models/vae_approx # xlvaeapp ON
__term_sd_task_pre_model_46 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/loras/sdxl_lcm_lora.safetensors "$fooocus_path"/models/loras # sdxl_lcm_lora ON
__term_sd_task_pre_model_47 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/control-lora-canny-rank128.safetensors "$fooocus_path"/models/controlnet # control-lora-canny-rank128 ON
__term_sd_task_pre_model_48 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/fooocus_ip_negative.safetensors "$fooocus_path"/models/controlnet # fooocus_ip_negative ON
__term_sd_task_pre_model_49 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/fooocus_xl_cpds_128.safetensors "$fooocus_path"/models/controlnet # fooocus_xl_cpds_128 ON
__term_sd_task_pre_model_50 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/ip-adapter-plus_sdxl_vit-h.bin "$fooocus_path"/models/controlnet # ip-adapter-plus_sdxl_vit-h ON
__term_sd_task_pre_model_51 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/detection_Resnet50_Final.pth "$fooocus_path"/models/controlnet # detection_Resnet50_Final ON
__term_sd_task_pre_model_52 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/ip-adapter-plus-face_sdxl_vit-h.bin "$fooocus_path"/models/controlnet # ip-adapter-plus-face_sdxl_vit-h ON
__term_sd_task_pre_model_53 aria2_download https://huggingface.co/licyk/fooocus-model/resolve/main/controlnet/parsing_parsenet.pth "$fooocus_path"/models/controlnet # parsing_parsenet ON
