__term_sd_task_pre_model_1 =====SD1.5大模型===== OFF
__term_sd_task_pre_model_2 v1-5-pruned-emaonly OFF
__term_sd_task_pre_model_3 animefull-final-pruned ON
__term_sd_task_pre_model_4 =====SDXL大模型===== OFF
__term_sd_task_pre_model_5 sd_xl_base_1.0_0.9vae OFF
__term_sd_task_pre_model_6 animagine-xl-3.0 OFF
__term_sd_task_pre_model_7 kohaku-xl-delta-rev1 OFF
__term_sd_task_pre_model_8 =====VAE模型===== OFF
__term_sd_task_pre_model_9 vae-ft-ema-560000-ema-pruned OFF
__term_sd_task_pre_model_10 vae-ft-mse-840000-ema-pruned OFF
__term_sd_task_pre_model_11 sdxl_fp16_fix_vae OFF
__term_sd_task_pre_model_12 sdxl_vae OFF
