__term_sd_task_pre_model_1 # =====SD1.5大模型===== OFF
__term_sd_task_pre_model_2 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sd_1.5/v1-5-pruned-emaonly.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # v1-5-pruned-emaonly(4.27g) OFF
__term_sd_task_pre_model_3 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sd_1.5/animefull-final-pruned.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # animefull-final-pruned(4.27g) ON
__term_sd_task_pre_model_4 # =====SD2.1大模型===== OFF
__term_sd_task_pre_model_5 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sd_2.1/v2-1_768-ema-pruned.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # v2-1_768-ema-pruned(5.21g) OFF
__term_sd_task_pre_model_6 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sd_2.1/wd-1-4-anime_e2.ckpt "${KOHYA_SS_ROOT_PATH}"/models/ # wd-1-4-anime_e2(5.16g) OFF
__term_sd_task_pre_model_7 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sd_2.1/wd-mofu-fp16.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # wd-mofu-fp16(2.58g) OFF
__term_sd_task_pre_model_8 # =====SDXL大模型===== OFF
__term_sd_task_pre_model_9 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sd_xl_base_1.0_0.9vae.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # sd_xl_base_1.0_0.9vae(6.94g) OFF
__term_sd_task_pre_model_10 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sd_xl_refiner_1.0_0.9vae.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # sd_xl_refiner_1.0_0.9vae(6.94g) OFF
__term_sd_task_pre_model_11 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sd_xl_turbo_1.0_fp16.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # sd_xl_turbo_1.0_fp16(6.94g) OFF
__term_sd_task_pre_model_12 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animagine-xl-3.0-base.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # animagine-xl-3.0-base(6.94g) OFF
__term_sd_task_pre_model_13 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animagine-xl-3.0.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # animagine-xl-3.0(6.94g) OFF
__term_sd_task_pre_model_14 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animagine-xl-3.1.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # animagine-xl-3.1(6.94g) OFF
__term_sd_task_pre_model_15 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animagine-xl-4.0.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # animagine-xl-4.0(6.94g) OFF
__term_sd_task_pre_model_16 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animagine-xl-4.0-opt.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # animagine-xl-4.0-opt(6.94g) OFF
__term_sd_task_pre_model_17 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animagine-xl-4.0-zero.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # animagine-xl-4.0-zero(6.94g) OFF
__term_sd_task_pre_model_18 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/holodayo-xl-2.1.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # holodayo-xl-2.1(6.94g) OFF
__term_sd_task_pre_model_19 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/kivotos-xl-2.0.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # kivotos-xl-2.0(6.94g) OFF
__term_sd_task_pre_model_20 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/clandestine-xl-1.0.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # clandestine-xl-1.0(6.94g) OFF
__term_sd_task_pre_model_21 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/UrangDiffusion-1.1.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # UrangDiffusion-1.1(6.94g) OFF
__term_sd_task_pre_model_22 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/RaeDiffusion-XL-v2.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # RaeDiffusion-XL-v2(6.94g) OFF
__term_sd_task_pre_model_23 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sd_xl_anime_V52.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # sd_xl_anime_V52(6.94g) OFF
__term_sd_task_pre_model_24 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/kohaku-xl-delta-rev1.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # kohaku-xl-delta-rev1(6.94g) OFF
__term_sd_task_pre_model_25 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/kohakuXLEpsilon_rev1.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # kohakuXLEpsilon_rev1(6.94g) OFF
__term_sd_task_pre_model_26 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/kohaku-xl-epsilon-rev2.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # kohaku-xl-epsilon-rev2(6.94g) OFF
__term_sd_task_pre_model_27 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/kohaku-xl-epsilon-rev3.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # kohaku-xl-epsilon-rev3(6.94g) OFF
__term_sd_task_pre_model_28 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/kohaku-xl-zeta.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # kohaku-xl-zeta(6.94g) OFF
__term_sd_task_pre_model_29 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/starryXLV52_v52.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # starryXLV52_v52(6.94g) OFF
__term_sd_task_pre_model_30 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/heartOfAppleXL_v20.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # heartOfAppleXL_v20(6.94g) OFF
__term_sd_task_pre_model_31 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/heartOfAppleXL_v30.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # heartOfAppleXL_v30(6.94g) OFF
__term_sd_task_pre_model_32 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/baxlBartstylexlBlueArchiveFlatCelluloid_xlv1.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # baxlBartstylexlBlueArchiveFlatCelluloid_xlv1(6.94g) OFF
__term_sd_task_pre_model_33 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/baxlBlueArchiveFlatCelluloidStyle_xlv3.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # baxlBlueArchiveFlatCelluloidStyle_xlv3(6.94g) OFF
__term_sd_task_pre_model_34 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sanaexlAnimeV10_v10.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # sanaexlAnimeV10_v10(6.94g) OFF
__term_sd_task_pre_model_35 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/sanaexlAnimeV10_v11.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # sanaexlAnimeV10_v11(6.94g) OFF
__term_sd_task_pre_model_36 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/SanaeXL-Anime-v1.2-aesthetic.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # SanaeXL-Anime-v1.2-aesthetic(6.94g) OFF
__term_sd_task_pre_model_37 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/SanaeXL-Anime-v1.3-aesthetic.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # SanaeXL-Anime-v1.3-aesthetic(6.94g) OFF
__term_sd_task_pre_model_38 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/Illustrious-XL-v0.1.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # Illustrious-XL-v0.1(6.94g) OFF
__term_sd_task_pre_model_39 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/Illustrious-XL-v0.1-GUIDED.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # Illustrious-XL-v0.1-GUIDED(6.94g) OFF
__term_sd_task_pre_model_40 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/Illustrious-XL-v1.0.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # Illustrious-XL-v1.0(6.94g) OFF
__term_sd_task_pre_model_41 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/Illustrious-XL-v1.1.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # Illustrious-XL-v1.1(6.94g) OFF
__term_sd_task_pre_model_42 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/Illustrious-XL-v2.0-stable.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # Illustrious-XL-v2.0-stable(6.94g) OFF
__term_sd_task_pre_model_43 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/jruTheJourneyRemains_v25XL.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # jruTheJourneyRemains_v25XL(6.94g) OFF
__term_sd_task_pre_model_44 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/PVCStyleModelMovable_illustriousxl10.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # PVCStyleModelMovable_illustriousxl10(6.94g) OFF
__term_sd_task_pre_model_45 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/miaomiaoHarem_v15a.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # miaomiaoHarem_v15a(6.94g) OFF
__term_sd_task_pre_model_46 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/waiNSFWIllustrious_v80.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # waiNSFWIllustrious_v80(6.94g) OFF
__term_sd_task_pre_model_47 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/tIllunai3_v4.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # tIllunai3_v4(6.94g) OFF
__term_sd_task_pre_model_48 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_earlyAccessVersion.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_earlyAccessVersion(6.94g) OFF
__term_sd_task_pre_model_49 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_epsilonPred05Version.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_epsilonPred05Version(6.94g) OFF
__term_sd_task_pre_model_50 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_epsilonPred075.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_epsilonPred075(6.94g) OFF
__term_sd_task_pre_model_51 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_epsilonPred077.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_epsilonPred077(6.94g) OFF
__term_sd_task_pre_model_52 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_epsilonPred10Version.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_epsilonPred10Version(6.94g) OFF
__term_sd_task_pre_model_53 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_epsilonPred11Version.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_epsilonPred11Version(6.94g) OFF
__term_sd_task_pre_model_54 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_vPredTestVersion.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_vPredTestVersion(6.94g) OFF
__term_sd_task_pre_model_55 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_vPred05Version.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_vPred05Version(6.94g) OFF
__term_sd_task_pre_model_56 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_vPred06Version.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_vPred06Version(6.94g) OFF
__term_sd_task_pre_model_57 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_vPred065SVersion.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_vPred065SVersion(6.94g) OFF
__term_sd_task_pre_model_58 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_vPred075SVersion.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_vPred075SVersion(6.94g) OFF
__term_sd_task_pre_model_59 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_vPred09RVersion.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_vPred09RVersion(6.94g) OFF
__term_sd_task_pre_model_60 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/noobaiXLNAIXL_vPred10Version.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # noobaiXLNAIXL_vPred10Version(6.94g) OFF
__term_sd_task_pre_model_61 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/PVCStyleModelMovable_nbxl12.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # PVCStyleModelMovable_nbxl12(6.94g) OFF
__term_sd_task_pre_model_62 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/PVCStyleModelMovable_nbxlVPredV10.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # PVCStyleModelMovable_nbxlVPredV10(6.94g) OFF
__term_sd_task_pre_model_63 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/ponyDiffusionV6XL_v6StartWithThisOne.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # ponyDiffusionV6XL_v6(6.94g) OFF
__term_sd_task_pre_model_64 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/pdForAnime_v20.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # pdForAnime_v20(7.11g) OFF
__term_sd_task_pre_model_65 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/tPonynai3_v51WeightOptimized.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # tPonynai3_v51WeightOptimized(6.94g) OFF
__term_sd_task_pre_model_66 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/omegaPonyXLAnime_v20.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # omegaPonyXLAnime_v20(6.94g) OFF
__term_sd_task_pre_model_67 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/animeIllustDiffusion_v061.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # animeIllustDiffusion_v061(6.94g) OFF
__term_sd_task_pre_model_68 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/artiwaifuDiffusion_v10.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # artiwaifuDiffusion_v10(6.94g) OFF
__term_sd_task_pre_model_69 aria2_download https://huggingface.co/licyk/sd-model/resolve/main/sdxl_1.0/artiwaifu-diffusion-v2.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # artiwaifu-diffusion-v2(6.94g) OFF
__term_sd_task_pre_model_70 # =====VAE模型===== OFF
__term_sd_task_pre_model_71 aria2_download https://huggingface.co/licyk/sd-vae/resolve/main/sd_1.5/vae-ft-ema-560000-ema-pruned.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # vae-ft-ema-560000-ema-pruned(334.6m) OFF
__term_sd_task_pre_model_72 aria2_download https://huggingface.co/licyk/sd-vae/resolve/main/sd_1.5/vae-ft-mse-840000-ema-pruned.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # vae-ft-mse-840000-ema-pruned(334.6m) OFF
__term_sd_task_pre_model_73 aria2_download https://huggingface.co/licyk/sd-vae/resolve/main/sdxl_1.0/sdxl_fp16_fix_vae.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # sdxl_fp16_fix_vae(334.6m) OFF
__term_sd_task_pre_model_74 aria2_download https://huggingface.co/licyk/sd-vae/resolve/main/sdxl_1.0/sdxl_vae.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # sdxl_vae(334.6m) OFF
__term_sd_task_pre_model_75 # =====FLUX模型===== OFF
__term_sd_task_pre_model_76 aria2_download https://huggingface.co/licyk/flux-model/resolve/main/flux_1/flux1-dev.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # flux1-dev(23.8g) OFF
__term_sd_task_pre_model_77 aria2_download https://huggingface.co/licyk/flux-model/resolve/main/flux_1/flux1-schnell.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # flux1-schnell(23.8g) OFF
__term_sd_task_pre_model_78 aria2_download https://huggingface.co/licyk/flux-model/resolve/main/flux_1/ashen0209-flux1-dev2pro.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # ashen0209-flux1-dev2pro(23.8g) OFF
__term_sd_task_pre_model_79 aria2_download https://huggingface.co/licyk/flux-model/resolve/main/flux_1/jimmycarter-LibreFLUX.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # jimmycarter-LibreFLUX(23.8g) OFF
__term_sd_task_pre_model_80 aria2_download https://huggingface.co/licyk/flux-model/resolve/main/flux_1/nyanko7-flux-dev-de-distill.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # nyanko7-flux-dev-de-distill(23.8g) OFF
__term_sd_task_pre_model_81 aria2_download https://huggingface.co/licyk/flux-model/resolve/main/flux_1/shuttle-3-diffusion.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # shuttle-3-diffusion(23.8g) OFF
__term_sd_task_pre_model_82 # =====FLUX-文本编码器/VAE模型===== OFF
__term_sd_task_pre_model_83 aria2_download https://huggingface.co/licyk/flux-model/resolve/main/flux_text_encoders/clip_l.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # clip_l(246.1m) OFF
__term_sd_task_pre_model_84 aria2_download https://huggingface.co/licyk/flux-model/resolve/main/flux_text_encoders/t5xxl_fp16.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # t5xxl_fp16(9.79g) OFF
__term_sd_task_pre_model_85 aria2_download https://huggingface.co/licyk/flux-model/resolve/main/flux_vae/ae.safetensors "${KOHYA_SS_ROOT_PATH}"/models/ # ae(335m) OFF
