__term_sd_task_pre_ext_38 term_sd_echo "下载controlnet模型中"
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11e_sd15_ip2p_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11e_sd15_shuffle_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11f1e_sd15_tile_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11f1p_sd15_depth_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_canny_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_inpaint_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_lineart_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_mlsd_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_normalbae_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_openpose_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_scribble_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_seg_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_softedge_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15s2_lineart_anime_fp16.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v1p_sd15_brightness.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v1p_sd15_illumination.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v1p_sd15_qrcode_monster.safetensors "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_canny_sd15v2.pth "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_color_sd14v1.pth "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_depth_sd15v2.pth "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_keypose_sd14v1.pth "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_openpose_sd14v1.pth "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_seg_sd14v1.pth "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_sketch_sd15v2.pth "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_style_sd14v1.pth "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_zoedepth_sd15v1.pth "$comfyui_path"/models/controlnet
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/LayerNorm/DensePose-TorchScript-with-hint-image/densepose_r101_fpn_dl.torchscript "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/LayerNorm/DensePose-TorchScript-with-hint-image
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/LayerNorm/DensePose-TorchScript-with-hint-image/densepose_r50_fpn_dl.torchscript "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/LayerNorm/DensePose-TorchScript-with-hint-image
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/LiheYoung/Depth-Anything/checkpoints/depth_anything_vitl14.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/LiheYoung/Depth-Anything/checkpoints
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/LiheYoung/Depth-Anything/checkpoints_metric_depth/depth_anything_metric_depth_indoor.pt "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/LiheYoung/Depth-Anything/checkpoints_metric_depth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/bdsqlsz/qinglong_controlnet-lllite/Annotators/7_model.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/bdsqlsz/qinglong_controlnet-lllite/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/bdsqlsz/qinglong_controlnet-lllite/Annotators/UNet.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/bdsqlsz/qinglong_controlnet-lllite/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/dhkim2810/MobileSAM/mobile_sam.pt "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/hr16/ControlNet-HandRefiner-pruned/graphormer_hand_state_dict.bin "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/hr16/ControlNet-HandRefiner-pruned/hrnetv2_w64_imagenet_pretrained.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/hr16/DWPose-TorchScript-BatchSize5/dw-ll_ucoco_384_bs5.torchscript.pt "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/hr16/DWPose-TorchScript-BatchSize5/rtmpose-m_ap10k_256_bs5.torchscript.pt "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/hr16/UnJIT-DWPose/dw-ll_ucoco.onnx "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/hr16/UnJIT-DWPose
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/hr16/UnJIT-DWPose/rtmpose-m_ap10k_256.onnx "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/hr16/UnJIT-DWPose
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/hr16/yolo-nas-fp16/yolo_nas_l_fp16.onnx "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/hr16/yolo-nas-fp16
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/hr16/yolo-nas-fp16/yolo_nas_m_fp16.onnx "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/hr16/yolo-nas-fp16
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/hr16/yolo-nas-fp16/yolo_nas_s_fp16.onnx "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/hr16/yolo-nas-fp16
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/hr16/yolox-onnx/yolox_l.torchscript.pt "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/hr16/yolox-onnx
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/150_16_swin_l_oneformer_coco_100ep.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/250_16_swin_l_oneformer_ade20k_160k.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/ControlNetHED.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/ZoeD_M12_N.pt "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/body_pose_model.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/dpt_hybrid-midas-501f0c75.pt "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/dw-ll_ucoco_384.onnx "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/erika.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/facenet.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/hand_pose_model.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/latest_net_G.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/mlsd_large_512_fp32.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/netG.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/res101.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/scannet.pt "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/sk_model.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/sk_model2.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/table5_pidinet.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/upernet_global_small.pth "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/lllyasviel/Annotators/yolox_l.onnx "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/skytnt/anime-seg/isnetis.ckpt "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/skytnt/anime-seg
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/yzd-v/DWPose/dw-ll_ucoco_384.onnx "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/yzd-v/DWPose
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/comfyui_controlnet_aux/yzd-v/DWPose/yolox_l.onnx "$comfyui_path"/custom_nodes/comfyui_controlnet_aux/ckpts/yzd-v/DWPose

__term_sd_task_pre_ext_44 term_sd_echo "下载animatediff模型中"
__term_sd_task_pre_ext_44 aria2_download https://huggingface.co/guoyww/animatediff/resolve/main/mm_sd_v15_v2.ckpt "$comfyui_path"/custom_nodes/ComfyUI-AnimateDiff-Evolved/models

__term_sd_task_pre_ext_46 term_sd_echo "下载ip-adapter模型中"
__term_sd_task_pre_ext_46 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/ip-adapter-plus-face_sd15.pth "$comfyui_path"/custom_nodes/ComfyUI_IPAdapter_plus/models
__term_sd_task_pre_ext_46 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/ip-adapter_sd15.pth "$comfyui_path"/custom_nodes/ComfyUI_IPAdapter_plus/models
__term_sd_task_pre_ext_46 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/ip-adapter_sd15_light.pth "$comfyui_path"/custom_nodes/ComfyUI_IPAdapter_plus/models
__term_sd_task_pre_ext_46 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/ip-adapter_sd15_plus.pth "$comfyui_path"/custom_nodes/ComfyUI_IPAdapter_plus/models
__term_sd_task_pre_ext_46 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/clip_vision/clip_g.pth "$comfyui_path"/models/clip_vision
__term_sd_task_pre_ext_46 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/clip_vision/clip_h.pth "$comfyui_path"/models/clip_vision
__term_sd_task_pre_ext_46 aria2_download https://huggingface.co/licyk/controlnet_v1.1_annotator/resolve/main/clip_vision/clip_vitl.pth "$comfyui_path"/models/clip_vision

__term_sd_task_pre_ext_7 term_sd_echo "下载ComfyUI-Impact-Pack模型中"
__term_sd_task_pre_ext_7 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Impact-Pack/face_yolov8m.pt "$comfyui_path"/models/ultralytics/bbox
__term_sd_task_pre_ext_7 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Impact-Pack/mmdet_anime-face_yolov3.pth "$comfyui_path"/models/ultralytics/bbox
__term_sd_task_pre_ext_7 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Impact-Pack/sam_vit_b_01ec64.pth "$comfyui_path"/models/sams
__term_sd_task_pre_ext_7 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Impact-Pack/hand_yolov8s.pt "$comfyui_path"/models/ultralytics/bbox
__term_sd_task_pre_ext_7 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Impact-Pack/person_yolov8m-seg.pt "$comfyui_path"/models/ultralytics/segm

__term_sd_task_pre_ext_61 term_sd_echo "下载ComfyUI-Marigold模型中"
__term_sd_task_pre_ext_61 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Marigold/model_index.json "$comfyui_path"/diffusers
__term_sd_task_pre_ext_61 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Marigold/scheduler/scheduler_config.json "$comfyui_path"/diffusers/scheduler
__term_sd_task_pre_ext_61 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Marigold/text_encoder/config.json "$comfyui_path"/diffusers/text_encoder
__term_sd_task_pre_ext_61 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Marigold/text_encoder/model.safetensors "$comfyui_path"/diffusers/text_encoder
__term_sd_task_pre_ext_61 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Marigold/tokenizer/merges.txt "$comfyui_path"/diffusers/tokenizer
__term_sd_task_pre_ext_61 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Marigold/tokenizer/special_tokens_map.json "$comfyui_path"/diffusers/tokenizer
__term_sd_task_pre_ext_61 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Marigold/tokenizer/tokenizer_config.json "$comfyui_path"/diffusers/tokenizer
__term_sd_task_pre_ext_61 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Marigold/tokenizer/vocab.json "$comfyui_path"/diffusers/tokenizer
__term_sd_task_pre_ext_61 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Marigold/unet/config.json "$comfyui_path"/diffusers/unet
__term_sd_task_pre_ext_61 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Marigold/unet/diffusion_pytorch_model.safetensors "$comfyui_path"/diffusers/unet
__term_sd_task_pre_ext_61 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Marigold/vae/config.json "$comfyui_path"/diffusers/vae
__term_sd_task_pre_ext_61 aria2_download https://huggingface.co/licyk/comfyui-extension-models/resolve/main/ComfyUI-Marigold/vae/diffusion_pytorch_model.safetensors "$comfyui_path"/diffusers/vae
