__term_sd_task_pre_ext_1 git_clone_repository ${github_mirror} https://github.com/WASasquatch/was-node-suite-comfyui ComfyUI/custom_nodes ON # 适用于ComfyUI的广泛节点套件，包含190多个新节点
__term_sd_task_pre_ext_2 git_clone_repository ${github_mirror} https://github.com/BlenderNeko/ComfyUI_Cutoff ComfyUI/custom_nodes ON # 解决tag污染
__term_sd_task_pre_ext_3 git_clone_repository ${github_mirror} https://github.com/BlenderNeko/ComfyUI_TiledKSampler ComfyUI/custom_nodes OFF # ComfyUI的平铺采样器
__term_sd_task_pre_ext_4 git_clone_repository ${github_mirror} https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb ComfyUI/custom_nodes OFF # 高级剪辑文本编码，可让您选择解释提示权重的方式
__term_sd_task_pre_ext_5 git_clone_repository ${github_mirror} https://github.com/BlenderNeko/ComfyUI_Noise ComfyUI/custom_nodes OFF # 噪声控制
__term_sd_task_pre_ext_6 git_clone_repository ${github_mirror} https://github.com/Davemane42/ComfyUI_Dave_CustomNode ComfyUI/custom_nodes OFF # 图片区域控制
__term_sd_task_pre_ext_7 git_clone_repository ${github_mirror} https://github.com/ltdrdata/ComfyUI-Impact-Pack ComfyUI/custom_nodes OFF # 通过检测器、细节器、升频器、管道等方便地增强图像
__term_sd_task_pre_ext_8 git_clone_repository ${github_mirror} https://github.com/ltdrdata/ComfyUI-Manager ComfyUI/custom_nodes ON # 自定义节点/插件管理器
__term_sd_task_pre_ext_9 git_clone_repository ${github_mirror} https://github.com/Zuellni/ComfyUI-Custom-Nodes ComfyUI/custom_nodes OFF # ComfyUI的自定义节点
__term_sd_task_pre_ext_10 git_clone_repository ${github_mirror} https://github.com/pythongosssss/ComfyUI-Custom-Scripts ComfyUI/custom_nodes OFF # ComfyUI的增强功能
__term_sd_task_pre_ext_11 git_clone_repository ${github_mirror} https://github.com/xXAdonesXx/NodeGPT ComfyUI/custom_nodes OFF # 使用GPT辅助生图
__term_sd_task_pre_ext_12 git_clone_repository ${github_mirror} https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes ComfyUI/custom_nodes OFF # 方程式节点
__term_sd_task_pre_ext_13 git_clone_repository ${github_mirror} https://github.com/LucianoCirino/efficiency-nodes-comfyui ComfyUI/custom_nodes OFF # ComfyUI的效率节点
__term_sd_task_pre_ext_14 git_clone_repository ${github_mirror} https://github.com/lilly1987/ComfyUI_node_Lilly ComfyUI/custom_nodes OFF # 通配符文本工具
__term_sd_task_pre_ext_15 git_clone_repository ${github_mirror} https://github.com/hnmr293/ComfyUI-nodes-hnmr ComfyUI/custom_nodes OFF # 包含X/Y/Z-plotX/Y/Z，合并，潜在可视化，采样等节点
__term_sd_task_pre_ext_16 git_clone_repository ${github_mirror} https://github.com/diontimmer/ComfyUI-Vextra-Nodes ComfyUI/custom_nodes OFF # 包含像素排序，交换颜色模式，拼合颜色等节点
__term_sd_task_pre_ext_17 git_clone_repository ${github_mirror} https://github.com/omar92/ComfyUI-QualityOfLifeSuit_Omar92 ComfyUI/custom_nodes OFF # 包含GPT辅助标签生成，字符串操作，latentTools等节点
__term_sd_task_pre_ext_18 git_clone_repository ${github_mirror} https://github.com/Fannovel16/FN16-ComfyUI-nodes ComfyUI/custom_nodes OFF # ComfyUI自定义节点集合
__term_sd_task_pre_ext_19 git_clone_repository ${github_mirror} https://github.com/BadCafeCode/masquerade-nodes-comfyui ComfyUI/custom_nodes OFF # ComfyUI掩码相关节点
__term_sd_task_pre_ext_20 git_clone_repository ${github_mirror} https://github.com/EllangoK/ComfyUI-post-processing-nodes ComfyUI/custom_nodes OFF # ComfyUI的后处理节点集合，可实现各种酷炫的图像效果
__term_sd_task_pre_ext_21 git_clone_repository ${github_mirror} https://github.com/LEv145/images-grid-comfy-plugin ComfyUI/custom_nodes OFF # XYZPlot图生成
__term_sd_task_pre_ext_22 git_clone_repository ${github_mirror} https://github.com/biegert/ComfyUI-CLIPSeg ComfyUI/custom_nodes OFF # 利用CLIPSeg模型根据文本提示为图像修复任务生成蒙版
__term_sd_task_pre_ext_23 git_clone_repository ${github_mirror} https://github.com/Jcd1230/rembg-comfyui-node ComfyUI/custom_nodes OM # 背景去除
__term_sd_task_pre_ext_24 git_clone_repository ${github_mirror} https://github.com/TinyTerra/ComfyUI_tinyterraNodes ComfyUI/custom_nodes OFF # ComfyUI的自定义节点
__term_sd_task_pre_ext_25 git_clone_repository ${github_mirror} https://github.com/guoyk93/yk-node-suite-comfyui ComfyUI/custom_nodes OFF # ComfyUI的自定义节点
__term_sd_task_pre_ext_26 git_clone_repository ${github_mirror} https://github.com/comfyanonymous/ComfyUI_experiments ComfyUI/custom_nodes OFF # ComfyUI的一些实验性自定义节点
__term_sd_task_pre_ext_27 git_clone_repository ${github_mirror} https://github.com/gamert/ComfyUI_tagger ComfyUI/custom_nodes OFF # 图片tag反推
__term_sd_task_pre_ext_28 git_clone_repository ${github_mirror} https://github.com/YinBailiang/MergeBlockWeighted_fo_ComfyUI ComfyUI/custom_nodes OFF # 权重合并
__term_sd_task_pre_ext_29 git_clone_repository ${github_mirror} https://github.com/Kaharos94/ComfyUI-Saveaswebp ComfyUI/custom_nodes OFF # 将生成的图片保存为webp格式
__term_sd_task_pre_ext_30 git_clone_repository ${github_mirror} https://github.com/trojblue/trNodes ComfyUI/custom_nodes OFF # 通过蒙版混合两个图像
__term_sd_task_pre_ext_31 git_clone_repository ${github_mirror} https://github.com/city96/ComfyUI_NetDist ComfyUI/custom_nodes OFF # 在多个本地GPU/联网机器上运行ComfyUI工作流程
__term_sd_task_pre_ext_32 git_clone_repository ${github_mirror} https://github.com/SLAPaper/ComfyUI-Image-Selector ComfyUI/custom_nodes OFF # 从批处理中选择一个或多个图像
__term_sd_task_pre_ext_33 git_clone_repository ${github_mirror} https://github.com/strimmlarn/ComfyUI-Strimmlarns-Aesthetic-Score ComfyUI/custom_nodes OFF # 图片美学评分
__term_sd_task_pre_ext_34 git_clone_repository ${github_mirror} https://github.com/ssitu/ComfyUI_UltimateSDUpscale ComfyUI/custom_nodes OFF # 图片放大
__term_sd_task_pre_ext_35 git_clone_repository ${github_mirror} https://github.com/space-nuko/ComfyUI-Disco-Diffusion ComfyUI/custom_nodes OFF # DiscoDiffusion模块
__term_sd_task_pre_ext_36 git_clone_repository ${github_mirror} https://github.com/Bikecicle/ComfyUI-Waveform-Extensions ComfyUI/custom_nodes OFF # 包括姿势，翻译等节点
__term_sd_task_pre_ext_37 git_clone_repository ${github_mirror} https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet ComfyUI/custom_nodes OFF # 一些额外的音频工具，用于示例扩散ComfyUI扩展
__term_sd_task_pre_ext_38 git_clone_repository ${github_mirror} https://github.com/Fannovel16/comfyui_controlnet_aux ComfyUI/custom_nodes ON # ComfyUI的ControlNet辅助预处理器
__term_sd_task_pre_ext_39 git_clone_repository ${github_mirror} https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION ComfyUI/custom_nodes ON # ComfyUI的翻译扩展
__term_sd_task_pre_ext_40 git_clone_repository ${github_mirror} https://github.com/Stability-AI/stability-ComfyUI-nodes ComfyUI/custom_nodes ON # Stability-AI自定义节点支持
__term_sd_task_pre_ext_41 git_clone_repository ${github_mirror} https://github.com/hustille/ComfyUI_Fooocus_KSampler ComfyUI/custom_nodes OFF # 添加fooocus噪声生成器支持
__term_sd_task_pre_ext_42 git_clone_repository ${github_mirror} https://github.com/WASasquatch/FreeU_Advanced ComfyUI/custom_nodes ON # 生图加速
__term_sd_task_pre_ext_43 git_clone_repository ${github_mirror} https://github.com/kohya-ss/ControlNet-LLLite-ComfyUI ComfyUI/custom_nodes OFF # 添加ControlNet-LLLite支持
