__term_sd_task_pre_ext_1 git_clone_repository ${github_mirror} https://github.com/Fannovel16/comfyui_controlnet_aux "$comfyui_path"/custom_nodes ON # ComfyUI的ControlNet辅助预处理器
__term_sd_task_pre_ext_2 git_clone_repository ${github_mirror} https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved "$comfyui_path"/custom_nodes ON # 视频生成节点
__term_sd_task_pre_ext_3 git_clone_repository ${github_mirror} https://github.com/cubiq/ComfyUI_IPAdapter_plus "$comfyui_path"/custom_nodes ON # 添加ip-adapt支持
__term_sd_task_pre_ext_4 git_clone_repository ${github_mirror} https://github.com/ltdrdata/ComfyUI-Impact-Pack "$comfyui_path"/custom_nodes ON # 通过检测器、细节器、升频器、管道等方便地增强图像
__term_sd_task_pre_ext_5 git_clone_repository ${github_mirror} https://github.com/kijai/ComfyUI-Marigold "$comfyui_path"/custom_nodes ON # 深度图生成节点
__term_sd_task_pre_ext_6 git_clone_repository ${github_mirror} https://github.com/pythongosssss/ComfyUI-WD14-Tagger "$comfyui_path"/custom_nodes ON # 图片标签反推
__term_sd_task_pre_ext_7 git_clone_repository ${github_mirror} https://github.com/huchenlei/ComfyUI-layerdiffusion "$comfyui_path"/custom_nodes OFF # LayerDiffusion节点
__term_sd_task_pre_ext_8 git_clone_repository ${github_mirror} https://github.com/huchenlei/ComfyUI_DanTagGen "$comfyui_path"/custom_nodes OFF # 使用Danboou风格对tag进行润色，使出图效果更好，内容更丰富
__term_sd_task_pre_ext_9 git_clone_repository ${github_mirror} https://github.com/gameltb/Comfyui-StableSR "$comfyui_path"/custom_nodes OFF # 图片放大
__term_sd_task_pre_ext_10 git_clone_repository ${github_mirror} https://github.com/WASasquatch/was-node-suite-comfyui "$comfyui_path"/custom_nodes OFF # 适用于ComfyUI的广泛节点套件，包含190多个新节点
__term_sd_task_pre_ext_11 git_clone_repository ${github_mirror} https://github.com/BlenderNeko/ComfyUI_Cutoff "$comfyui_path"/custom_nodes OFF # 解决tag污染
__term_sd_task_pre_ext_12 git_clone_repository ${github_mirror} https://github.com/BlenderNeko/ComfyUI_TiledKSampler "$comfyui_path"/custom_nodes ON # ComfyUI的平铺采样器
__term_sd_task_pre_ext_13 git_clone_repository ${github_mirror} https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb "$comfyui_path"/custom_nodes OFF # 高级剪辑文本编码，可让您选择解释提示权重的方式
__term_sd_task_pre_ext_14 git_clone_repository ${github_mirror} https://github.com/BlenderNeko/ComfyUI_Noise "$comfyui_path"/custom_nodes OFF # 噪声控制
__term_sd_task_pre_ext_15 git_clone_repository ${github_mirror} https://github.com/Davemane42/ComfyUI_Dave_CustomNode "$comfyui_path"/custom_nodes OFF # 图片区域控制
__term_sd_task_pre_ext_16 git_clone_repository ${github_mirror} https://github.com/ltdrdata/ComfyUI-Manager "$comfyui_path"/custom_nodes ON # 自定义节点管理器
__term_sd_task_pre_ext_17 git_clone_repository ${github_mirror} https://github.com/Zuellni/ComfyUI-Custom-Nodes "$comfyui_path"/custom_nodes OFF # ComfyUI的自定义节点
__term_sd_task_pre_ext_18 git_clone_repository ${github_mirror} https://github.com/pythongosssss/ComfyUI-Custom-Scripts "$comfyui_path"/custom_nodes ON # ComfyUI的增强功能
__term_sd_task_pre_ext_19 git_clone_repository ${github_mirror} https://github.com/xXAdonesXx/NodeGPT "$comfyui_path"/custom_nodes OFF # 使用GPT辅助生图
__term_sd_task_pre_ext_20 git_clone_repository ${github_mirror} https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes "$comfyui_path"/custom_nodes ON # 方程式节点
__term_sd_task_pre_ext_21 git_clone_repository ${github_mirror} https://github.com/lilly1987/ComfyUI_node_Lilly "$comfyui_path"/custom_nodes OFF # 通配符文本工具
__term_sd_task_pre_ext_22 git_clone_repository ${github_mirror} https://github.com/hnmr293/ComfyUI-nodes-hnmr "$comfyui_path"/custom_nodes OFF # 包含X/Y/Z-plotX/Y/Z，合并，潜在可视化，采样等节点
__term_sd_task_pre_ext_23 git_clone_repository ${github_mirror} https://github.com/diontimmer/ComfyUI-Vextra-Nodes "$comfyui_path"/custom_nodes OFF # 包含像素排序，交换颜色模式，拼合颜色等节点
__term_sd_task_pre_ext_24 git_clone_repository ${github_mirror} https://github.com/omar92/ComfyUI-QualityOfLifeSuit_Omar92 "$comfyui_path"/custom_nodes OFF # 包含GPT辅助标签生成，字符串操作，latentTools等节点
__term_sd_task_pre_ext_25 git_clone_repository ${github_mirror} https://github.com/Fannovel16/FN16-ComfyUI-nodes "$comfyui_path"/custom_nodes OFF # ComfyUI自定义节点集合
__term_sd_task_pre_ext_26 git_clone_repository ${github_mirror} https://github.com/BadCafeCode/masquerade-nodes-comfyui "$comfyui_path"/custom_nodes OFF # ComfyUI掩码相关节点
__term_sd_task_pre_ext_27 git_clone_repository ${github_mirror} https://github.com/EllangoK/ComfyUI-post-processing-nodes "$comfyui_path"/custom_nodes OFF # ComfyUI的后处理节点集合，可实现各种酷炫的图像效果
__term_sd_task_pre_ext_28 git_clone_repository ${github_mirror} https://github.com/LEv145/images-grid-comfy-plugin "$comfyui_path"/custom_nodes ON # XYZPlot图生成
__term_sd_task_pre_ext_29 git_clone_repository ${github_mirror} https://github.com/biegert/ComfyUI-CLIPSeg "$comfyui_path"/custom_nodes OFF # 利用CLIPSeg模型根据文本提示为图像修复任务生成蒙版
__term_sd_task_pre_ext_30 git_clone_repository ${github_mirror} https://github.com/Jcd1230/rembg-comfyui-node "$comfyui_path"/custom_nodes OM # 背景去除
__term_sd_task_pre_ext_31 git_clone_repository ${github_mirror} https://github.com/TinyTerra/ComfyUI_tinyterraNodes "$comfyui_path"/custom_nodes OFF # ComfyUI的自定义节点
__term_sd_task_pre_ext_32 git_clone_repository ${github_mirror} https://github.com/guoyk93/yk-node-suite-comfyui "$comfyui_path"/custom_nodes OFF # ComfyUI的自定义节点
__term_sd_task_pre_ext_33 git_clone_repository ${github_mirror} https://github.com/comfyanonymous/ComfyUI_experiments "$comfyui_path"/custom_nodes ON # ComfyUI的一些实验性自定义节点
__term_sd_task_pre_ext_34 git_clone_repository ${github_mirror} https://github.com/gamert/ComfyUI_tagger "$comfyui_path"/custom_nodes OFF # 图片tag反推
__term_sd_task_pre_ext_35 git_clone_repository ${github_mirror} https://github.com/YinBailiang/MergeBlockWeighted_fo_ComfyUI "$comfyui_path"/custom_nodes OFF # 权重合并
__term_sd_task_pre_ext_36 git_clone_repository ${github_mirror} https://github.com/Kaharos94/ComfyUI-Saveaswebp "$comfyui_path"/custom_nodes OFF # 将生成的图片保存为webp格式
__term_sd_task_pre_ext_37 git_clone_repository ${github_mirror} https://github.com/trojblue/trNodes "$comfyui_path"/custom_nodes OFF # 通过蒙版混合两个图像
__term_sd_task_pre_ext_38 git_clone_repository ${github_mirror} https://github.com/city96/ComfyUI_NetDist "$comfyui_path"/custom_nodes OFF # 在多个本地GPU/联网机器上运行ComfyUI工作流程
__term_sd_task_pre_ext_39 git_clone_repository ${github_mirror} https://github.com/SLAPaper/ComfyUI-Image-Selector "$comfyui_path"/custom_nodes OFF # 从批处理中选择一个或多个图像
__term_sd_task_pre_ext_40 git_clone_repository ${github_mirror} https://github.com/strimmlarn/ComfyUI-Strimmlarns-Aesthetic-Score "$comfyui_path"/custom_nodes OFF # 图片美学评分
__term_sd_task_pre_ext_41 git_clone_repository --submod ${github_mirror} https://github.com/ssitu/ComfyUI_UltimateSDUpscale "$comfyui_path"/custom_nodes ON # 图片放大
__term_sd_task_pre_ext_42 git_clone_repository ${github_mirror} https://github.com/space-nuko/ComfyUI-Disco-Diffusion "$comfyui_path"/custom_nodes OFF # DiscoDiffusion模块
__term_sd_task_pre_ext_43 git_clone_repository ${github_mirror} https://github.com/Bikecicle/ComfyUI-Waveform-Extensions "$comfyui_path"/custom_nodes OFF # 包括姿势，翻译等节点
__term_sd_task_pre_ext_44 git_clone_repository ${github_mirror} https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet "$comfyui_path"/custom_nodes ON # 提示词翻译节点
__term_sd_task_pre_ext_45 git_clone_repository ${github_mirror} https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION "$comfyui_path"/custom_nodes ON # ComfyUI的翻译扩展
__term_sd_task_pre_ext_46 git_clone_repository ${github_mirror} https://github.com/Stability-AI/stability-ComfyUI-nodes "$comfyui_path"/custom_nodes ON # Stability-AI自定义节点支持
__term_sd_task_pre_ext_47 git_clone_repository ${github_mirror} https://github.com/hustille/ComfyUI_Fooocus_KSampler "$comfyui_path"/custom_nodes OFF # 添加fooocus噪声生成器支持
__term_sd_task_pre_ext_48 git_clone_repository ${github_mirror} https://github.com/WASasquatch/FreeU_Advanced "$comfyui_path"/custom_nodes ON # 生图加速
__term_sd_task_pre_ext_49 git_clone_repository ${github_mirror} https://github.com/kohya-ss/ControlNet-LLLite-ComfyUI "$comfyui_path"/custom_nodes ON # 添加ControlNet-LLLite支持
__term_sd_task_pre_ext_50 git_clone_repository ${github_mirror} https://github.com/Acly/comfyui-tooling-nodes "$comfyui_path"/custom_nodes OFF # 使用ComfyUI作为外部工具后端的节点
__term_sd_task_pre_ext_51 git_clone_repository ${github_mirror} https://github.com/jags111/efficiency-nodes-comfyui "$comfyui_path"/custom_nodes ON # 自定义节点的集合，可帮助简化工作流程并减少节点总数
__term_sd_task_pre_ext_52 git_clone_repository ${github_mirror} https://github.com/laksjdjf/cd-tuner_negpip-ComfyUI "$comfyui_path"/custom_nodes OFF # 解决tag的强污染，效果比cutoff好
__term_sd_task_pre_ext_53 git_clone_repository ${github_mirror} https://github.com/yolain/ComfyUI-Easy-Use "$comfyui_path"/custom_nodes OFF # 添加ControlNet-LLLite的支持
__term_sd_task_pre_ext_54 git_clone_repository ${github_mirror} https://github.com/twri/sdxl_prompt_styler "$comfyui_path"/custom_nodes OFF # SDXL提示词风格预设节点
__term_sd_task_pre_ext_55 git_clone_repository ${github_mirror} https://github.com/11cafe/comfyui-workspace-manager "$comfyui_path"/custom_nodes ON # 工作流管理器
__term_sd_task_pre_ext_56 git_clone_repository ${github_mirror} https://github.com/talesofai/comfyui-browser "$comfyui_path"/custom_nodes OFF # 查看和管理ComfyUI的所有输出文件/工作流，并且添加收藏方便随时调用
__term_sd_task_pre_ext_57 git_clone_repository ${github_mirror} https://github.com/chrisgoringe/cg-use-everywhere "$comfyui_path"/custom_nodes OFF # 节点整理工具
__term_sd_task_pre_ext_58 git_clone_repository ${github_mirror} https://github.com/ltdrdata/ComfyUI-Inspire-Pack "$comfyui_path"/custom_nodes ON # 整合多功能的节点
__term_sd_task_pre_ext_59 git_clone_repository ${github_mirror} https://github.com/mcmonkeyprojects/sd-dynamic-thresholding "$comfyui_path"/custom_nodes OFF # 解决使用更高的CFGScale而出现颜色问题
__term_sd_task_pre_ext_60 git_clone_repository ${github_mirror} https://github.com/rgthree/rgthree-comfy "$comfyui_path"/custom_nodes OFF # 节点管道工具
__term_sd_task_pre_ext_61 git_clone_repository ${github_mirror} https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes "$comfyui_path"/custom_nodes ON # ComfyUI自定义节点合集
__term_sd_task_pre_ext_62 git_clone_repository ${github_mirror} https://github.com/FizzleDorf/ComfyUI_FizzNodes "$comfyui_path"/custom_nodes ON # 视频制作节点
__term_sd_task_pre_ext_63 git_clone_repository ${github_mirror} https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet "$comfyui_path"/custom_nodes ON # Controlnet节点，包含各种Controlnet调节选项
__term_sd_task_pre_ext_64 git_clone_repository ${github_mirror} https://github.com/WASasquatch/PowerNoiseSuite "$comfyui_path"/custom_nodes ON # 噪声生成节点
__term_sd_task_pre_ext_65 git_clone_repository ${github_mirror} https://github.com/crystian/ComfyUI-Crystools "$comfyui_path"/custom_nodes ON # 资源监视器
__term_sd_task_pre_ext_66 git_clone_repository ${github_mirror} https://github.com/chflame163/ComfyUI_LayerStyle "$comfyui_path"/custom_nodes OFF # 图层和蒙版合成节点
__term_sd_task_pre_ext_67 git_clone_repository ${github_mirror} https://github.com/Nuked88/ComfyUI-N-Sidebar "$comfyui_path"/custom_nodes OFF # 节点快捷收藏整理工具
__term_sd_task_pre_ext_68 git_clone_repository ${github_mirror} https://github.com/brianfitzgerald/style_aligned_comfy "$comfyui_path"/custom_nodes OFF # 使用StyleAligned保持多张图片一致性
__term_sd_task_pre_ext_69 git_clone_repository ${github_mirror} https://github.com/flowtyone/ComfyUI-Flowty-TripoSR "$comfyui_path"/custom_nodes OFF # 添加TripoSR支持
__term_sd_task_pre_ext_70 git_clone_repository ${github_mirror} https://github.com/city96/ComfyUI_ExtraModels "$comfyui_path"/custom_nodes OFF #
__term_sd_task_pre_ext_71 git_clone_repository ${github_mirror} https://github.com/kijai/ComfyUI-SUPIR "$comfyui_path"/custom_nodes OFF # 添加DiT，PixArt，T5和一些自定义VAE模型的支持
__term_sd_task_pre_ext_72 git_clone_repository ${github_mirror} https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM "$comfyui_path"/custom_nodes OFF # 对象检测与分割
__term_sd_task_pre_ext_73 git_clone_repository ${github_mirror} https://github.com/ZHO-ZHO-ZHO/ComfyUI-PixArt-alpha-Diffusers "$comfyui_path"/custom_nodes OFF # 添加PixArt-α模型支持
__term_sd_task_pre_ext_74 git_clone_repository ${github_mirror} https://github.com/ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO "$comfyui_path"/custom_nodes OFF # 对象蒙版生成
__term_sd_task_pre_ext_75 git_clone_repository ${github_mirror} https://github.com/ZHO-ZHO-ZHO/ComfyUI-DepthFM "$comfyui_path"/custom_nodes OFF # 深度图生成
__term_sd_task_pre_ext_76 git_clone_repository ${github_mirror} https://github.com/ZHO-ZHO-ZHO/ComfyUI-APISR "$comfyui_path"/custom_nodes OFF # 图像放大
__term_sd_task_pre_ext_77 git_clone_repository ${github_mirror} https://github.com/ZHO-ZHO-ZHO/ComfyUI-ArtGallery "$comfyui_path"/custom_nodes OFF # 可视化风格提示词预设选择
__term_sd_task_pre_ext_78 git_clone_repository ${github_mirror} https://github.com/ZHO-ZHO-ZHO/ComfyUI-BRIA_AI-RMBG "$comfyui_path"/custom_nodes OFF # 图片背景移除
__term_sd_task_pre_ext_79 git_clone_repository ${github_mirror} https://github.com/ZHO-ZHO-ZHO/ComfyUI-I2VGenXL "$comfyui_path"/custom_nodes OFF # 添加I2VGenXL的支持
__term_sd_task_pre_ext_80 git_clone_repository ${github_mirror} https://github.com/ZHO-ZHO-ZHO/ComfyUI-SegMoE "$comfyui_path"/custom_nodes OFF # 添加SegMoE的支持
__term_sd_task_pre_ext_81 git_clone_repository ${github_mirror} https://github.com/ZHO-ZHO-ZHO/ComfyUI-AnyText "$comfyui_path"/custom_nodes OFF # 添加AnyText的支持
__term_sd_task_pre_ext_82 git_clone_repository ${github_mirror} https://github.com/Clybius/ComfyUI-Extra-Samplers "$comfyui_path"/custom_nodes OFF # 添加额外的采样器
__term_sd_task_pre_ext_83 git_clone_repository ${github_mirror} https://github.com/blepping/ComfyUI-sonar "$comfyui_path"/custom_nodes OFF # 添加sonar采样器
__term_sd_task_pre_ext_84 git_clone_repository ${github_mirror} https://github.com/ssitu/ComfyUI_restart_sampling "$comfyui_path"/custom_nodes OFF # 添加restart采样器
__term_sd_task_pre_ext_85 git_clone_repository ${github_mirror} https://github.com/kijai/ComfyUI-Diffusers-X-Adapter "$comfyui_path"/custom_nodes OFF # 添加x-adapter支持
__term_sd_task_pre_ext_86 git_clone_repository ${github_mirror} https://github.com/nullquant/ComfyUI-BrushNet "$comfyui_path"/custom_nodes OFF # 添加brushnet支持，用于精准重绘
__term_sd_task_pre_ext_87 git_clone_repository ${github_mirror} https://github.com/kijai/ComfyUI-BrushNet-Wrapper "$comfyui_path"/custom_nodes OFF # 添加brushnet支持，用于精准重绘
__term_sd_task_pre_ext_88 git_clone_repository ${github_mirror} https://github.com/Koishi-Star/Euler-Smea-Dyn-Sampler "$comfyui_path"/custom_nodes OFF # 添加Eular-SMEA-Dy采样算法
__term_sd_task_pre_ext_89 git_clone_repository ${github_mirror} https://github.com/blepping/ComfyUI-bleh "$comfyui_path"/custom_nodes OFF # 改进hypertile和deepshrink节点，提供更好的生成预览算法
__term_sd_task_pre_ext_90 git_clone_repository ${github_mirror} https://github.com/dfl/comfyui-tcd-scheduler "$comfyui_path"/custom_nodes OFF # 添加TCD采样器
__term_sd_task_pre_ext_91 git_clone_repository ${github_mirror} https://github.com/huchenlei/ComfyUI-IC-Light-Native "$comfyui_path"/custom_nodes OFF # 添加ic-light支持
