__term_sd_task_pre_ext_1 git_clone_repository https://github.com/Fannovel16/comfyui_controlnet_aux "${COMFYUI_PATH}"/custom_nodes ON # ComfyUI的ControlNet辅助预处理器
__term_sd_task_pre_ext_2 git_clone_repository https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved "${COMFYUI_PATH}"/custom_nodes ON # 视频生成节点
__term_sd_task_pre_ext_3 git_clone_repository https://github.com/cubiq/ComfyUI_IPAdapter_plus "${COMFYUI_PATH}"/custom_nodes ON # 添加ip-adapt支持
__term_sd_task_pre_ext_4 git_clone_repository https://github.com/ltdrdata/ComfyUI-Impact-Pack "${COMFYUI_PATH}"/custom_nodes ON # 通过检测器、细节器、升频器、管道等方便地增强图像
__term_sd_task_pre_ext_5 git_clone_repository https://github.com/kijai/ComfyUI-Marigold "${COMFYUI_PATH}"/custom_nodes ON # 深度图生成节点
__term_sd_task_pre_ext_6 git_clone_repository https://github.com/pythongosssss/ComfyUI-WD14-Tagger "${COMFYUI_PATH}"/custom_nodes ON # 图片标签反推
__term_sd_task_pre_ext_7 git_clone_repository https://github.com/huchenlei/ComfyUI-layerdiffusion "${COMFYUI_PATH}"/custom_nodes OFF # LayerDiffusion节点
__term_sd_task_pre_ext_8 git_clone_repository https://github.com/huchenlei/ComfyUI_DanTagGen "${COMFYUI_PATH}"/custom_nodes OFF # 使用Danboou风格对tag进行润色，使出图效果更好，内容更丰富
__term_sd_task_pre_ext_9 git_clone_repository https://github.com/gameltb/Comfyui-StableSR "${COMFYUI_PATH}"/custom_nodes OFF # 图片放大
__term_sd_task_pre_ext_10 git_clone_repository https://github.com/KohakuBlueleaf/z-tipo-extension "${COMFYUI_PATH}"/custom_nodes OFF # 使用danbooru-tag和自然语言对提示词进行润色，增强模型的出图效果
__term_sd_task_pre_ext_11 git_clone_repository https://github.com/WASasquatch/was-node-suite-comfyui "${COMFYUI_PATH}"/custom_nodes OFF # 适用于ComfyUI的广泛节点套件，包含190多个新节点
__term_sd_task_pre_ext_12 git_clone_repository https://github.com/BlenderNeko/ComfyUI_Cutoff "${COMFYUI_PATH}"/custom_nodes OFF # 解决tag污染
__term_sd_task_pre_ext_13 git_clone_repository https://github.com/BlenderNeko/ComfyUI_TiledKSampler "${COMFYUI_PATH}"/custom_nodes ON # ComfyUI的平铺采样器
__term_sd_task_pre_ext_14 git_clone_repository https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb "${COMFYUI_PATH}"/custom_nodes OFF # 高级剪辑文本编码，可让您选择解释提示权重的方式
__term_sd_task_pre_ext_15 git_clone_repository https://github.com/BlenderNeko/ComfyUI_Noise "${COMFYUI_PATH}"/custom_nodes OFF # 噪声控制
__term_sd_task_pre_ext_16 git_clone_repository https://github.com/Davemane42/ComfyUI_Dave_CustomNode "${COMFYUI_PATH}"/custom_nodes OFF # 图片区域控制
__term_sd_task_pre_ext_17 git_clone_repository https://github.com/ltdrdata/ComfyUI-Manager "${COMFYUI_PATH}"/custom_nodes ON # 自定义节点管理器
__term_sd_task_pre_ext_18 git_clone_repository https://github.com/Zuellni/ComfyUI-Custom-Nodes "${COMFYUI_PATH}"/custom_nodes OFF # ComfyUI的自定义节点
__term_sd_task_pre_ext_19 git_clone_repository https://github.com/pythongosssss/ComfyUI-Custom-Scripts "${COMFYUI_PATH}"/custom_nodes ON # ComfyUI的增强功能
__term_sd_task_pre_ext_20 git_clone_repository https://github.com/xXAdonesXx/NodeGPT "${COMFYUI_PATH}"/custom_nodes OFF # 使用GPT辅助生图
__term_sd_task_pre_ext_21 git_clone_repository https://github.com/Derfuu/Derfuu_ComfyUI_ModdedNodes "${COMFYUI_PATH}"/custom_nodes ON # 方程式节点
__term_sd_task_pre_ext_22 git_clone_repository https://github.com/lilly1987/ComfyUI_node_Lilly "${COMFYUI_PATH}"/custom_nodes OFF # 通配符文本工具
__term_sd_task_pre_ext_23 git_clone_repository https://github.com/hnmr293/ComfyUI-nodes-hnmr "${COMFYUI_PATH}"/custom_nodes OFF # 包含X/Y/Z-plotX/Y/Z，合并，潜在可视化，采样等节点
__term_sd_task_pre_ext_24 git_clone_repository https://github.com/diontimmer/ComfyUI-Vextra-Nodes "${COMFYUI_PATH}"/custom_nodes OFF # 包含像素排序，交换颜色模式，拼合颜色等节点
__term_sd_task_pre_ext_25 git_clone_repository https://github.com/omar92/ComfyUI-QualityOfLifeSuit_Omar92 "${COMFYUI_PATH}"/custom_nodes OFF # 包含GPT辅助标签生成，字符串操作，latentTools等节点
__term_sd_task_pre_ext_26 git_clone_repository https://github.com/Fannovel16/FN16-ComfyUI-nodes "${COMFYUI_PATH}"/custom_nodes OFF # ComfyUI自定义节点集合
__term_sd_task_pre_ext_27 git_clone_repository https://github.com/BadCafeCode/masquerade-nodes-comfyui "${COMFYUI_PATH}"/custom_nodes OFF # ComfyUI掩码相关节点
__term_sd_task_pre_ext_28 git_clone_repository https://github.com/EllangoK/ComfyUI-post-processing-nodes "${COMFYUI_PATH}"/custom_nodes OFF # ComfyUI的后处理节点集合，可实现各种酷炫的图像效果
__term_sd_task_pre_ext_29 git_clone_repository https://github.com/LEv145/images-grid-comfy-plugin "${COMFYUI_PATH}"/custom_nodes ON # XYZPlot图生成
__term_sd_task_pre_ext_30 git_clone_repository https://github.com/biegert/ComfyUI-CLIPSeg "${COMFYUI_PATH}"/custom_nodes OFF # 利用CLIPSeg模型根据文本提示为图像修复任务生成蒙版
__term_sd_task_pre_ext_31 git_clone_repository https://github.com/Jcd1230/rembg-comfyui-node "${COMFYUI_PATH}"/custom_nodes OFF # 背景去除
__term_sd_task_pre_ext_32 git_clone_repository https://github.com/TinyTerra/ComfyUI_tinyterraNodes "${COMFYUI_PATH}"/custom_nodes OFF # ComfyUI的自定义节点
__term_sd_task_pre_ext_33 git_clone_repository https://github.com/guoyk93/yk-node-suite-comfyui "${COMFYUI_PATH}"/custom_nodes OFF # ComfyUI的自定义节点
__term_sd_task_pre_ext_34 git_clone_repository https://github.com/comfyanonymous/ComfyUI_experiments "${COMFYUI_PATH}"/custom_nodes ON # ComfyUI的一些实验性自定义节点
__term_sd_task_pre_ext_35 git_clone_repository https://github.com/gamert/ComfyUI_tagger "${COMFYUI_PATH}"/custom_nodes OFF # 图片tag反推
__term_sd_task_pre_ext_36 git_clone_repository https://github.com/YinBailiang/MergeBlockWeighted_fo_ComfyUI "${COMFYUI_PATH}"/custom_nodes OFF # 权重合并
__term_sd_task_pre_ext_37 git_clone_repository https://github.com/Kaharos94/ComfyUI-Saveaswebp "${COMFYUI_PATH}"/custom_nodes OFF # 将生成的图片保存为webp格式
__term_sd_task_pre_ext_38 git_clone_repository https://github.com/trojblue/trNodes "${COMFYUI_PATH}"/custom_nodes OFF # 通过蒙版混合两个图像
__term_sd_task_pre_ext_39 git_clone_repository https://github.com/city96/ComfyUI_NetDist "${COMFYUI_PATH}"/custom_nodes OFF # 在多个本地GPU/联网机器上运行ComfyUI工作流程
__term_sd_task_pre_ext_40 git_clone_repository https://github.com/SLAPaper/ComfyUI-Image-Selector "${COMFYUI_PATH}"/custom_nodes OFF # 从批处理中选择一个或多个图像
__term_sd_task_pre_ext_41 git_clone_repository https://github.com/strimmlarn/ComfyUI-Strimmlarns-Aesthetic-Score "${COMFYUI_PATH}"/custom_nodes OFF # 图片美学评分
__term_sd_task_pre_ext_42 git_clone_repository https://github.com/ssitu/ComfyUI_UltimateSDUpscale "${COMFYUI_PATH}"/custom_nodes ON # 图片放大
__term_sd_task_pre_ext_43 git_clone_repository https://github.com/space-nuko/ComfyUI-Disco-Diffusion "${COMFYUI_PATH}"/custom_nodes OFF # DiscoDiffusion模块
__term_sd_task_pre_ext_44 git_clone_repository https://github.com/Bikecicle/ComfyUI-Waveform-Extensions "${COMFYUI_PATH}"/custom_nodes OFF # 包括姿势，翻译等节点
__term_sd_task_pre_ext_45 git_clone_repository https://github.com/AlekPet/ComfyUI_Custom_Nodes_AlekPet "${COMFYUI_PATH}"/custom_nodes ON # 提示词翻译节点
__term_sd_task_pre_ext_46 git_clone_repository https://github.com/AIGODLIKE/AIGODLIKE-COMFYUI-TRANSLATION "${COMFYUI_PATH}"/custom_nodes ON # ComfyUI的翻译扩展
__term_sd_task_pre_ext_47 git_clone_repository https://github.com/Stability-AI/stability-ComfyUI-nodes "${COMFYUI_PATH}"/custom_nodes ON # Stability-AI自定义节点支持
__term_sd_task_pre_ext_48 git_clone_repository https://github.com/hustille/ComfyUI_Fooocus_KSampler "${COMFYUI_PATH}"/custom_nodes OFF # 添加fooocus噪声生成器支持
__term_sd_task_pre_ext_49 git_clone_repository https://github.com/WASasquatch/FreeU_Advanced "${COMFYUI_PATH}"/custom_nodes OFF # 生图加速
__term_sd_task_pre_ext_50 git_clone_repository https://github.com/kohya-ss/ControlNet-LLLite-ComfyUI "${COMFYUI_PATH}"/custom_nodes ON # 添加ControlNet-LLLite支持
__term_sd_task_pre_ext_51 git_clone_repository https://github.com/Acly/comfyui-tooling-nodes "${COMFYUI_PATH}"/custom_nodes OFF # 使用ComfyUI作为外部工具后端的节点
__term_sd_task_pre_ext_52 git_clone_repository https://github.com/jags111/efficiency-nodes-comfyui "${COMFYUI_PATH}"/custom_nodes ON # 自定义节点的集合，可帮助简化工作流程并减少节点总数
__term_sd_task_pre_ext_53 git_clone_repository https://github.com/laksjdjf/cd-tuner_negpip-ComfyUI "${COMFYUI_PATH}"/custom_nodes OFF # 解决tag的强污染，效果比cutoff好
__term_sd_task_pre_ext_54 git_clone_repository https://github.com/yolain/ComfyUI-Easy-Use "${COMFYUI_PATH}"/custom_nodes OFF # 自定义节点集合
__term_sd_task_pre_ext_55 git_clone_repository https://github.com/twri/sdxl_prompt_styler "${COMFYUI_PATH}"/custom_nodes OFF # SDXL提示词风格预设节点
__term_sd_task_pre_ext_56 git_clone_repository https://github.com/11cafe/comfyui-workspace-manager "${COMFYUI_PATH}"/custom_nodes ON # 工作流管理器
__term_sd_task_pre_ext_57 git_clone_repository https://github.com/talesofai/comfyui-browser "${COMFYUI_PATH}"/custom_nodes ON # 查看和管理ComfyUI的所有输出文件/工作流，并且添加收藏方便随时调用
__term_sd_task_pre_ext_58 git_clone_repository https://github.com/chrisgoringe/cg-use-everywhere "${COMFYUI_PATH}"/custom_nodes OFF # 节点整理工具
__term_sd_task_pre_ext_59 git_clone_repository https://github.com/ltdrdata/ComfyUI-Inspire-Pack "${COMFYUI_PATH}"/custom_nodes ON # 整合多功能的节点
__term_sd_task_pre_ext_60 git_clone_repository https://github.com/mcmonkeyprojects/sd-dynamic-thresholding "${COMFYUI_PATH}"/custom_nodes OFF # 解决使用更高的CFGScale而出现颜色问题
__term_sd_task_pre_ext_61 git_clone_repository https://github.com/rgthree/rgthree-comfy "${COMFYUI_PATH}"/custom_nodes OFF # 节点管道工具
__term_sd_task_pre_ext_62 git_clone_repository https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes "${COMFYUI_PATH}"/custom_nodes ON # ComfyUI自定义节点合集
__term_sd_task_pre_ext_63 git_clone_repository https://github.com/FizzleDorf/ComfyUI_FizzNodes "${COMFYUI_PATH}"/custom_nodes ON # 视频制作节点
__term_sd_task_pre_ext_64 git_clone_repository https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet "${COMFYUI_PATH}"/custom_nodes ON # Controlnet节点，包含各种Controlnet调节选项
__term_sd_task_pre_ext_65 git_clone_repository https://github.com/WASasquatch/PowerNoiseSuite "${COMFYUI_PATH}"/custom_nodes ON # 噪声生成节点
__term_sd_task_pre_ext_66 git_clone_repository https://github.com/crystian/ComfyUI-Crystools "${COMFYUI_PATH}"/custom_nodes ON # 资源监视器
__term_sd_task_pre_ext_67 git_clone_repository https://github.com/chflame163/ComfyUI_LayerStyle "${COMFYUI_PATH}"/custom_nodes OFF # 图层和蒙版合成节点
__term_sd_task_pre_ext_68 git_clone_repository https://github.com/Nuked88/ComfyUI-N-Sidebar "${COMFYUI_PATH}"/custom_nodes OFF # 节点快捷收藏整理工具
__term_sd_task_pre_ext_69 git_clone_repository https://github.com/brianfitzgerald/style_aligned_comfy "${COMFYUI_PATH}"/custom_nodes OFF # 使用StyleAligned保持多张图片一致性
__term_sd_task_pre_ext_70 git_clone_repository https://github.com/flowtyone/ComfyUI-Flowty-TripoSR "${COMFYUI_PATH}"/custom_nodes OFF # 添加TripoSR支持
__term_sd_task_pre_ext_71 git_clone_repository https://github.com/city96/ComfyUI_ExtraModels "${COMFYUI_PATH}"/custom_nodes OFF # 添加DiT，PixArt，HunYuanDiT，MiaoBi模型的支持
__term_sd_task_pre_ext_72 git_clone_repository https://github.com/kijai/ComfyUI-SUPIR "${COMFYUI_PATH}"/custom_nodes OFF # 添加DiT，PixArt，T5和一些自定义VAE模型的支持
__term_sd_task_pre_ext_73 git_clone_repository https://github.com/ZHO-ZHO-ZHO/ComfyUI-YoloWorld-EfficientSAM "${COMFYUI_PATH}"/custom_nodes OFF # 对象检测与分割
__term_sd_task_pre_ext_74 git_clone_repository https://github.com/ZHO-ZHO-ZHO/ComfyUI-PixArt-alpha-Diffusers "${COMFYUI_PATH}"/custom_nodes OFF # 添加PixArt-α模型支持
__term_sd_task_pre_ext_75 git_clone_repository https://github.com/ZHO-ZHO-ZHO/ComfyUI-BiRefNet-ZHO "${COMFYUI_PATH}"/custom_nodes OFF # 对象蒙版生成
__term_sd_task_pre_ext_76 git_clone_repository https://github.com/ZHO-ZHO-ZHO/ComfyUI-DepthFM "${COMFYUI_PATH}"/custom_nodes OFF # 深度图生成
__term_sd_task_pre_ext_77 git_clone_repository https://github.com/ZHO-ZHO-ZHO/ComfyUI-APISR "${COMFYUI_PATH}"/custom_nodes OFF # 图像放大
__term_sd_task_pre_ext_78 git_clone_repository https://github.com/ZHO-ZHO-ZHO/ComfyUI-ArtGallery "${COMFYUI_PATH}"/custom_nodes OFF # 可视化风格提示词预设选择
__term_sd_task_pre_ext_79 git_clone_repository https://github.com/ZHO-ZHO-ZHO/ComfyUI-BRIA_AI-RMBG "${COMFYUI_PATH}"/custom_nodes OFF # 图片背景移除
__term_sd_task_pre_ext_80 git_clone_repository https://github.com/ZHO-ZHO-ZHO/ComfyUI-I2VGenXL "${COMFYUI_PATH}"/custom_nodes OFF # 添加I2VGenXL的支持
__term_sd_task_pre_ext_81 git_clone_repository https://github.com/ZHO-ZHO-ZHO/ComfyUI-SegMoE "${COMFYUI_PATH}"/custom_nodes OFF # 添加SegMoE的支持
__term_sd_task_pre_ext_82 git_clone_repository https://github.com/ZHO-ZHO-ZHO/ComfyUI-AnyText "${COMFYUI_PATH}"/custom_nodes OFF # 添加AnyText的支持
__term_sd_task_pre_ext_83 git_clone_repository https://github.com/Clybius/ComfyUI-Extra-Samplers "${COMFYUI_PATH}"/custom_nodes OFF # 添加额外的采样器
__term_sd_task_pre_ext_84 git_clone_repository https://github.com/blepping/ComfyUI-sonar "${COMFYUI_PATH}"/custom_nodes OFF # 添加sonar采样器
__term_sd_task_pre_ext_85 git_clone_repository https://github.com/ssitu/ComfyUI_restart_sampling "${COMFYUI_PATH}"/custom_nodes OFF # 添加restart采样器
__term_sd_task_pre_ext_86 git_clone_repository https://github.com/kijai/ComfyUI-Diffusers-X-Adapter "${COMFYUI_PATH}"/custom_nodes OFF # 添加x-adapter支持
__term_sd_task_pre_ext_87 git_clone_repository https://github.com/nullquant/ComfyUI-BrushNet "${COMFYUI_PATH}"/custom_nodes OFF # 添加brushnet支持，用于精准重绘
__term_sd_task_pre_ext_88 git_clone_repository https://github.com/kijai/ComfyUI-BrushNet-Wrapper "${COMFYUI_PATH}"/custom_nodes OFF # 添加brushnet支持，用于精准重绘
__term_sd_task_pre_ext_89 git_clone_repository https://github.com/Koishi-Star/Euler-Smea-Dyn-Sampler "${COMFYUI_PATH}"/custom_nodes OFF # 添加Eular-SMEA-Dy采样算法
__term_sd_task_pre_ext_90 git_clone_repository https://github.com/blepping/ComfyUI-bleh "${COMFYUI_PATH}"/custom_nodes OFF # 改进hypertile和deepshrink节点，提供更好的生成预览算法
__term_sd_task_pre_ext_91 git_clone_repository https://github.com/dfl/comfyui-tcd-scheduler "${COMFYUI_PATH}"/custom_nodes OFF # 添加TCD采样器
__term_sd_task_pre_ext_92 git_clone_repository https://github.com/huchenlei/ComfyUI-IC-Light-Native "${COMFYUI_PATH}"/custom_nodes OFF # 添加ic-light支持
__term_sd_task_pre_ext_93 git_clone_repository https://github.com/Acly/comfyui-inpaint-nodes "${COMFYUI_PATH}"/custom_nodes OFF # 添加fooocus的重绘模型支持
__term_sd_task_pre_ext_94 git_clone_repository https://github.com/comfyanonymous/ComfyUI_TensorRT "${COMFYUI_PATH}"/custom_nodes OFF # 添加TensorRT加速
__term_sd_task_pre_ext_95 git_clone_repository https://github.com/Haoming02/comfyui-diffusion-cg "${COMFYUI_PATH}"/custom_nodes OFF # 在潜空间张量范围执行颜色分级，改进出图的效果
__term_sd_task_pre_ext_96 git_clone_repository https://github.com/Haoming02/comfyui-floodgate "${COMFYUI_PATH}"/custom_nodes OFF # 节点控制
__term_sd_task_pre_ext_97 git_clone_repository https://github.com/Haoming02/comfyui-resharpen "${COMFYUI_PATH}"/custom_nodes OFF # 为主体生成用于修复的蒙版，使背景与主体融合更融洽
__term_sd_task_pre_ext_98 git_clone_repository https://github.com/Haoming02/comfyui-menu-anchor "${COMFYUI_PATH}"/custom_nodes OFF # 界面按钮位置修改
__term_sd_task_pre_ext_99 git_clone_repository https://github.com/Haoming02/comfyui-tab-handler "${COMFYUI_PATH}"/custom_nodes OFF # 将tab按键的行为修改成聚焦文本区域
__term_sd_task_pre_ext_100 git_clone_repository https://github.com/Haoming02/comfyui-clear-screen "${COMFYUI_PATH}"/custom_nodes OFF # 清理控制台输出
__term_sd_task_pre_ext_101 git_clone_repository https://github.com/Haoming02/comfyui-node-beautify "${COMFYUI_PATH}"/custom_nodes OFF # 节点美化
__term_sd_task_pre_ext_102 git_clone_repository https://github.com/Haoming02/comfyui-prompt-format "${COMFYUI_PATH}"/custom_nodes OFF # 提示词格式化工具
__term_sd_task_pre_ext_103 git_clone_repository https://github.com/huchenlei/ComfyUI_omost "${COMFYUI_PATH}"/custom_nodes OFF # 添加omost模型支持
__term_sd_task_pre_ext_104 git_clone_repository https://github.com/TheMistoAI/ComfyUI-Anyline "${COMFYUI_PATH}"/custom_nodes OFF # 添加anyline预处理器
__term_sd_task_pre_ext_105 git_clone_repository https://github.com/shiimizu/ComfyUI-TiledDiffusion "${COMFYUI_PATH}"/custom_nodes ON # TiledDiffusion分块放大工具
__term_sd_task_pre_ext_106 git_clone_repository https://github.com/kijai/ComfyUI-DynamiCrafterWrapper "${COMFYUI_PATH}"/custom_nodes OFF # ToonCrafter节点
__term_sd_task_pre_ext_107 git_clone_repository https://github.com/thisjam/comfyui-sixgod_prompt "${COMFYUI_PATH}"/custom_nodes OFF # 提示词辅助工具
__term_sd_task_pre_ext_108 git_clone_repository https://github.com/huchenlei/ComfyUI_densediffusion "${COMFYUI_PATH}"/custom_nodes OFF # 使用DenseDiffusion进行分区控制
__term_sd_task_pre_ext_109 git_clone_repository https://github.com/huchenlei/omost_region_editor "${COMFYUI_PATH}"/custom_nodes OFF # omost区域提示词编辑器
__term_sd_task_pre_ext_110 git_clone_repository https://github.com/huchenlei/ComfyUI-openpose-editor "${COMFYUI_PATH}"/custom_nodes OFF # openpose编辑器
__term_sd_task_pre_ext_111 git_clone_repository https://github.com/kijai/ComfyUI-IC-Light "${COMFYUI_PATH}"/custom_nodes OFF # 添加lc-light支持
__term_sd_task_pre_ext_112 git_clone_repository https://github.com/kijai/ComfyUI-KJNodes "${COMFYUI_PATH}"/custom_nodes OFF # 自定义节点集合
__term_sd_task_pre_ext_113 git_clone_repository https://github.com/cubiq/ComfyUI_essentials "${COMFYUI_PATH}"/custom_nodes OFF # 自定义节点集合
__term_sd_task_pre_ext_114 git_clone_repository https://github.com/licyk/ComfyUI-Restart-Sampler "${COMFYUI_PATH}"/custom_nodes OFF # 为ComfyUI添加Restart采样算法
__term_sd_task_pre_ext_115 git_clone_repository https://github.com/licyk/ComfyUI-TCD-Sampler "${COMFYUI_PATH}"/custom_nodes OFF # 为ComfyUI添加TCD采样算法
__term_sd_task_pre_ext_116 git_clone_repository https://github.com/chrisgoringe/cg-noise "${COMFYUI_PATH}"/custom_nodes OFF # 添加变异种子支持
__term_sd_task_pre_ext_117 git_clone_repository https://github.com/googincheng/ComfyUX "${COMFYUI_PATH}"/custom_nodes OFF # 优化ComfyUI界面，使整理节点更方便
__term_sd_task_pre_ext_118 git_clone_repository https://github.com/ZHO-ZHO-ZHO/ComfyUI-UltraEdit-ZHO "${COMFYUI_PATH}"/custom_nodes OFF # 添加UltraEdit支持
__term_sd_task_pre_ext_119 git_clone_repository https://github.com/weilin9999/WeiLin-ComfyUI-prompt-all-in-one "${COMFYUI_PATH}"/custom_nodes OFF # Prompt-all-in-one-app项目的修改版本，能够在ComfyUI中创建节点使用tag功能
__term_sd_task_pre_ext_120 git_clone_repository https://github.com/city96/ComfyUI-GGUF "${COMFYUI_PATH}"/custom_nodes OFF # 为ComfyUI添加gguf格式模型的支持
__term_sd_task_pre_ext_121 git_clone_repository https://github.com/XLabs-AI/x-flux-comfyui "${COMFYUI_PATH}"/custom_nodes OFF # 添加xlabs的controlnet模型支持
__term_sd_task_pre_ext_122 git_clone_repository https://github.com/MakkiShizu/ComfyUI-Prompt-Wildcards "${COMFYUI_PATH}"/custom_nodes OFF # 添加提示词通配符支持
__term_sd_task_pre_ext_123 git_clone_repository https://github.com/chrisgoringe/cg-controller "${COMFYUI_PATH}"/custom_nodes OFF # 添加类似invokeai的节点整理控制
__term_sd_task_pre_ext_124 git_clone_repository https://github.com/Clybius/ComfyUI-Latent-Modifiers "${COMFYUI_PATH}"/custom_nodes OFF # 在Latent部分应用滤镜，调整出图效果
__term_sd_task_pre_ext_125 git_clone_repository https://github.com/BennyKok/comfyui-deploy "${COMFYUI_PATH}"/custom_nodes OFF # 将ComfyUI工作流生成API
__term_sd_task_pre_ext_126 git_clone_repository https://github.com/licyk/ComfyUI-HakuImg "${COMFYUI_PATH}"/custom_nodes OFF # 图像处理工具
__term_sd_task_pre_ext_127 git_clone_repository https://github.com/Repeerc/ComfyUI-flash-attention-rdna3-win-zluda "${COMFYUI_PATH}"/custom_nodes OFF # 为Windows下的ZLUDA添加FlashAttension支持
__term_sd_task_pre_ext_128 git_clone_repository https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node "${COMFYUI_PATH}"/custom_nodes OFF # 为blender添加comfyui支持
__term_sd_task_pre_ext_129 git_clone_repository https://github.com/florestefano1975/comfyui-portrait-master "${COMFYUI_PATH}"/custom_nodes OFF # 使用滑块调整描述人物的提示词
__term_sd_task_pre_ext_130 git_clone_repository https://github.com/Extraltodeus/sigmas_tools_and_the_golden_scheduler "${COMFYUI_PATH}"/custom_nodes OFF # 调整调度器
__term_sd_task_pre_ext_131 git_clone_repository https://github.com/ssitu/ComfyUI_fabric "${COMFYUI_PATH}"/custom_nodes OFF # 基于注意力的参考图像调节
__term_sd_task_pre_ext_132 git_clone_repository https://github.com/Ttl/ComfyUi_NNLatentUpscale "${COMFYUI_PATH}"/custom_nodes OFF # 使用小型神经网络快速放大潜空间图像
__term_sd_task_pre_ext_133 git_clone_repository https://github.com/badjeff/comfyui_lora_tag_loader "${COMFYUI_PATH}"/custom_nodes OFF # 使用提示词调用LoRA模型
