__term_sd_task_pre_ext_38 term_sd_echo "下载controlnet模型中"
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/cldm_v15.yaml ./ComfyUI/models/controlnet cldm_v15.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/cldm_v21.yaml ./ComfyUI/models/controlnet cldm_v21.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_canny.yaml ./ComfyUI/models/controlnet control_sd15_canny.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_depth.yaml ./ComfyUI/models/controlnet control_sd15_depth.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_hed.yaml ./ComfyUI/models/controlnet control_sd15_hed.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_mlsd.yaml ./ComfyUI/models/controlnet control_sd15_mlsd.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_normal.yaml ./ComfyUI/models/controlnet control_sd15_normal.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_openpose.yaml ./ComfyUI/models/controlnet control_sd15_openpose.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_scribble.yaml ./ComfyUI/models/controlnet control_sd15_scribble.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_sd15_seg.yaml ./ComfyUI/models/controlnet control_sd15_seg.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11e_sd15_ip2p_fp16.safetensors ./ComfyUI/models/controlnet control_v11e_sd15_ip2p_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11e_sd15_ip2p_fp16.yaml ./ComfyUI/models/controlnet control_v11e_sd15_ip2p_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11e_sd15_shuffle_fp16.safetensors ./ComfyUI/models/controlnet control_v11e_sd15_shuffle_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11e_sd15_shuffle_fp16.yaml ./ComfyUI/models/controlnet control_v11e_sd15_shuffle_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11f1e_sd15_tile_fp16.safetensors ./ComfyUI/models/controlnet control_v11f1e_sd15_tile_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11f1e_sd15_tile_fp16.yaml ./ComfyUI/models/controlnet control_v11f1e_sd15_tile_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11f1p_sd15_depth_fp16.safetensors ./ComfyUI/models/controlnet control_v11f1p_sd15_depth_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11f1p_sd15_depth_fp16.yaml ./ComfyUI/models/controlnet control_v11f1p_sd15_depth_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_canny_fp16.safetensors ./ComfyUI/models/controlnet control_v11p_sd15_canny_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_canny_fp16.yaml ./ComfyUI/models/controlnet control_v11p_sd15_canny_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_inpaint_fp16.safetensors ./ComfyUI/models/controlnet control_v11p_sd15_inpaint_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_inpaint_fp16.yaml ./ComfyUI/models/controlnet control_v11p_sd15_inpaint_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_lineart_fp16.safetensors ./ComfyUI/models/controlnet control_v11p_sd15_lineart_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_lineart_fp16.yaml ./ComfyUI/models/controlnet control_v11p_sd15_lineart_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_mlsd_fp16.safetensors ./ComfyUI/models/controlnet control_v11p_sd15_mlsd_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_mlsd_fp16.yaml ./ComfyUI/models/controlnet control_v11p_sd15_mlsd_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_normalbae_fp16.safetensors ./ComfyUI/models/controlnet control_v11p_sd15_normalbae_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_normalbae_fp16.yaml ./ComfyUI/models/controlnet control_v11p_sd15_normalbae_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_openpose_fp16.safetensors ./ComfyUI/models/controlnet control_v11p_sd15_openpose_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_openpose_fp16.yaml ./ComfyUI/models/controlnet control_v11p_sd15_openpose_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_scribble_fp16.safetensors ./ComfyUI/models/controlnet control_v11p_sd15_scribble_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_scribble_fp16.yaml ./ComfyUI/models/controlnet control_v11p_sd15_scribble_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_seg_fp16.safetensors ./ComfyUI/models/controlnet control_v11p_sd15_seg_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_seg_fp16.yaml ./ComfyUI/models/controlnet control_v11p_sd15_seg_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_softedge_fp16.safetensors ./ComfyUI/models/controlnet control_v11p_sd15_softedge_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15_softedge_fp16.yaml ./ComfyUI/models/controlnet control_v11p_sd15_softedge_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15s2_lineart_anime_fp16.safetensors ./ComfyUI/models/controlnet control_v11p_sd15s2_lineart_anime_fp16.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v11p_sd15s2_lineart_anime_fp16.yaml ./ComfyUI/models/controlnet control_v11p_sd15s2_lineart_anime_fp16.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v1p_sd15_brightness.safetensors ./ComfyUI/models/controlnet control_v1p_sd15_brightness.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v1p_sd15_illumination.safetensors ./ComfyUI/models/controlnet control_v1p_sd15_illumination.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v1p_sd15_qrcode_monster.safetensors ./ComfyUI/models/controlnet control_v1p_sd15_qrcode_monster.safetensors
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/control_v1p_sd15_qrcode_monster.yaml ./ComfyUI/models/controlnet control_v1p_sd15_qrcode_monster.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_canny_sd15v2.pth ./ComfyUI/models/controlnet t2iadapter_canny_sd15v2.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_canny_sd15v2.yaml ./ComfyUI/models/controlnet t2iadapter_canny_sd15v2.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_color_sd14v1.pth ./ComfyUI/models/controlnet t2iadapter_color_sd14v1.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_color_sd14v1.yaml ./ComfyUI/models/controlnet t2iadapter_color_sd14v1.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_depth_sd15v2.pth ./ComfyUI/models/controlnet t2iadapter_depth_sd15v2.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_depth_sd15v2.yaml ./ComfyUI/models/controlnet t2iadapter_depth_sd15v2.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_keypose_sd14v1.pth ./ComfyUI/models/controlnet t2iadapter_keypose_sd14v1.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_keypose_sd14v1.yaml ./ComfyUI/models/controlnet t2iadapter_keypose_sd14v1.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_openpose_sd14v1.pth ./ComfyUI/models/controlnet t2iadapter_openpose_sd14v1.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_openpose_sd14v1.yaml ./ComfyUI/models/controlnet t2iadapter_openpose_sd14v1.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_seg_sd14v1.pth ./ComfyUI/models/controlnet t2iadapter_seg_sd14v1.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_seg_sd14v1.yaml ./ComfyUI/models/controlnet t2iadapter_seg_sd14v1.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_sketch_sd15v2.pth ./ComfyUI/models/controlnet t2iadapter_sketch_sd15v2.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_sketch_sd15v2.yaml ./ComfyUI/models/controlnet t2iadapter_sketch_sd15v2.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_style_sd14v1.pth ./ComfyUI/models/controlnet t2iadapter_style_sd14v1.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_style_sd14v1.yaml ./ComfyUI/models/controlnet t2iadapter_style_sd14v1.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_zoedepth_sd15v1.pth ./ComfyUI/models/controlnet t2iadapter_zoedepth_sd15v1.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/t2iadapter_zoedepth_sd15v1.yaml ./ComfyUI/models/controlnet t2iadapter_zoedepth_sd15v1.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/image_adapter_v14.yaml ./ComfyUI/models/controlnet image_adapter_v14.yaml
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/ip-adapter-plus-face_sd15.pth ./ComfyUI/models/controlnet ip-adapter-plus-face_sd15.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/ip-adapter_sd15.pth ./ComfyUI/models/controlnet ip-adapter_sd15.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/ip-adapter_sd15_light.pth ./ComfyUI/models/controlnet ip-adapter_sd15_light.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/ip-adapter_sd15_plus.pth ./ComfyUI/models/controlnet ip-adapter_sd15_plus.pth
__term_sd_task_pre_ext_38 aria2_download https://huggingface.co/licyk/controlnet_v1.1/resolve/main/sketch_adapter_v14.yaml ./ComfyUI/models/controlnet sketch_adapter_v14.yaml